### ISSUE TITLE
Logo(s)

### ISSUE THREAD

**Issue by ninmesara** [ReactiveX/RxPY#103]
RxPY should have an official logo.
I've thought of two possibilities myself:

- Two snakes, python's colors (python's logo is actually two stylized snakes together):

![double-snake](https://cloud.githubusercontent.com/assets/16024629/16091591/411542b6-332c-11e6-90e6-60c2cbf8630c.png)

- Single snake, python's colors:

![single-snake](https://cloud.githubusercontent.com/assets/16024629/16091448/9039edfc-332b-11e6-9f79-3306147f1478.png)

- @dbrattli 's been working on a logo too:

![hp0r2zna](https://cloud.githubusercontent.com/assets/16024629/16091450/9333c988-332b-11e6-8f90-b5945c7769b2.jpg)

What do people think about these logos?

**Comment by dbrattli** [comment]
The Rx logo is of an electric eel. We cannot use that logo in Python. For Python we need a python snake and not an electric eel with "python" colors. If I wanted to publish the logo I would have done so, but it's not ready yet and don't really want this up for discussion.

**Comment by ninmesara** [comment]
Ok, it makes sense.
Never thought of it as an electric eel, more like some kind of dragon (which is more like a snake).
But sure, snake it is then :)

**Comment by dbrattli** [comment]
Just use the original Rx logo for now
