### ISSUE TITLE
GEventScheduler missing schedule_periodic function

### ISSUE THREAD

**Issue by geospock-bob** [ReactiveX/RxPY#106]
Hello,

We're using _grequests_ and thus _gevent_ on a project, so I was keen to use the _GEventScheduler_. I started off with a simple Observable with the _interval_ operator, but this failed due to _GEventScheduler_ missing the **schedule_periodic** function:

```
    Observable \
        .interval(1000, scheduler=GEventScheduler()) \
        .map(lambda l: generate_request(l)) \
        .batch_create() \
        .subscribe(self.viewer)
```

Results in:

```
Traceback (most recent call last):
  File "/Users/Bob/Library/Python/2.7/lib/python/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/Bob/Library/Python/2.7/lib/python/site-packages/gevent/pool.py", line 119, in _run
    for item in self.iterable:
  File "./test.py", line 64, in gen
    raise item.exception
AttributeError: 'GEventScheduler' object has no attribute 'schedule_periodic'
<IMapUnordered at 0x1070a2b90> failed with AttributeError
```

So looking through the code, I found the **SchedulePeriodicRecursive** class, so monkey patched (if that's the right term) the _GEventScheduler_ with the following: 

```
def schedule_periodic(self, period, action, state=None):
    scheduler = SchedulePeriodicRecursive(self, period, action, state)
    return scheduler.start()

GEventScheduler.schedule_periodic = schedule_periodic
```

This appears to then allow the _interval_ operator to work correctly, although it does drift over time.

Is the lack of a **schedule_periodic** function in _GEventScheduler_ on purpose? Is this the correct way to work around it? If not, should I fork and send a pull request for this to be included?

Cheers,

Bob.

**Comment by dbrattli** [comment]
Thanks, note that I'm currently camping in Africa, so will not have time to look at this until early august.

**Comment by dbrattli** [comment]
Yes, please send a PR.

**Comment by erikkemperman** [comment]
I guess this is resolved? At least in current master this scheduler inherits `scheduler_periodic` from its base class.
