### ISSUE TITLE
state is always None if schedule_relative with EventLoopScheduler

### ISSUE THREAD

**Issue by MichaelSchneeberger** [ReactiveX/RxPY#107]
eventloopscheduler.py on line 58:
`return self.schedule_absolute(duetime + self.now, action, state=None)`

In my opinion state should not be forced to None:
`return self.schedule_absolute(duetime + self.now, action, state)`

**Comment by dbrattli** [comment]
Thanks, note that I'm currently camping in Africa, so will not have time to look at this until early august.

**Comment by dbrattli** [comment]
Fixed in develop
