### ISSUE TITLE
debounce() in ms or seconds?

### ISSUE THREAD

**Issue by tjf** [ReactiveX/RxPY#109]
The code, docs and tests seem to indicate that it should be an integer value representing the number of milliseconds.  However, the examples (autocomplete_asyncio, for example) seem to use floating point (0.750, vs 750 for 750ms)

I've tried both, but I'm getting very odd behavior either way..  When using any value over 100, I don't get any items emitted at all.

v1.5.2

**Comment by dbrattli** [comment]
Thanks, note that I'm currently camping in Africa, so will not have time to look at this until early august.

**Comment by dbrattli** [comment]
The example was wrong, and fixed in develop branch. Should be 750 for 750 ms. Just tested both the develop and master branch and cannot find anything wrong with `debounce()`. Which scheduler are you using?
