### ISSUE TITLE
GEventScheduler schedule_absolute and now is not working

### ISSUE THREAD

**Issue by alexcwyu** [ReactiveX/RxPY#112]
schedule_relative is fine
schedule_absolute is not working

the root cause is "now" is not working, always return 1970, instead of current time.
looks like we divide extra 1000 on the timestamp when convert the current time.

**Comment by dbrattli** [comment]
Feel free to create a PR.

**Comment by erikkemperman** [comment]
It looks like this was resolved; the original `now` implementation was corrected, with no further change, as a side-effect of the switch from millis to seconds (https://github.com/ReactiveX/RxPY/commit/85b816374dc8b0928c5ac6a5df498a306bc38af2#diff-c30dfb804aaa447273ddbcf68afa7b0b).
