### ISSUE TITLE
Stream operations on multiple fields

### ISSUE THREAD

**Issue by lucidbee** [ReactiveX/RxPY#113]
I don't know if this is the right place, I apologize if this is the wrong place. I am trying to use RxPy on the following problem. 

If I have a stream of 3 random integer values separated by commas:
3, 5, 8
2, 1, 5
...
and I want to turn this into a stream of two integer values field1 + field3, field2
11, 5
7, 1
...
I am having problems getting the output that I want. 
When I use map() on the original stream I can compute either 
field1+field3 and output that (this works) or I can use map() and output field2 (that works)
but I can't get the output of two columns concatenated from distinct computations on the original 
stream. 
What operators would I use to do this?
Is there a way to split the original stream into two identical streams? and operate on each and then merge? Or is that not supported?
What seems to happen is when I do the map() the first time the fields I don't select are no longer accessible.

**Comment by dbrattli** [comment]
Not sure I understand. What's the data type you are using for your comma separated values? If you are using tuples you can just create your new tuple in the `map()` operator.

`.map(lambda x: (x[0]+x[2], x[1]))`

**Comment by MainRo** [comment]
Closing this old question. Please re-open it if it is still relevant.
