### ISSUE TITLE
Multiple Subscribers not Working with 1.5.3

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxPY#134]
I am finding multiple issues with 1.5.3 (see #133 for other critical issue). When I do this simple operation with two Subscribers on a cold Observable, I only receive emissions for the first one. 

```python
from rx import Observable

source = Observable.from_(["Alpha","Beta","Gamma","Delta","Epsilon"])

source.subscribe(lambda s: print(s))
source.subscribe(lambda s: print(s))
```

**OUTPUT:**

```
Alpha
Beta
Gamma
Delta
Epsilon
```

I have to teach RxPy through an O'Reilly video a week from today, and I'd prefer to not have to tell viewers to use 1.5.2 until fixes are put in. I also need the `ThreadPoolScheduler`. Is it possible this is a quick fix?

**Comment by dbrattli** [comment]
Should be fixed by 1.5.4.

**Comment by thomasnield** [comment]
Excellent!  I'll take a look today. Thank you for all your awesome work on this project.

**Comment by thomasnield** [comment]
Confirmed this issue is resolved. Looking at #133 next.
