### ISSUE TITLE
It's not possible anymore to subscribe to Observable.range mutiple times

### ISSUE THREAD

**Issue by MichaelSchneeberger** [ReactiveX/RxPY#143]
The following code ...
```
from rx import Observable

ts = Observable.range(1, 3)
ts.subscribe(print)
ts.subscribe(print)
```
... prints ...
> 1 2 3

... but used to print (before the commit on the 27 May 2016) ...

> 1 2 3 1 2 3

Why does it makes sense to dispose the overservable "range" after the first subscription?

**Comment by dbrattli** [comment]
Should be fixed now. Please re-open if you still have problems.

**Comment by AXGKl** [comment]
works here now, and the fix looks nice. Did you forget [this](https://github.com/ReactiveX/RxPY/commit/1e32e318583a7b8ba3ea7c6521badacc4b951844) print or you really want it in?
