### ISSUE TITLE
How to contribute to RxPY

### ISSUE THREAD

**Issue by AXGKl** [ReactiveX/RxPY#149]
Hi Dag, 

this is a "meta" question. If there was any comm. thread in the past clarifying those things then link me to it, did not find sth.

Problem Statement:

- Github, until you, as owner, merge or reject a PR, does not allow separate PRs, at least it seems so. 
- Any commit into my fork does land in the one open PR on development branch (just closed [this](https://github.com/ReactiveX/RxPY/pull/148) since it is already containing 3 unrelated small things and I have a few more locally still)
- Since this is a (fantastic) **spare time** project of yours, you can't check open PRs on a daily basis. 

My problem is that I have not this one big contributuion going on, justifying (in my world) a feature branch. But, as a beginner with RxPY, I have many smallish things, which do not justify branches (or do they?).

So, how you want contributions in the following cases:

1. Small corrections like typos in the docstrings
1. Small fixes like the missing default for scheduler in `time_interval`
1. Additional Documentation like [this](https://github.com/axiros/RxPY/tree/develop/notebooks/reactivex.io)
1. Additional tests

Alternatives as far as I can see:

1. Letting all accumulate in one PR (with clear commit messages) and you accept, reject or cherry pick - easy for us but maybe you don't like that(?). We could redeclare/generalize the PR title with any new addition.

1. Separate branches for each and anything

1. Contributors wait with next push to their forks until you accept their current open PR on dev. branch

1. Other flows I'm not aware of?

-----

Regarding the additional tests: You have tons of tests based on the Virtual Time Testscheduler, allowing fast test times. But they are hard to understand for beginners. Would you even appreciate some tests based on the normal schedulers, e.g. using marbles to set up streams? 

Upside: Tests will better document, for beginners
Downside: Testtime

My suggestion: Putting those beginner use cases in IPython Notebooks, incl assertions. I could add assertions e.g. [here](https://github.com/axiros/RxPY/tree/develop/notebooks/reactivex.io).
Not have them run on travis all the time but on demand. Should one fail then beginners will send issues anyway.

-----

Cheers, many thanks for this work. Python has many async features but this is as far as I can see the only project which allows for proper coordination.

**Comment by dbrattli** [comment]
Thanks for feedback. With regards to PRs you can submit small or large, but with larger PRs the chance of rejection increases. For correction and cleanup this should not be a problem. But branches are quick and easy with Git, so nothing is too small for a branch. Make sure you check out https://storify.com/koenkivits/open-source-contribution-tips-by-andre-staltz

Tests should always use the `TestScheduler` which makes sure they run in virtual time. We don't want test to block or sleep, so only use a separate scheduler if it never sleeps. Sometimes we do need to test with a given scheduler, but then we must make sure that sleeps are very very short.

**Comment by AXGKl** [comment]
Thanks also for the feedback. Yours and André's policies make a lot of sense and matches also what the git guys in my company tell me, branches can be supersmall, its no problem at all in git (I'm from the mercurial camp and have to finally learn that git branches are far more like bookmarks in hg than branches which are heavy there).

- https://github.com/ReactiveX/RxPY/pull/152 we should close then and I explode it into branches then, rite?  To defined myself: I've put the all the "small stuffs in", since in the notebooks I depend on them (except the bool marbles suggestion, 2 lines which you can just delete without breaking anything. Should have done an issue for that.)


- Regarding tests it is understood with VirtTime (and technically amazying). Downside: Very hard to learn for beginners from test code how to do 'real' things - maybe those ipython notebooks do make sense as an addition for them then and the work was not in vain.

**Comment by dbrattli** [comment]
Let the PR be (not close) for now, but I'll need some time to go through it. The additions are fine (fail forward), but need to go through the changes for `tofuture` etc.

**Comment by AXGKl** [comment]
Closing seems all pretty canonical - the problem was me with my mercurial thinking that branches are too heavy. Thanks for the link to Andre's hints.
