### ISSUE TITLE
to_list() produces different lists when subscribing multible times

### ISSUE THREAD

**Issue by MichaelSchneeberger** [ReactiveX/RxPY#156]
The following code ...
```
xs = Observable.range(0, 3).to_list()
xs.subscribe(print)
xs.subscribe(print)
```
... prints ...

> [0 1 2]
> [0 0 1 2]

... but should print ...

> [0 1 2]
> [0 1 2]

**Comment by thomasnield** [comment]
What version of RxPy are you using?

**Comment by MichaelSchneeberger** [comment]
Version 5.1.8

**Comment by thomasnield** [comment]
Has this been resolved guys?

**Comment by thomasnield** [comment]
I ran this on my end and it looks like I'm also getting an incorrect output. I can try to help debug later, but we probably should resolve this quickly. 

```
[0, 1, 2]
[0, 0, 1, 2]
```

**Comment by thomasnield** [comment]
Oh, @dbrattli you have a fix on the `develop` branch. I suppose I should be using that branch too! Sorry, I like to live dangerously but I'll put my future additions on there.
