### ISSUE TITLE
`generate` method cannot be re-subscribed

### ISSUE THREAD

**Issue by yarosla** [ReactiveX/RxPY#157]
Test case:

    Observable.generate(1,
                        lambda x: x <= 3,
                        lambda x: x + 1,
                        lambda x: x) \
        .repeat(3) \
        .subscribe(lambda x: logger.debug('got %s', x),
                   lambda x: logger.debug('err %s', x),
                   lambda: logger.debug('completed'))

Expected output:

    got 1
    got 2
    got 3
    got 1
    got 2
    got 3
    got 1
    got 2
    got 3
    completed

Actual output:

    got 1
    got 2
    got 3

**Comment by yarosla** [comment]
I've submitted pull request https://github.com/ReactiveX/RxPY/pull/158 to fix this.

**Comment by dbrattli** [comment]
This is fixed in 1.5.8. Closing. Please reopen if you think it's still a problem.
