### ISSUE TITLE
marbles error on windows10 in japan(utc+9)

### ISSUE THREAD

**Issue by katsuooo** [ReactiveX/RxPY#162]
I tryed your tutorial for marbles in windows10

"marbles tutorial" 
https://github.com/ReactiveX/RxPY/blob/develop/notebooks/Getting%20Started.ipynb

from rx.testing import marbles
xs = Observable.from_marbles("a-b-c-|")
xs.to_blocking().to_marbles()

I get Error in this code.
error last line
  File "c:\python36\lib\site-packages\rx\concurrency\schedulerbase.py", line 60, in to_relative
    timespan = timespan - datetime.fromtimestamp(0)
OSError: [Errno 22] Invalid argument

I change code in rx/concurrency/schedulerbase.py
class SchedulerBase / def def to_relative(cls, timespan):
            #timespan = timespan - datetime.fromtimestamp(0)
            timespan = timespan - datetime(1970,1,1)

This code run without error.
In ubuntu16.04, I don't get this error.

Best regards.

**Comment by dbrattli** [comment]
This is a bug in Python 3.6. https://bugs.python.org/issue29100

**Comment by katsuooo** [comment]
I don't check your requirement.
I use rxpy in Python3.4.
