### ISSUE TITLE
Statistical Functions for RxPy

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxPY#167]
Since Python is used for data science quite a bit, it might be helpful to add more statistical functions beyond `sum()`, `min()`, `max()`, `average()`, etc.

Here are some I'm thinking of adding. @dbrattli let me know if you are opposed to this idea and I'll drop it. Otherwise I'll add these in a few days:

* `median()` - finds the median of the finite sequence of numbers
*  `mode()` - finds the most frequent occurring emission
* `standard_deviation()` -  calculates the standard deviation of a sequence of numbers
*  `variance()` - calculates the variance of  a sequence of numbers

**Comment by dbrattli** [comment]
Sounds like a great idea!

**Comment by thomasnield** [comment]
I added `median()` and `mode()`, as well as `to_sorted_list()` which exists in RxJava.

**Comment by thomasnield** [comment]
Just put in `variance()` and `standard_deviation()` as well. I didn't put any coverage for these, I'll look into adding unit tests later. But I manually ran some cases against an Excel workbook and these seem to run great. 

It's always a fun challenge trying to multicast instead of collecting items into intermediary lists. Unfortunately, I think it was necessary to collect emissions into lists for some parts of the implementations. 

We will start with these four statistical operators. I may add more later.

**Comment by thomasnield** [comment]
Should we do a release @dbrattli? I think I've done enough damage for now.
