### ISSUE TITLE
Side effects

### ISSUE THREAD

**Issue by favetelinguis** [ReactiveX/RxPY#170]
Is it possible to do side effects in a stream? For example inserting values in mongodb in the middle of a stream pipeline?

**Comment by thomasnield** [comment]
The best solution is to multicast at that point, rather than creating a side effect using `doAction()`. Multicasting essentially forces subscribers to receive the same stream of emissions from the source, rather than creating separate streams from the source. 

```python

from rx import Observable

source = Observable.from_(["Alpha", "Beta", "Gamma", "Delta", "Epsilon"])  \
    .map(lambda s: len(s)) \
    .publish() # multicast so emissions go to both subscribers

# send to database
source.subscribe(lambda i: print("Writing {0} to database!".format(i)))

# send to list
source.to_list() \
    .subscribe(lambda list: print("Received List {0}".format(list)))


# fire!
source.connect()
```

**OUTPUT:**

```
Writing 5 to database!
Writing 4 to database!
Writing 5 to database!
Writing 5 to database!
Writing 7 to database!
Received List [5, 4, 5, 5, 7]
```

On the next release, you can use `auto_connect()` to automatically mutlicast and start firing when x number of subscribers are subscribed.

```python

from rx import Observable

source = Observable.from_(["Alpha", "Beta", "Gamma", "Delta", "Epsilon"])  \
    .map(lambda s: len(s)) \
    .publish() \
    .auto_connect(2) # fire as soon as there are two subscribers

# send to database
source.subscribe(lambda i: print("Writing {0} to database!".format(i)))

# send to list
source.to_list() \
    .subscribe(lambda list: print("Received List {0}".format(list)))
```

**Comment by thomasnield** [comment]
More info: https://github.com/ReactiveX/RxPY#multicasting

**Comment by AXGKl** [comment]
Hi, I think this example is, besides the publish & run concurrent option, also relevant regarding running sideeffects:

https://github.com/ReactiveX/RxPY/blob/master/examples/autocomplete/autocomplete_asyncio.py

```python
# here a result stream is created, containing the results from the sideeffect:
searcher = query.flat_map_latest(search_wikipedia)
```

**Comment by favetelinguis** [comment]
@thomasnield Thanks for the example, however I have a few questions regarding this implementation (might apply generally to rx).

My Observable is a Custom Hot Observable wrapping a python queue implemented with something like this:
```
def custom_observable(observable):
   while True:
      observable.on_next(queue.get())
```
Then I create an Observable
```
source = Observable.create(custom_observable).share()
```
Now the issue I have is related to my lack of understanding how concurrency work in rxpy.
Since my observable is blocking I can not execute it on the main thread so i use:
```
source.subscribe_on(work_threadpool)...
```
This effect of doing this is that my observable executes and blocks on its own thread from work_threadpool.

Now I want to add another subscription (here is where im getting lost).
```
source.subscribe_on(work_threadpool)...
```
What does subscribe_on do in this second subscription? My infinite observable is already started so could I not just use subscribe_on in my first subscription and then a regular subscribe in all other cases?

And the second issue I have is that when saving stuff to a database I want to use a different threadpool would the solution be to just use source.observe_on(repository_threadpool)...??? In this case I have stared the infinite observer on a separate thread but then I switch threadpool when I save to the database?

Is this reasoning sound or what am i missing?

**Comment by thomasnield** [comment]
```python
def custom_observable(observable):
   while True:
      observable.on_next(queue.get())
```

I'm curious, does `queue` block if there are no more items and it waits for more? If so, that is technically fine. Without having context, I feel like there should be a more reactive way to not use a queue and have the source be reactive too unless you don't own that source. 

Regarding `subscribe_on()`, that should go before the `share()` most likely. 

```python
source = Observable.create(custom_observable).subscribe_on(work_threadpool).share()
```
Doing `subscribe_on()` with mutlicasting can be nuanced. The `share()` is a single proxy subscriber to the source and it might disregard `subscribe_on()` requests from the downstream after `share()`. But before, it should work fine. `observe_on()` is what you will want to use to switch threads _after_ the `share()`.

**Comment by thomasnield** [comment]
Regarding your database operation, I think that is right. `subscribe_on()` is going to have no effect at this point, so `observe_on()` is what you will want to use to switch to a different thread _at that point_ in the Observable chain.

**Comment by dbrattli** [comment]
The Rx way of composing side-effects into the stream is to use the `select_many()` operator. The results of the side-effects may then be merged back into the stream. With `select_many` you basically swap the value for a new stream that will eventually get the result of that operation. This stream of streams is the merged back into a single stream of results.

**Comment by favetelinguis** [comment]
@dbrattli Thanks for the tip, could you please provide an illustrative example since im new to Rx it would really help.

**Comment by favetelinguis** [comment]
@dbrattli After some research I have come up with this solution, not sure why I would use select_many instead of flat_map though or even if this is the solution you had in mind?
```py
stream.flat_map(
    lambda x: Observable.just(x).subscribe_on(io_scheduler).map(lambda y: side_effect(y))
)...Continue process stream
```

However this implementation does not preserve order, is it even possible to do async io and preserve order with rxpy?

**Comment by AXGKl** [comment]
@favetelinguis:

select_many and flat_map are equal.

There is a built in aliasing machinery, since there evolved two pretty disjunct namespaces for the same operations on streams (see rx website) and via this alias mechanics RxPY supports both:

```ack flat_map
linq/observable/selectmany.py
7:def _flat_map(source, selector):
19:@extensionmethod(Observable, alias="flat_map")
```

Regarding order, don't understand exactly what you mean but I have the feeling you should consider flat_map_latest as well, with that nice example in `https://github.com/ReactiveX/RxPY/blob/master/examples/autocomplete/autocomplete_asyncio.py` - at least for me thats all I needed to understand to do side effects for my stuff.

**Comment by favetelinguis** [comment]
The thing with order if when things are done async, if you receive 1 2 3 in sequence and then do an async side effect on then the order they are returned might be different depending on how long they take to complete.

**Comment by AXGKl** [comment]
exactly. So: 
IF you want the results of your side effects back in the original event stream
AND the order of events preserved

you must do each side effect one after the other, you don't want to run them concurrently, right?

If so I can give you an example using flat_map.

**Comment by favetelinguis** [comment]
Yes plz show me.

**Comment by AXGKl** [comment]
using greenlets as async framework I do sideeffects like this:

- I have a stream of events, e.g. from web requests coming. 
- I want to do various sideeffects async, one after the other (not concurrent), based on data within those streams
- I want the results of those async operations within the original stream

I normally "do" this like so: 

```python
from rx     import concurrency, Observable as O
from gevent import event, spawn
from random import randint
from time   import sleep, time

class SideEffectRunner(object):
    '''
    Intended to be subclassed for various side effectors overriding the
    do function, e.g. CmdRunner(SideEffectRunner) with a do function running
    a cmd on the os
    '''
    def __init__(self, ev, **work):
        self.ev = ev
        self.res = self.set_wip(work)

    def set_wip(self, work):
        'wip = work in progress'
        wip = event.AsyncResult()
        spawn(lambda: self.do(**work)).link(wip)
        return wip

    def do(self, **work):
        'spawned into a green thread'
        sleep(work['dt']/1000.)
        return 'done, took %(dt)s millis' % work

    def subscribe(self, on_next, on_error, on_completed):
        self.ev['result'] = self.res.get()
        on_next(self.ev)
        on_completed()

def p(ev): print ev
ts = time()
s = ( O.from_([{'id': 1}, {'id': 2}, {'id': 3}])
       .flat_map(lambda ev: SideEffectRunner(ev, dt=randint(100, 1000)))
    ).subscribe(p)
print 'overall this took %.2f secs' % (time() - ts)
```
```
~ $ python se.py 
{'id': 1, 'result': 'done, took 304 millis'}
{'id': 2, 'result': 'done, took 914 millis'}
{'id': 3, 'result': 'done, took 812 millis'}
overall this took 2.05 secs
```

That could be done in less lines of code but this approach allows to register the work in progress by value of predefined keys in the `work` definition, which then in turn allows, that two requests coming in concurrently triggering the **same** kind of work (e.g. pull a repo to local), would only run once, with the second returning the same result once the work is finished.

I omitted that registration by work definition in the code above, to not overload the reader.

Hope it helps.
