### ISSUE TITLE
BlockingObservable Needs more Operators

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxPY#172]
I'm going to add some additional blocking operators to the BlockingObservable later, particularly`first()`, `first_or_default()`,, and `last()`

https://github.com/ReactiveX/RxJava/wiki/Blocking-Observable-Operators

**Comment by thomasnield** [comment]
Just pushed these to the `develop` branch, and they worked great. @dbrattli can we do a release soon with all these new goodies? I would volunteer but I've never released a Python binary before. I've only done Java...

I've been using RxPy for a contract at my brother's company, and it's been working out fantastically for data wrangling.

**Comment by dbrattli** [comment]
Good to hear! Have just release a new version 1.5.9.

**Comment by thomasnield** [comment]
Nice!
