### ISSUE TITLE
Question: How to gracefully close resources upon POSIX signals in a RxPY application?

### ISSUE THREAD

**Issue by marccarre** [ReactiveX/RxPY#177]
(Apologies in advance if there is already an example illustrating this, I couldn't find anything despite several searches.)

## Scenario

You have:
- an infinite source (`Observable`),
- `0..n` intermediate processing stages,
- a sink (`Observer`) which needs to **close resources in a clean way** (e.g. connection to DB).

## Questions

1. What would the RxPY-y way to stop the full pipeline upon **external** events, i.e. interrupt the infinite source and propagate this interruption, so all resources are gracefully closed? 
An external event could be, for example, POSIX signals like `SIGINT` (`ctrl-c`) or `SIGTERM` (`kill <pid>`).

2. Is the below solution the best way to proceed?

3. Is there a way the signal handling could be wrapped as an `Observable` and added to the pipeline even though most of the time it wouldn't yield anything? Do I need a special scheduler for this?

4. What if the source also needs to close a connection?

## Current state

Source code:
```
def source():
	''' Infinitely yield values. '''
	x = 0
	while True:
		x += 1
		yield x

from rx.concurrency import CurrentThreadScheduler
scheduler = CurrentThreadScheduler()

import signal
def handler(signum, frame):
	def stop(scheduler, state=None):
		raise StopIteration()
	# Send exception down the pipeline to stop everything:
	scheduler.schedule(stop)
signal.signal(signal.SIGINT, handler)
signal.signal(signal.SIGTERM, handler)

import time
def processor(x):
	time.sleep(1) # Do work...
	return x + 1

from rx import Observer
class sink(Observer):
	def on_next(self, value):
		print(value)
		return value
	def on_completed(self):
		print('Closed upon completion.')
	def on_error(self, error):
		print('Closed upon error.')

from rx import Observable
Observable.from_(source(), scheduler).map(processor).subscribe(sink())
```

Output for `SIGINT`:
```
$ python example.py 
2
3
## In a separate shell: $ kill -s SIGINT <pid>
4
Closed upon error.
```

Output for `ctrl+C` in the same shell:
```
$ python rxpy.py 
2
3
^C4
Closed upon error.
```

Output for `SIGTERM`:
```
$ python example.py 
2
3
## In a separate shell: $ kill -s SIGTERM <pid>
4
Closed upon error.
```

**Comment by potbunker** [comment]
One of the operations you are supposed to use for such a scenario is `using`.

```python
class ConnectionFactory(Disposable):
    def __init__(self):
        self._conn = connection

    @property
    def connection():
        return self._conn

    def dispose():
        self._conn.close()

def to_data(conn_factory):
    conn = conn_factory.connection
    def subscribe(observer):
        while True:
             observer.on_next(<something from the connection>)
    return Observable.create(subscribe)

o = Observable.using(ConnectionFactory, to_data)
```
So when stream completes, `ConnectionFactory`'s `dispose` method will be invoked. It is similar to context manager in vanilla python.
However, I am having some difficulty to get everything working smoothly.

Another idea is to have a `Subject` to pass signal event to the observer, and use `take_until` operator.

```python
s = Subject()

def handler(signum, frame):
    s.on_next(signum)

source.take_until(s).map(processor).subscribe(sink)
```

**Comment by dbrattli** [comment]
Closed due to inactivity
