### ISSUE TITLE
Flask Socket

### ISSUE THREAD

**Issue by GiovanninoPaneEvino** [ReactiveX/RxPY#178]
Hello,
I am sure this is an easy one :-)
Could somebody suggest me how to create an observable from an event from flask-socket?

I tried to use the from_callback method like:

from flask import Flask
from flask_socketio import SocketIO
from rx import Observable, Observer

app = Flask(__name__)
socketio = SocketIO(app)

class MyObserver(Observer):
    def on_next(self,x):
        print("Got: %s" % x)

    def on_error(self,e):
        print("Got error: %s" % e)

    def on_completed(self):
        print("Sequence completed")

[...]

socket_observable = Observable.from_callback(socketio.on_event)
socket_my_event = socket_observable('my event')
socket_my_event.subscribe(MyObserver())

Unfortunately after one call on the event "my event" from the client the observer doesn't get updated.

Any idea?

Thank you!!!

**Comment by MainRo** [comment]
Closing this old question. Please re-open it if it is still relevant.
