### ISSUE TITLE
The easiest way to stream from a csv file

### ISSUE THREAD

**Issue by wbeuil** [ReactiveX/RxPY#181]
I start playing with RxPy but I can't find a way to stream a csv file which represents stock ticker with timestamp. Can someone help me to understand how to use scheduler to go back to my first tick and then stream each line from the csv at the exact timestamp ?

    from rx import Observable
    from rx.concurrency import HistoricalScheduler
    import pandas as pd
    from datetime import datetime

    df = pd.read_csv("eurusd.csv", names=['Symbol', 'Date', 'Bid', 'Ask'])
    df['Date'] = pd.to_datetime(df['Date'])

    startTime = df['Date'][0]
    scheduler = HistoricalScheduler(startTime)

    observable = Observable.from_iterable(df, scheduler=scheduler).timestamp(scheduler=scheduler)
    observable.map(lambda l: l)
    observable.subscribe(lambda s: print(s))

    scheduler.start()

**Comment by MainRo** [comment]
You might be interested in [RxSci](https://github.com/maki-nage/rxsci/). It is a data science library based on RxPY.
You can see examples here:
https://www.makinage.org/doc/makinage-book/latest/howto.html#read-a-csv-file

**Comment by dbrattli** [comment]
Closing this. Please feel free to add more questions or discussions in the Discussion tab.
