### ISSUE TITLE
Nested to_blocking leads to infinite lock

### ISSUE THREAD

**Issue by tsydd** [ReactiveX/RxPY#182]
The following code blocks thread
```python
result = (
    rx.Observable.just(None)
    .map(lambda *_: rx.Observable.just(None)
         .to_list()
         .to_blocking()
         .to_iterable()
         .next()
         )
    .to_list()
    .to_blocking()
    .to_iterable()
    .next()
)
```
Expected behaviour - result == None

**Comment by Hong-Xiang** [comment]
I'm facing the same problem. Any solutions?

**Comment by dbrattli** [comment]
You can use a thread based scheduler to avoid running the code on the same thread.

```python
import rx
from rx.concurrency import ThreadPoolScheduler


scheduler = ThreadPoolScheduler()

result = (
    rx.Observable.just(None, scheduler=scheduler)
    .map(lambda *_: rx.Observable.just(None, scheduler=scheduler)
         .to_list()
         .to_blocking()
         .to_iterable()
         .next()
         )
    .to_list()
    .to_blocking()
    .to_iterable()
    .next()
)
```

**Comment by thomasnield** [comment]
@dbrattli is there a trampoline mechanism in these schedulers to prevent recursive scheduling?

**Comment by dbrattli** [comment]
Yes, both `CurrentThreadScheduler` and `ThreadPoolScheduler` has a trampoline for each thread. I think the problem here is that the inner subscription blocks waiting for values (iterating), but this will also block the outer subscription (running on the same thread) and everything comes to halt. Thus you must make sure that the inner and outer subscription runs on different threads.

**Comment by neilvyas** [comment]
This also works using `TimeoutScheuduler`, which I think is more natural to use than `ThreadPoolScheduler`. I ran into this working on 10a0683 before I realized that `comparer` in `.sequence_equal(comparer)` can return an `Observable[bool]` and not just `bool`.

**Comment by dbrattli** [comment]
Closing. Feel free to reopen if you still think it's a bug.
