### ISSUE TITLE
Spam in the wiki

### ISSUE THREAD

**Issue by ubald** [ReactiveX/RxPY#193]
Something's wrong with the wiki.

**Comment by thomasnield** [comment]
Alrighty then, that's weird. We'll clean that up later.

**Comment by thomasnield** [comment]
Thank you, it looks like @dbrattli will have to make that permission change. I don't think I have that ability as a collaborator.

**Comment by dbrattli** [comment]
I can disable the wiki but not change permissions. I'm also just a collaborator. Was there anything useful in the wiki before this started? Should we just disable it?

**Comment by ubald** [comment]
I went there looking for some documentation, there wasn't any ;)

**Comment by dbrattli** [comment]
Wiki disabled
