### ISSUE TITLE
Service Solahart Cipayung 082122541663

### ISSUE THREAD

**Issue by servicecenterkompor** [ReactiveX/RxPY#194]
**Service Solahart Cipayung 082122541663_Service Pemanas AIr Solahart Cipayung Hubungi Call  Center 081313462267 / 082122541663 Email : cs.fikrimandiriajaya@yahoo.com Atau Kunjungi Website Resmi Pemanas Air Solahart http://www.servicesolahart.com/******

**Comment by thomasnield** [comment]
Please stop spamming. I am going to report this account to GitHub.
