### ISSUE TITLE
This does not work in PySide.

### ISSUE THREAD

**Issue by AlexTochka** [ReactiveX/RxPY#204]
https://github.com/ReactiveX/RxPY/blob/99e481e39bd54fad2ff225da4f97687c64b64977/examples/timeflies/timeflies_qt.py#L22
This does not work in PySide. This will work in PySide if changed to:
        super (Window, self) .__ init __ ()
In PyQt this will work too.

**Comment by erikkemperman** [comment]
Just ran the timeflies example on current master, works for by PyQT5 and PySide2.
