### ISSUE TITLE
Any plan of adding PyQt mainloop support?

### ISSUE THREAD

**Issue by ralphjzhang** [ReactiveX/RxPY#21]
Hi, I notice there is a tkinter mainloop scheduler, as PyQt is also very popular and extremely powerful, is there any plan of adding a qt mainloop scheduler?

I'm new to Rx but I'll try to do one first.

**Comment by dbrattli** [comment]
Should not be too difficult. Look at the other schedulers. You basically need to figure out how to schedule timeouts with PyQT. I see there's a QTimer that could work. Please reach out if you need any help, or if you want med to look at some code.

**Comment by jdreaver** [comment]
Hey @dbrattli, I have implemented a Qt mainloop scheduler in my fork of RxPY (see [this commit](https://github.com/jdreaver/RxPY/commit/c1dfa4205cda8df55f20e249a5af2f34eba972b7)). However, I can't open a pull request against the develop branch because it is behind master by 14 commits right now. I think master needs to be merged into develop. What should I do?

**Comment by dbrattli** [comment]
Shouln't be a problem. Just merge master into develop to get up-to-date:

```bash
> git checkout develop
> git merge master
```
Now resolve conflicts, if any and retry the pull request. You may also use `git rebase` here. Isn't that so @leinz?

**Comment by leinz** [comment]
@dbrattli You can use `rebase` or `merge`, but it will make unnecessary noise when pulling in these two commits.

@jdreaver You only have two commits, so the cleanest tool to get them into your `develop` branch is by using `cherry-pick`. First sync your `develop` branch with the upstream repository and then cherry-pick your commits into the develop branch:
```
> git remote add upstream git@github.com:ReactiveX/RxPY.git
> git fetch upstream
> git checkout develop
> git merge upstream/develop
> git cherry-pick aa66978
> git cherry-pick 1d88af9
> git push origin develop   (assuming your remote name is origin)
```
Then you create the pull request from your updated develop branch. Hopefully you can cherry-pick without any conflicts.

If you later want to remove the commits from the `master` branch:
```
> git checkout master
> git reset --hard HEAD~2
> git push -f origin master
```

**Comment by jdreaver** [comment]
Oh, I am silly. I didn't think to simply put the commits on my fork's develop branch. For some reason I just assumed that this repo's develop branch would be more up-to-date with master. Thanks for the info, I'll open the pull request!
