### ISSUE TITLE
Pydev completions for RxPy dont work

### ISSUE THREAD

**Issue by michaeljquinn** [ReactiveX/RxPY#215]
Not sure if this is the right place
But completions dont seem to work in RxPy/PyDev, eg
Observable.create is not there, but Observable.subscribe does complete ??
Ubuntu install for everything
apologies for ignorance

**Comment by dbrattli** [comment]
This is a known issue as RxPY adds methods dynamically to the `Observable` class. This will be fixed in the next major version of RxPY.

**Comment by aellwein** [comment]
Completion doesn't work in PyCharm neither. This can be really annoying if you are a RxPY newbie and want to learn the API by doing.

**Comment by dbrattli** [comment]
Will be fixed in next major version. See the vnext branch.

2018-02-28 18:46 GMT+02:00 Alex Ellwein <notifications@github.com>:

**Comment by iwatchme** [comment]
is there any deadline for next major version，really forward to completions

**Comment by dbrattli** [comment]
There is no deadline, RxPY is not a product, but a community driven effort. You can check out the latest v3 (alpha) version, but docs not finished yet.
