### ISSUE TITLE
many_select is broken

### ISSUE THREAD

**Issue by neilvyas** [ReactiveX/RxPY#218]
I've been working on many_select for a bit and found that it's broken, in the sense that this line:

```python
chain[0] and chain[0].on_next(x)  # x is not an Observable!
```

is not well-typed, and should be

```python
chain[0] and chain[0].on_next(curr)
```

This will break when we attempt to traverse the `tail.merge_observable()` inside `ChainedObservable`. If we only use `first()`, like we do in tests, we don't force this to occur and nothing fails. Check it out:

```python
In [1]: import rx

In [2]: rx.Observable.from_iterable([1, 2, 3]).many_select(lambda x: x.last().subscribe()).subscribe()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

...

AttributeError: 'int' object has no attribute 'subscribe'

In [3]: rx.Observable.from_iterable([1, 2, 3]).many_select(lambda x: x.first().subscribe()).subscribe()
Out[3]: <rx.disposables.anonymousdisposable.AnonymousDisposable at 0x10c6d8910>

In [4]:
```

I'm going to fix this later today.

**Comment by dbrattli** [comment]
Many select has been removed from the code base. Feel free to fix the PR for the new operator format `Callable[[Observable], Observable]' if you want to se it back.
