### ISSUE TITLE
obs1.merge(obs2).subscribe() subscribes first on obs2 and not obs1

### ISSUE THREAD

**Issue by MikeSchneeberger** [ReactiveX/RxPY#220]
The following code ...

```
obs1 = Observable.range(0, 3)
obs2 = Observable.range(10, 3)
obs1.merge(obs2).subscribe(print)
```

... produces ...
```
10
0
11
1
12
2
```
 ... and not as one would expect ....
```
0
10
1
11
2
12
```

The problem is that _self_ gets appended instead of prepended to _args_ in **merge.py** (p. 25)

```
    if not isinstance(args[0], int):
        args = args + tuple([self])
        return Observable.merge(*args, **kwargs)
```

Is there a reason for appending it?

**Comment by dbrattli** [comment]
Both results are valid. The result is impl. (scheduler) dependent. Note that observable streams are about events that happen at a given time. Your example does not have time between the events, only ordering. Thus

```
0
1
2
10
11
12
```

is just as valid as

```
10
11
12
0
1
2
```

**Comment by MikeSchneeberger** [comment]
That means the rx conventions only guarantee the ordering of each cold observable individually, but not the ordering of several cold observables interacting with each other?

**Comment by dbrattli** [comment]
Yes, all events happen at the same point in time. There is no ordering between the different streams (only within the stream). 

PS: This is equivalent to having multiple lists. How would you iterate them? One before the other, one item from each, then second item from each. Is one order more correct than another?
