### ISSUE TITLE
Interval not working correctly

### ISSUE THREAD

**Issue by Megamiun** [ReactiveX/RxPY#221]
I am having problems using the Observable.interval() function on my computer. Below there are the results of me using the function:

```python
from rx import Observable

Observable.interval(1000) \
    .map(lambda i: "{0} Mississippi".format(i)) \
    .subscribe(lambda s: print(s))

Observable.interval(1000) \
    .subscribe(on_next=print, on_error=\
               lambda e: print('if I try to print the error, it does nothing,', e))

Observable.interval(1000) \
    .subscribe(on_next=print, on_error=print('there are errors'))
```
When trying to run it in PyCharm(Tried on terminal too), the exit is:

```
/usr/bin/python3.5 /home/gabryel/git/theLearningBit/learnbit/learnbit.py
there are errors

Process finished with exit code 0
```

At first I thought I was doing something wrong as it is my first time using Rx, but even the first example, that is given on this project README, doesn't work.

I am using python 3.5.2 with RxPy 1.6, I don't know any other information that could help at the moment.

**Comment by jcafhe** [comment]
Hello,

You have to block your main thread or use a loop to let things happen. 

Think rx as a declarative manner to build streams. In your example, your file is executed and finishes directly after your last line. So basically, you have just declared streams but there is no loop to maintain your program alive.

Try to add _time.sleep()_ or _input()_ functions at the end :
```python
input('press enter to exit')
```

Note that you should also provide a function as on_error argument in your last statement:
```python
Observable.interval(1000) \
    .subscribe(on_next=print, on_error=lambda e: print('there are errors'))
```

**Comment by Megamiun** [comment]
Oh, @jcafhe,

Sorry, I didn't understand it! Now it makes a lot more sense why there is an input on the end of the example! I think I should apologize and close this issue now hahahaha

Oh, and do you think it would be a good thing to add to the README's examples? If so, I can try to make a PR for that.

**Comment by thomasnield** [comment]
@Megamiun we always welcome contributions to documentation and README. Please feel free and I'll review and merge.

**Comment by thomasnield** [comment]
And always feel free to join us in the #rxpy channel in PySlackers. This is where a lot of community discussion takes place now, and is more active in answering questions. 

https://pyslackers.com/

**Comment by QuantScientist** [comment]
Hi,
Is it possible to schedule the invocation of a method every N seconds? 
The examples above only run ONCE. I would like to trigger a method every 30 seconds that retrives data from a URL an stores it, I did this until now using the "schedule" Python library. 
Thanks,
