### ISSUE TITLE
Is there a list of other libraries using RxPY ? e.g. State Machine using RxPY

### ISSUE THREAD

**Issue by kavink** [ReactiveX/RxPY#230]
I am interested in building a user configurable State machine which does some i.e. Something like https://mobx.js.org but on server side for Python.

Wondering if there is already some work done or I need to build a configuration example for user on top RxPY, i.e. allow user to configure what to do on_next or on_error or on_complete for a DAG (Directed acyclic graph).

**Comment by MainRo** [comment]
AFAIK there is no such library. We list the libraries we are aware of in the [documentation](https://rxpy.readthedocs.io/en/latest/additional_reading.html)
You may have more answers on the slack channel.
