### ISSUE TITLE
Retry with exception handler

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [ReactiveX/RxPY#231]
I think would be useful pass a handler here

https://github.com/ReactiveX/RxPY/blob/6beb2e2cbb108fdf924561f9431eb4aa610c6ad9/rx/linq/observable/retry.py#L6-L22

https://github.com/ReactiveX/RxPY/blob/0e2a8849617e67c618ff6ed62ee674db323c1a36/rx/linq/observable/catch.py#L38

### Example:

``` python
@extensionmethod(Observable) 
def retry(self, retry_count=None,handler=None):   
  return Observable.catch_exception(Enumerable.repeat(self, retry_count),handler) 

```

**Comment by dbrattli** [comment]
I think `retry` should just retry the source observable. If you need the handler, you should use `catch` directly. Catch has btw just been modified to take the source observable so it's easy to use it for retrying as well.
