### ISSUE TITLE
Dispose leaking?

### ISSUE THREAD

**Issue by diorcety** [ReactiveX/RxPY#244]
I can't provide the full code right now (I have to extract the meaning part) but I have issue with dispose not called in a two thread application. I have tracking down my code to find the issue and I found a "funny" behaviour

```
obs = obs.do_on_subscribe(lambda : logger.debug("AAAA8 Subscribe")).do_on_dispose(lambda : logger.debug("AAAA8 Dispose"))
obs = obs.do_on_subscribe(lambda : logger.debug("AAAA81 Subscribe")).do_on_dispose(lambda : logger.debug("AAAA81 Dispose"))
```
I run a stress test, which will produce 100000(or 10000) loop on a test using this part
I put the stderr in a file and doing a wc on it

> cat tt | grep 'AAAA81 Sub' | wc
>  100000 1100000 7500000
> cat tt | grep 'AAAA8 Sub' | wc 
>  100000 1100000 7400000

Okay that seems logic

> cat tt | grep 'AAAA81 Dis' | wc
>   99986 1099846 7235654

Okay maybe on my code I was leaking some dipose after the code sample.

> cat tt | grep 'AAAA8 Dis' | wc
>   99991 1099901 7135035

What???

Here it's only print, but I have few important dispose actions, which sometime are not called...

**Comment by diorcety** [comment]
Here a simple example

It works well on python 3.5 but not on 2.7

```
def loop(ref_counts):
    lock = threading.Lock()

    def inc(i):
        def fct():
            with lock:
                ref_counts[i] += 1
        return fct

    def dec(i):
        def fct():
            with lock:
                ref_counts[i] -= 1
        return fct

    obs = rx.Observable.interval(0.001)
    obs = obs.do_on_subscribe(inc(0)).do_on_dispose(dec(0))
    obs = obs.take(1)
    sub = obs.subscribe(lambda x: x)
    time.sleep(0.001)
    sub.dispose()

    for a in ref_counts:
        if a != 0:
            print("Error %s" % str(ref_counts))
            raise Exception("exit")


def loop_test():
    ref_counts = [0] * 16
    for i in range(10000):
        print("Loop %d" % i)
        loop(ref_counts)

loop_test()
```

**Comment by diorcety** [comment]
I'm not crazy it should dispose correctly, no?

**Comment by diorcety** [comment]
Linked to https://github.com/ReactiveX/RxPY/blob/master/rx/core/autodetachobserver.py#L31 ???

**Comment by diorcety** [comment]
Okay, I found, https://github.com/ReactiveX/RxPY/blob/master/rx/disposables/singleassignmentdisposable.py#L30
Is set before the lock. If when the lock is taken 3 lines after dipose was called, the value of should_dispose is incorrect

**Comment by diorcety** [comment]
https://github.com/diorcety/RxPY/commit/b55c1a0d0e50362c8d65e4be9e9b71611ef1f14c

**Comment by diorcety** [comment]
There is lot of if object in some parts: https://github.com/diorcety/RxPY/commit/b55c1a0d0e50362c8d65e4be9e9b71611ef1f14c#diff-7ceb5bdf6be1eaca70221674ff7e3787R52
Which is not correct with observable implementing __len__ (found thanks to trace)
SingleAssignement observable isn't just MultipleAssignmentDisposable with a check?
Is it normal that the MultipleAssignmentDisposable  doesn't dispose the old one on set_disposable ?

**Comment by diorcety** [comment]
I missed one thing. this one is the good one: https://github.com/diorcety/RxPY/commit/9828169e495e3e1ae97e52d66f237faee9b2015f

**Comment by dbrattli** [comment]
@diorcety Your commit contains a few things that I'm not sure is relevant to the leak:

1) Always calling `ensure_trampoline`in `ObservableBase`. Why?
2) Not copying disposables `current_disposables = self.disposables[:]` may result in the list of disposable being changed while you traverse. Why this change? Is it relevant for the leak?
3) `should_dispose` is read only. Why do we need to put it inside the lock?

I'm happy that you changes fixed your problem, but I'm still unsure what the problem was and which of the changes did the trick?

**Comment by diorcety** [comment]
1 ensure_trampoline do exactly the same thing (https://github.com/ReactiveX/RxPY/blob/dd4a5cc4b887908a8fc28eb6f762c5243e3c86fa/rx/concurrency/currentthreadscheduler.py#L103)

2 No It isn't. disposables modifications are protected thanks to the lock

3 This is point is the core of the issue. Yes should_dispose is read only. But the value of it is set before the lock. If for example one thread is currently here https://github.com/ReactiveX/RxPY/blob/master/rx/disposables/singleassignmentdisposable.py#L51 and the other one entering here https://github.com/ReactiveX/RxPY/blob/master/rx/disposables/singleassignmentdisposable.py#L30.  You will have should_disposable to False, then wait for the lock to be available (when the other thread releasing the lock) and continue the function like if the disposable was not disposed, but which is not True anymore.

You can easily test that with my code here: https://github.com/ReactiveX/RxPY/issues/244#issuecomment-398116475
You will see that you will lose lot of disposable "dispose" in this case. In almost all the case it's not a problem, except when you use "action" disposable or do_on_dispose, when you really wan't to be called on dispose

**Comment by dbrattli** [comment]
Thanks a lot for the good answer. I'll make a patch later this weekend.
