### ISSUE TITLE
Adding a MainThreadScheduler to RXPY

### ISSUE THREAD

**Issue by favetelinguis** [ReactiveX/RxPY#245]
Im trying to add a scheduler that redirects emissions back to the main thread. The use case if as follows. Im currently getting emissions from an external API that uses its own thread to push emissions. No on my end i publish the emissions and I want one of my subscriptions to block the main thread (to do some console TUI stuff).

I did try the most simple thing I could come up with:

```python
import threading

from rx.concurrency import CurrentThreadScheduler
from rx.core import Scheduler


class MainThreadScheduler(CurrentThreadScheduler):
    def get_queue(self):
        ident = threading.main_thread().ident

        with self.lock:
            return self.queues.get(ident)

    def set_queue(self, queue):
        ident = threading.main_thread().ident

        with self.lock:
            self.queues[ident] = queue

Scheduler.main_thread = main_thread_scheduler = MainThreadScheduler()
```

However this has no effect as evident by the following example:

```python
from rx import Observable
import threading
orders = Observable.of(1)
print(threading.current_thread().name)
orders.do_action(lambda x: print(threading.current_thread().name))\
    .observe_on(NewThreadScheduler())\
    .do_action(lambda x: print(threading.current_thread().name))\
    .observe_on(MainThreadScheduler())\
    .do_action(lambda x: print(threading.current_thread().name))\
    .subscribe(lambda x: print(threading.current_thread().name))
input('holding')
```

Now why is there no Scheduler like this, the need to put things back on the main thread must be there even for others? If this sounds like a good idea maybe someone could help me get this working and we can add it to rxpy?

**Comment by hulucc** [comment]
You can't schedule something to a running thread, and in your case, the main thread is waiting for the input io.
So, generally, the main thread is not schedulable except there is a event loop running on it.

**Comment by erikkemperman** [comment]
You should be able to use the `CurrentThreadScheduler` — If I understand the issue properly it would do what you want, but you have to call the `schedule` methods from the main thread as well.

If you want another thread to do the scheduling, it’s probably not going to work. Certainly not by just overriding the keys as you were trying to do in your snippet.

**Comment by ldulcic** [comment]
How can return emission back to main thread? I'm doing some background work which triggers some UI actions, I need to be on main thread for executing UI actions, how can I do that in RxPY?

**Comment by hulucc** [comment]
Implement a scheduler of your ui event loop and schedule to it.
