### ISSUE TITLE
subscribe_ method in readme tutorial throws AttributeError

### ISSUE THREAD

**Issue by oyeyipowale** [ReactiveX/RxPY#246]
Error

```
Traceback (most recent call last):
...
.filter(lambda i: i >= 5)\
AttributeError: 'AnonymousObservable' object has no attribute 'subscribe_'
```
test env:

- current version of RxPy
- in python IDLE (v 3.5 and v 3.6)

**Comment by dbrattli** [comment]
Please use tutorial at [stable branch](https://github.com/ReactiveX/RxPY/tree/release/v1.6.x). I've added a notice to master branch that it is work in progress.
