### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by lherman-cs** [ReactiveX/RxPY#247]
I can't use any module from RxPy.
<img width="643" alt="screen shot 2018-06-22 at 8 51 31 am" src="https://user-images.githubusercontent.com/15654932/41777517-94c21454-75f9-11e8-8575-c41f0c7f416b.png">

Python environment: Python 3.6.5 on MAC (homebrew)

Steps to reproduce:
* ```pip3 install rx```
* Copy the example from README.md
* Run it

**Comment by dbrattli** [comment]
The documentation of the master branch is for version 2.x that haven't been released yet. You can find the documentation for the 1.6.x branch at https://github.com/ReactiveX/RxPY/tree/release/v1.6.x . I'll add a notice about this to avoid confusion.

**Comment by lherman-cs** [comment]
Got it. thanks @dbrattli
