### ISSUE TITLE
Using RxPy in current thread without any scheduler

### ISSUE THREAD

**Issue by Soamid** [ReactiveX/RxPY#250]
I have some experience working with RxJava and recently I've started project in RxPy. During writing tests I found something that looked like a bug and totally changed expected behavior of my application: if there're nested `subscribe()` operations anywhere in code, instructions are not invoked sequentially, like they were non-blocking. For example:
```python
def test():
    rx.Observable.from_iterable([1,2,3]) \
        .subscribe(lambda x : print(x))
    print("after subscribe")

for i in range(3):
    test()
```
In such case output will be:
```
1
2
3
after subscribe
1
2
3
after subscribe
1
2
3
after subscribe
```
But, if you write this loop using RxPy:
```python
rx.Observable.range(0, 3) \
    .do_action(lambda _ : test()) \
    .subscribe()
```
subscriptions in `test()` function are non-blocking, producing (for example) following output:
```
after subscribe
1
after subscribe
2
1
after subscribe
3
2
1
3
2
3
``` 
After debugging RxPy code I've came to conclusion that all subscriptions are by default scheduled on `CurrentThreadScheduler`, that works like `trampoline()` in RxJava. It's great that we can have such behavior in RxPy, but is it possible to use RxPy **without** scheduling, just like it's working in RxJava by default? 
I think it can be also really confusing for new users, especially that I can't find any information about default behavior in RxPy documentation. :(

**Comment by samiur** [comment]
For these scenarios, you want to use the `immediate_scheduler`.

```python
def test():
    rx.Observable.from_iterable([1,2,3], scheduler=rx.concurrency.immediate_scheduler) \
        .subscribe(lambda x : print(x))
    print("after subscribe")

rx.Observable.range(0, 3, scheduler=rx.concurrency.immediate_scheduler) \
    .do_action(lambda _ : test()) \
    .subscribe()
```

outputs:

```
1
2
3
after subscribe
1
2
3
after subscribe
1
2
3
after subscribe
```

**Comment by Soamid** [comment]
I didn't noticed `immediate_scheduler` when I was digging into RxPy code, thank you!

But after applying this scheduler I found that it works as intended only if is configured by using `scheduler=` keyword argument, if I use `subscribe_on()` instead it works like the default scheduler (like in my example). I thought that invoking `subscribe_on()` is similar to specifying scheduler as an argument? When I use other schedulers, e.g. `NewThreadScheduler` I see no difference and it works ok.

**Comment by dbrattli** [comment]
No it's not the same. `subscribe_on()` is where (scheduler) to run the subscribe logic on (which scheduler calls subscribe. The operator may however choose it's own scheduler. In RxPY v3 you can also supply a scheduler to subscribe to set it as default for all operators up the chain i.e `.subscribe(scheduler=immediate_scheduler)`.
