### ISSUE TITLE
Unexpected scheduling order

### ISSUE THREAD

**Issue by ablaagaard** [ReactiveX/RxPY#262]
Not sure if this is a bug. I was expecting to get the range back ordered?

rx.Observable.range(0,21).buffer_with_count(10).flat_map(lambda x: x).take(15).subscribe(print)

Consistently includes 20 as the second to last item for me:
0
1
2
3
4
5
6
7
8
9
10
11
12
20
13

**Comment by dbrattli** [comment]
Not a bug as `flat_map` merges the subscribed inner streams concurrently. To process the inner streams in order you should use `concat_map` instead (just note that the current impl. of `concat_map` does not support iterables so you must use e.g `from_iterable`. to convert it to an Observable.
