### ISSUE TITLE
while_do  and on_completed/on_error

### ISSUE THREAD

**Issue by akhilman** [ReactiveX/RxPY#263]
Why [while_do](https://github.com/ReactiveX/RxPY/blob/master/rx/operators/iterable/whiledo.py) doesn't handle on_error and on_competed? Seems like we will have frozen iterable in case of on_error/on_completed events.

**Comment by dbrattli** [comment]
The `while_do`operators is concatenating the observables, and `on_error` will be handled by `concat()` and it will terminate the resulting observable. The `on_completed` is handled like an empty observable and the resulting observable will then do nothing until the condition is False, then it will also complete.

**Comment by akhilman** [comment]
Thank you for explanation.
