### ISSUE TITLE
RxPY 3.0: Documentation

### ISSUE THREAD

**Issue by MainRo** [ReactiveX/RxPY#270]
With v3, an official documentation should be provided. This issue can be used to follow the progress on this topic. The following things must be done

- [X] create outline
- [X] migrate part of readme in doc
- [X] reference doc from readme
- [X] add a migration section
- [X] document APIs : autodoc for all operators and classes
- [X] choose a theme : Guzzle. 
- [x] publish the doc somewhere:  https://rxpy.readthedocs.io
- [x] add marble diagrams for operators
- [X] add additional readings section
- [X] license section
- [X] contributing section
- [X] Fix docstring errors in __init__.py
- [x] spellcheck
- [ ] final pass on each section

**Comment by dbrattli** [comment]
There are some theme samples are http://www.writethedocs.org/guide/tools/sphinx-themes/ . Read-the-docs is nice. Also the Guzzle theme looks quite nice and clean.

As for hosting we should be able to get permission to deploy at e.g. http://reactivex.io/rxpy

**Comment by MainRo** [comment]
I have several commits ready. Should I push them on feature/rxpy-3.0 or wait until the merge on master is done ?

**Comment by MainRo** [comment]
Concerning the marble diagrams, initially I wanted to reuse the ones from reactivex.io. However they are not all consistent (there are several graphic styles, depending on the operators). Moreover linking to picture does not allow to see the marble diagram when reading the source code. 

So I wonder if the following could be possible: Create a sphinx addon that would use a tool to convert text based marble diagram to pictures. This would have several advantages compared to static pictures that are hard to update:

- The diagrams are readable in the code documentation.
- They can be easily updated.
- diagrams are automatically available when adding new operators
- diagrams style is consistent.

The main issue here is to get this marble renderer. Surprisingly I did not find such a tool. If anybody is aware of an existing tool, I am interested! Otherwise maybe it could be relatively easy to implement one based on matplotlib. I will try some mocks if we want to document marble diagrams this way.

**Comment by dbrattli** [comment]
We might want to merge with master first. It's now being added new features on the feature branch, so it's time to merge. We can still have a period of rapid development before locking down and starting doing PRs for the master branch.

It would be interesting to see if it would be possible to use [Mermaid flowcharts](https://mermaidjs.github.io/flowchart.html) to generate marble diagrams. They are text based and can be used with Markdown and Sphinx. I haven't tried making marble diagrams, and they won't (currently) render directly on GitHub, but they render e.g on [HackMD](https://hackmd.io/). But I cannot find a way to render to ascii, so it would not be possible to use inside the code doc. Perhaps plain ascii diagrams are simpler and better.

**Comment by MainRo** [comment]
Status update: I enabled the Guzzle theme, the outline should be complete. Now I will work on the content of the missing parts.
Once this is done I will look at the marble diagrams.

**Comment by jcafhe** [comment]
I have some questions regarding the convention we should use(or not) for docstrings, especially in examples. It is not that serious but there are actually multiple ways for naming input/output observables:
Concerning `rx`
```python
>>> res =  ...
>>> obs = ...
>>> merged = ...
>>> rx.merge(obs1, obs2)
>>> rx.merge(xs, ys)
```
Concerning `rx.operators`
```python
>>> res = ...
>>> op = ...
```
When I have the opportunity to update a docstring, I use `res = ` because it seems to be the most common and `rx.merge(obs1, obs2)`. For `rx.operators` I use `op = ...` for denoting that the return value is not an observable but a function.
What do you think ?

**Comment by MainRo** [comment]
I played with a marble diagram generator from text and have a first implementation running. It is available here:
https://github.com/MainRo/dooble

it is also published on pypi. there is a map example in "examples/map.txt"

Do not focus on the visual aspects yet. I am confident that we can easily generate diagrams this way. I think I also found a way to describe higher order observable in an easy way. The tool is based on matplotlib, which allows to generate better marble diagrams than what could be done with mermaid diagrams (in my opinion)

generate a png with:

```console
dooble --input example/map.txt --output /tmp/map.png
```
what are the opinions on that ?

**Comment by jcafhe** [comment]
This is great! Now I'm curious to see how a higher order observable would look like.

A few comments:
- in your example, you should append an 's' to *example* in path  *examples/map.txt*:
`dooble --input examples/map.txt --output /tmp/map.png`
- have you considered to make an [entry point](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) instead of a shell script. In fact, in windows I didn't manage to make it work by calling `dooble` or `python dooble` in cli. However, it's a bit more tedious to set up.

**Comment by MainRo** [comment]
I changed the script with an entry point. Tell me if installation works better on windows.
I also added a support for higher order observables. I use the '+' character as an anchor point between the parent and the child: A parent emits a '+' item to indicate that it emits an observable. A child starts with a '+' to indicate that it is a continuation of the parent. The parent and the child must have the anchor at the same position to be associated.
I added an example with the window operator which is:

```
--a-b-c---d-e-f-->
[     window     ]
--+-------+------>
          +d-e-f-|
  +a-b-c-|
```
We do not draw the vertical links on the text because this is tedious and would break the ebnf based grammar, but they are generated on the diagram. Keeping in mind that this is for documentation with simple diagrams, the text representation seems still readable to me.

**Comment by jcafhe** [comment]
> I changed the script with an entry point. Tell me if installation works better on windows.

Yes, it's working perfectly, thank you :+1: .
I played with window example and this is fine. Great work!

**Comment by MainRo** [comment]
Now that the content of the readme is - almost - completely in the documentation, I will strip it. I have two questions on that:

- I would like to change the format from md to rst so that it can be displayed on pypi.
- Should I reference the doc with relative paths to github, absolute paths to github or a placeholder where the doc will be published ? For now I would use absolute paths to github, and later reference the published doc.

**Comment by MainRo** [comment]
I still have some paragraphs to complete, but the overall documentation is in good shape. @dbrattli do you know if there is a way to automatically publish it somewhere on reactivex.io ? With travis we can encrypt credentials so that the CI automatically update the doc and nobody needs access to the credentials. I made something like this on a private gitlab-ci that could be relevant here:

- All commits on master trigger a new doc build being published on site-url/master.
- All tags creation trigger a new doc build being published on site-url/[tag].
- site-url/lastest is linked to the most recent tag url (site-url/latest -> site-url/[tag]).

I can work on the travis part if needed, provided that there is a way to publish via tooling.

**Comment by erikkemperman** [comment]
Does anyone know why sphinx doesn't crosslink properly? For example:
https://rxpy.readthedocs.io/en/latest/reference_observable_factory.html

These methods have return type `Observable`, and I would expect to be able to click on that to go the Observable class.

**Comment by erikkemperman** [comment]
About those failing crosslinks -- I just quickly tried what happened if I use the bundled `sphinx-apidoc` script to generate rst files, and it turns out that the crosslinks then just work...

Please note, I'm not proposing to do this necessarily, because it will just create a "dry" package/subpackage index at the upper levels, not the nicely decorated "topical" structure there is now under `Reference`.

Still, perhaps it might help in tracking down why the crosslinks don't work currently? To me it seems like kind of a big deal to get those working!

https://github.com/erikkemperman/RxPY/commit/9c21a24ae066fc7922f5f5ef76fd8031c53459b0

**Comment by MainRo** [comment]
strange. sphinx-apidoc seems to manually create rst files. So we should have the same results than with sphinx-build.

There are old references to this issue here:
https://github.com/sphinx-doc/sphinx/issues/1059
https://github.com/agronholm/sphinx-autodoc-typehints/issues/15

So it's supposed to work here. I tried adding the parameters set by sphxin-apidoc in the rst, and setting the napoleon "use_param" option without success.

**Comment by erikkemperman** [comment]
Hm, never noticed this before: if there are docstrings for both class and `__init__` then sphinx only uses the first. So for example, `AsyncSubject` has both,

https://github.com/ReactiveX/RxPY/blob/e5fb1dcb64757057095f6770fa1fcf3bb71daec5/rx/subjects/asyncsubject.py#L13
https://github.com/ReactiveX/RxPY/blob/e5fb1dcb64757057095f6770fa1fcf3bb71daec5/rx/subjects/asyncsubject.py#L18

But the generated docs only have the first section:
https://rxpy.readthedocs.io/en/latest/reference_subject.html#rx.subjects.AsyncSubject

So the init function is not actually documented! This behaviour can change this with a single sphinx setting, but I just wanted to check if this might be deliberate (i.e. that we were only supposed to put docstrings in either class or `__init__()`, not both).

**Comment by MainRo** [comment]
Wow nice catch! I think that documenting in both class and constructor makes sense: The class documentation contains information on the class itself, while __init__ is specifically for the constructor.

**Comment by MainRo** [comment]
closing this issue now that v3 is released. We will iterate on the doc with dedicated issues and PR.
