### ISSUE TITLE
RxPY 3.0: Tests update

### ISSUE THREAD

**Issue by jcafhe** [ReactiveX/RxPY#282]
Following the MainRo's idea, this issue can be used to track tests update to the new API (rx & rx.operators namespaces) as well as the new pipe mechanism.

I've made a new repository [RxPY3.0-tests-tracking](http://github.com/jcafhe/RxPY3.0-tests-tracking) to track this in a table (much better than my paper & pencil). For convenience, I also copy/paste this table in the post below and occasionally will keep it up to date.

**Comment by dbrattli** [comment]
There are still a few tests failing, but they are all related to the same issue. I'm currently looking into it.

**Comment by jcafhe** [comment]
Great job !
