### ISSUE TITLE
Contract of ScheduledAction

### ISSUE THREAD

**Issue by erikkemperman** [ReactiveX/RxPY#287]
I was looking at the code in `concurrency` and it's not really clear to me what the contract of a `ScheduledAction` is: should my implementations return a disposable or an updated state?

The code in `SchedulerBase` seems to be expecting two distinct kinds of action arguments. The class-level `invoke_action` method handles separately the case where the action return value is a disposable and it ignores any other return types.
https://github.com/ReactiveX/RxPY/blob/master/rx/concurrency/schedulerbase.py#L14

But the nested `invoke_action` function within the `schedule_periodic` method uses whatever the return value is for the state in the next period, even if it is disposable. And if the return value is disposable, it is ignored (rather than, say, composited with the result of the recursive scheduling).
https://github.com/ReactiveX/RxPY/blob/master/rx/concurrency/schedulerbase.py#L39

**Comment by dbrattli** [comment]
Yes, you are right. There are two different scheduled actions, and the one for scheduling periodic work needs to return the state (https://github.com/dotnet/reactive/blob/b4ab7a3d5ef05c5f5f1f7f298f3d3ea54622ba3f/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs#L112). We will need to make a new type called `ScheduledPeriodicAction` or similar. The existing `ScheduledAction` should be modified to return a `Disposable`. Thanks!

**Comment by erikkemperman** [comment]
That makes sense, thanks a lot for the quick response!

Actually, I think I might have some more questions / suggestions... Context is that I am considering an attempt to contribute a ProcessPoolScheduler. But I am not sure what the best mode of operation here would be, when I run into things I don't quite understand.

Is it all right if I just gather some questions together and put them in an issue here? For the most part this would probably not be interesting for anyone else though... Alternatively, I could just go ahead with how I believe things might work and submit a PR, and then take it from there?

**Comment by dbrattli** [comment]
Please open new issues for making features, questions or bugs 👍

**Comment by erikkemperman** [comment]
Well that was fast, thanks!
