### ISSUE TITLE
README.md: RxPy v3 isn't available

### ISSUE THREAD

**Issue by dima-spire** [ReactiveX/RxPY#290]
README.md says:
> RxPY v3.x runs on Python 3. To install RxPY:
> ```
> pip3 install rx
> ```
but when doing that, I only get RxPY v1.6.1, not v3.x.

**Comment by dbrattli** [comment]
Now released as https://pypi.org/project/Rx/3.0.0a0/ so please comment if you find any problems.

**Comment by dbrattli** [comment]
Note that the README has not been properly updated for v3 yet. I would expect 3.5 to be the minimum version, but haven't checked. I'll add it to the `setup.py` as minimum requirement (type hints) and then we bug fix it from there if it turns out not to be true.

**Comment by erikkemperman** [comment]
Thanks, I was just trying to make myself familiar with the `concurrency` modules, and noticed some little things that I think can be simplified for v3 if we assume reasonably recent Python.

**Comment by erikkemperman** [comment]
I think it should maybe even be 3.6, or else there type hints on variables aren't supported...

**Comment by dbrattli** [comment]
Fixed in https://github.com/ReactiveX/RxPY/commit/d7da711cdc62b3bafcf36eccd9c02445786fe423

**Comment by dima-spire** [comment]
Hi guys, kudos for releasing! But this issue is not about versions, it's about installation steps in README.md. So far it's not working, so this issue is still open IMO.

**Comment by dbrattli** [comment]
`pip3 install --pre rx`
