### ISSUE TITLE
Artifacts exposed from `core/__init__.py`

### ISSUE THREAD

**Issue by erikkemperman** [ReactiveX/RxPY#293]
Sorry if this is a silly question, but I am slightly confused as to what artifacts are being exposed from `core/__init__.py`. In some cases these are typings (such as Disposable, Scheduler, Observer) and in other cases these are base implementations (e.g. Observable) which  extend the typings.

Would it be better to consistently expose base implementations here, which are presumably more directly relevant for users, and keep the typings only in the package of the same name, for (mostly) internal use?

**Comment by dbrattli** [comment]
Yes, agree. It's a bit messy right now. I'll fix this.

**Comment by dbrattli** [comment]
Added first iteration of fixes. Core still provides ObservableBase as Observable, but we might wan't to reconsider that. What do you think? Other suggestions?

**Comment by erikkemperman** [comment]
Thanks! I guess I would want to rename `ObservableBase` -> `Observable`. If you agree, I can take a stab at that?

**Comment by dbrattli** [comment]
No, wait. I think we should keep `ObservableBase` for now since it's (or should be) the base for `ConnectableObservable`, `GroupedObservable`, `BlockingObservable` and should be for `Observable`, but there's no difference right now. However there's some magic methods in `ObservableBase` that should only be in `Observable`.

**Comment by erikkemperman** [comment]
Not sure I follow completely... I'm going to see if I can figure it out if I look at those classes more closely.

Meanwhile I've been going over core.observer and came up with the following:
https://github.com/erikkemperman/RxPY/commit/53ad49e34b855e2e5c8215e23b587522866eeb7c

But I hadn't read your comment yet -- maybe this commit is not helpful after all?

**Comment by erikkemperman** [comment]
If I understand your comment correctly, you wanted to have those dunderscores / operator overloading in the main exported `Observer` class, but not in the superclass of `ConnectableObservable` and `GroupedObservable` and `BlockingObserable`... Is that correct?

If so, I guess splitting the class would work -- how about something like this?
https://github.com/erikkemperman/RxPY/commit/cede62c2be5ac5fc8e290794953bb47e1daef002

**Comment by jcafhe** [comment]
I've come to the same [conclusion](https://github.com/jcafhe/RxPY3.0-migration-tracking) by listing the methods.

**Comment by dbrattli** [comment]
This is very interresting. But I just arrived at the cabin, so I need to review things tomorrow morning ...

**Comment by dbrattli** [comment]
Btw. AutoDetachObserver must inherit from `typing.Observer` since it will bloat the traceback if an error happens in the  Rx pipeline. Thus we don't want to refactor it to use a base class. Better with code duplication in this particular case.

Try the following example:

```py
import time
import rx
from rx import operators as ops

source = rx.range(1, 10)

def error(x):
    print(x)
    raise Exception("Boom!")

if __name__ == "__main__":
    source.pipe(
        ops.map(lambda x: x * 10),
        ops.filter(lambda x: x < 50)
    ).subscribe_(on_next=error, on_error=lambda x: print(x))

    time.sleep(1)
```

**Comment by jcafhe** [comment]
> I've kept `__await__` in the base class (one of the unit tests does `await` on an instance of `AnonymousObservable`. Does that make sense, or should I move it to `Observer` and somehow adapt the test?

In fact I don't know, it was a simple guess from the post of @dbrattli. I think we should wait for his answer, only him knows the master plan!

>     * I've not removed the `first`, `last` etc methods from `BlockingObservable`. Should I?

This is a item listed in the remaining work #285 but I think you should not bother with that for the moment, and remove them later.

**Comment by erikkemperman** [comment]
All right, thanks for detailed feedback! I will try to consolidate things in a PR today!

Personally I dislike the dangling underscore, how about `subscribe_cb`?

**Comment by dbrattli** [comment]
Yes, I'm not happy with it either. What if we change things around and have `subscribe()` only take the callbacks (observer method)? IMO, most of us only use the callbacks.  It feels more Pythonic than the observer. It's also easy to subscribe an observer this way `subscribe(obv.on_next, obv.on_error, obv.on_completed)`. We could also provide a `subscribe_observer()` helper for those who need it.

**Comment by jcafhe** [comment]
> Yes, I'm not happy with it either. What if we change things around and have `subscribe()` only take the callbacks (observer methods)? IMO, most of us only use the callbacks. 

I agree. From a client point of view, I would never use `subscribe(observer)` and always prefer `subscribe_(**callbacks)`. This purely subjective but I like to think that when using `subscribe`, I'm leaving the Rx world to do some side-effect stuffs. With `subscribe(observer)`, it would force me to subclass Observer and lose the clear demarcation line between these two worlds.

**Comment by erikkemperman** [comment]
Or `subscribe` could be made polymorphic? There are decorators to make that relatively painless. I could also imagine a kind of intermediate between minimal callbacks and full observer, using e.g. `NamedTuple`.

**Comment by dbrattli** [comment]
Subscribe was polymorphic in previous releases, so we could go back. But I'm not happy with functions/methods doing trying to do more than one thing at the same time (dispatch). Subscribe with observer is really only used from within the operators themselves, and most of them are not needed and would probably disappear if we went for callbacks since none of the operators use observers.

**Comment by erikkemperman** [comment]
Fair enough! Another question, you recently refactored the disposable and the 'static' creator functions are now in the top of that package. Maybe it's just me, but it looks slightly weird to do

```python
from rx import disposable
from rx.disposable import ...  # Sometimes we need a specific class as well

disposable.empty()
```

So I was just curious, what was the problem with `Disposable.empty()`, which looks more natural to me and keeps the imports tidier?

**Comment by dbrattli** [comment]
The problem before was that `Disposable` was a static helper class that was only used to hold the methods and we are removing the static helper classes and replacing them with plain functions. Note that we are in the middle of a major refactoring, so not everything have found it's final form yet.

```py
from rx.disposable import emtpy, SingleAssignmentDisposable

empty()
SingleAssignmentDisposable()
```

```py
from rx import disposable

disposable.emtpy()
disposable.SingleAssignmentDisposable()
```

**Comment by erikkemperman** [comment]
Right, thanks. I was a bit stuck yesterday with my attempt at refactoring core.observable and core.observer... And we have guests this weekend so I hope no-one is waiting for it. I’d like to try again though, this is a great way to gain insights in how the various bits come together!

**Comment by MainRo** [comment]
Maybe late, but anyway: I also agree with supporting only callbacks in subscribe. I do not think I used it with Observer objects, except when using subjects. In these cases, using subscribe_observer seems fine to me.

I am also for replacing the BlockingObservable with a run function (btw this is already done now :). I must admit I never needed it anyway. The pattern is use when working with blocking code with RxPY is with the root Observables being cold, and all operators being synchronous. So anyway the subscribe call is "blocking" in these situations.

**Comment by dbrattli** [comment]
FYI: Gave up on rewriting `subscribe()` to take callbacks as all the operators needed to be rewritten. Decided to go back to polymorphic `subscribe()` with scheduler as mandatory named parameter to make things simpler.
