### ISSUE TITLE
for the README: Reactive Python video course

### ISSUE THREAD

**Issue by rudolfolah** [ReactiveX/RxPY#301]
Hi, back in Oct 2018, a video course I worked on for Packt was published and used RxPy extensively: https://www.packtpub.com/application-development/reactive-programming-python-video

The code repository is here: https://github.com/PacktPublishing/Reactive-Programming-in-Python

It would be nice to link to both the video and code repo; but it would be nice if just the code repo is linked to as there are some decent examples that I worked on. For example, [being able to use multiple schedulers in one RxPy program](https://github.com/PacktPublishing/Reactive-Programming-in-Python/blob/master/Section%206/main3.py#L21-L37), I was using QtScheduler and AsyncIOScheduler with Tornado's IOLoop scheduler running in separate threads.

**Comment by dbrattli** [comment]
The README has been bloated for many years, and will be reduced to an absolute minimum. There is an ongoing effort to create documentation pages instead and this video should be linked from a page in the documentation instead. @MainRo might have an idea of where we should link to learning material?

**Comment by MainRo** [comment]
I did not add such a section now in the doc because I was not sure whether it should stay in the README or moved to the documentation. For sure we can add a dedicated section in the documentation with the existing material, maybe splitting free and paid content.
