### ISSUE TITLE
Observable.from_array ?

### ISSUE THREAD

**Issue by caente** [ReactiveX/RxPY#31]
Hello I had to revisit a project that is using RxPY, it was on version 0.10,  so I upgraded to version 1.0.0.

Now it seems like Observable.from_array no longer exists, is there any option to create an observable from an array?

**Comment by dbrattli** [comment]
The method was ported from JavaScript, but Python does not have any arrays, so it's been renamed to Observable.from_iterable() with aliases from_() and from_list(). The idea is that the .from_() method eventually will handle (almost) anything.

**Comment by caente** [comment]
thanks man! it worked
