### ISSUE TITLE
Subscriber assertion error

### ISSUE THREAD

**Issue by Sammyalhashe** [ReactiveX/RxPY#310]
Okay, I know I'm doing something slightly wrong here. 

So basically, I have two classes communicating, a `data` class and a `plotter` class. What I'm doing right now is creating a `Subject` in `data` class, then instantiating an instance of the `data` class in my `plotter` class.  The `data` class calls the `on_next()` function.

Basically, in my `data` class, I have this:
```
def activateStream(self):
        if not self.stream:
            self.stream = Subject()

def getStream(self):
        if not self.stream:
            print("Activate the Data Stream first")
            return None
        print(type(self.stream))
        return self.stream
```

In my `plotter` class I have this:
```
def getObserver(self):
        if not self.observer:
            self.data_rpc.activateStream()
            self.observer = self.data_rpc.getStream()

    def plotData(self):
        if not self.observer:
            self.getObserver()
        self.data = np.array([])
        self.observer.subscribe(lambda x: self.addData(x))
        self.data_rpc.getData_test()

def addData(self, newData):
        self.data = np.append(self.data, newData[0])
        self.plot.plot(self.data)
```

When I was running this I was getting `assert isinstance(observer, abc.Observer)`.

This was weird because I ran a test in my terminal:
```
>>> from rx.subjects import Subject
>>> s = Subject()
>>> d = s.subscribe(lambda x: print(x))
>>> s.on_next(34)
34
>>> print(type(s))
<class 'rx.subjects.subject.Subject'>
```
Everything worked fine. I went into the source code [here](https://github.com/ReactiveX/RxPY/blob/master/rx/core/observable/observable.py) and found I was calling the `subscribe` method to get the `AssertionError`. But I also noticed there is a `subscribe_` method. I tried it out, and it worked.

I am doing something slightly wrong, but I don't know what. How come I was successful with the `subscribe_` method but not the `subscribe` method in my code. And why did the `subscribe` method work in my simple test?

**Comment by jcafhe** [comment]
Hi, 
Could you give some details about the version of rx you're running ?
 
In RxPY3, the behaviour of `subscribe` has been changed multiple times. It is now polymorphic i.e. it accepts an observer `subscribe(observer)` as well as one or multiple callbacks `subscribe(on_next=...) since commit c5ddccad558198b67cdcbd18fd5a929079cf06be.

**Comment by Sammyalhashe** [comment]
```
Name: Rx
Version: 3.0.0a2
Summary: Reactive Extensions (Rx) for Python
Home-page: http://reactivex.io
Author: Dag Brattli
Author-email: dag@brattli.net
License: Apache License
```

**Comment by MainRo** [comment]
You should try against master from the github repository. I suspect that your example works here.
Note that RxPY v3 is still in development. The current stable release is 1.6.1.

**Comment by dbrattli** [comment]
Yes, should work with latest beta as the subscribe accepts both observer and callbacks. Closing, but please reopen if you experience this again.
