### ISSUE TITLE
Solution for limiting network requests?

### ISSUE THREAD

**Issue by devtud** [ReactiveX/RxPY#315]
This is not really an issue with RxPY, but rather a problem I'm struggling with.

So,

Shortly, I need to make continuous checks for a set of data: let's say my set of data is `[1, 2, 3..., 20]` and I have to call a remote API to make a check for each number (`check(i) for i in data`).

The good part is that the remote API permits checking max 10 elements at once, but I can send max 1 request per 2 seconds. So my requests would be:
```
# 1 - check([1..10])
sleep 2 secs
# 2 - check([11..20])
sleep 2 secs
# 3 - check([1..10])
sleep 2 secs
# 4 - check([1..20])
sleep 2 secs
... and so on
```

My approach was to create an infinite generator which loops through my data like:

```python
def infgen():
    i = 1
    while True:
        yield i
        i += 1
        if i > 20:
            i = 1
```

..and use rx to create a pipeline:

```python

buffered_elems = rx.from_(infgen).pipe(  # consume data from generator 
    ops.buffer_with_count(10)  # make sets of 10 elements to be sent in check request
)

done_elems = rx.zip(  # !!!
    buffered_elems,
    rx.interval(datetime.timedelta(seconds=2)),  # release only 1 buffer of elems per 2 seconds
).pipe(
    ops.map(lambda x: x[0]),  # take back only data elements
    ops.map(check),  # call check() method which makes the API request
    ops.flat_map(rx.from_list),  # unpack the api response from buffer
    ops.filter(lambda api_response: api_response['is_done']),  # filter done elems
)

# then subscribe to ``done_elems`` and process them in some way
```

The problem is that `buffered_elems` produces data very fast, but the `zip` (# !!!) releases each 10 elems buffer once per 2 seconds, which leads to increasing the RAM until it gets full. I could use another 
`zip(infgen, interval)` and find an appropriate interval for it, but the rate of generating data would be constant, which is not what I want.

I would like to know if there is a way to inform `buffered_elems` to generate data only when is needed by `rx.zip` (# !!!).

Or, if there is a better approach I would be very happy if you share it.

**Comment by devtud** [comment]
I have another side question: if I have

```
rx.zip(
    rx.from_(generator),
    rx.interval(N_SECONDS)
)
```

I expect that each N_SECONDS seconds 1 item will be consumed from generator. Instead, I noticed that the generator is all consumed in an instant. Is there a way to achieve the  behavior I expect?

**Comment by jcafhe** [comment]
Hi,
Where do your data come from? Is it something that you generate in a deterministic way or is it something you get by polling some kind of buffer?

> I expect that each N_SECONDS seconds 1 item will be consumed from generator. Instead, I noticed that the generator is all consumed in an instant. Is there a way to achieve the behavior I expect?

Indeed, `zip` does not block the upstream observables. It will accumulate values in a queue if an observable produces items faster than the other observables.  Instead, you should create inner observable in high order operators like `flat_map`:
```python
import rx
from rx import operators as ops

def infgen():
    i = 1
    while True:
        print('yield {}'.format(i))
        yield i
        i += 1
        if i > 20:
            i = 1

buffer = rx.from_iterable(infgen())

buffered_elements = rx.interval(0.5).pipe(
    ops.flat_map(lambda _: buffer.pipe(ops.take(10))),
    ops.buffer_with_count(20),
    ops.take(3),
    )

buffered_elements.subscribe(lambda i: print('buffered_elms {}'.format(i)))
```

**Comment by devtud** [comment]
Thank you @jcafhe  for clearing out the `zip`'s behavior. I concluded it's not useful in this case for me.

I've tried to adapt your solution but still doesn't work. It hangs after some time and I'm not sure why.

Just to be sure I specify clear enough what I want to achieve, I'll write the equivalent without using `rx`. The idea is pretty simple, but I don't know how to "transpile" it in rx.

```
import requests
import time


def check_items(item_list):
    # Always sleep 2 secs before hitting the API just to be sure we respect
    # its rate limit
    time.sleep(2)
    responses_list = requests.post('API_URL', data=item_list).json()
    # responses_list looks like: [{item1: status_item_1}, {item2: status_item_2}, ...]
    return responses_list


def continuously_check_items(infinite_items_generator, subscribers):
    buffer_len = 10
    buffer = []
    for item in infinite_items_generator:
        buffer.append(item)  # accumulate buffer_len elems
        if len(buffer) == buffer_len:
            # Now we can hit the check function aka API
            responses_list = check_items(buffer)
            responses_with_status_ok = filter(lambda response: response['is_done'], responses_list)
            for subscriber in subscribers:
                # Notify each subscriber about the items with is_done status
                for response in responses_with_status_ok:
                    subscriber.notify(response)
        else:
            # continue until we fill the buffer
            pass
```

**Comment by jcafhe** [comment]
I don't think you can easily mitigate the emission rate of an observable based on the rate you want for a downstream observable. That would require some kind of back pressure or feedback loop that rx does not provided AFAIK.

Alternatively, you could generate values at a specified rate by using `rx.generate_with_relative_time` operator. However, for complex generation of values, it could be not appropriate. In fact, generate chunks of 10 values from your generator may be tricky.

Otherwise, a more complex solution is to create your own observable with `rx.create` operator.  You grab 10 elements at a time from your generator by using the lazy slice of `itertools.islice` on your generator and transform the result to a list/tuple. Then you schedule the emission of this list in a recusive way (see example below). Basically, each action will grab 10 values, push these values as a tuple to the observer, and shedule the next action to be executed 2s later.

```python
import rx
import rx.operators as ops
from itertools import islice
from rx import concurrency
from rx.disposable import SerialDisposable


def infgen():
    i = 1
    while True:
        print('generator yields {}'.format(i))
        yield i
        i += 1
        if i > 20:
            i = 1


new_thread_scheduler = concurrency.NewThreadScheduler()


def subscribe(observer, scheduler_):
    # use the scheduler_ provided by the downstream subscribe() method if
    # specified, else use a custom scheduler
    _scheduler = scheduler_ or new_thread_scheduler

    # instanciate the generator at subscription time. Thus, each subscriber
    # will have its own generator.
    generator = infgen()
    duetime = 2.0
    disp = SerialDisposable()

    def action(scheduler, state):
        # grab 10 values from the generator
        buffered_elements = tuple(islice(generator, 10))

        # push these values to the observer
        observer.on_next(buffered_elements)

        # schedule the next action from the current action.
        # if the current observable is disposed, the next action will not be
        # executed, stopping the emission of values.
        disp.set_disposable(_scheduler.schedule_relative(duetime, action))

    # schedule the first action ASAP
    disp.set_disposable(_scheduler.schedule(action))
    return disp


res = rx.create(subscribe).pipe(
    ops.take(3),  # stop the script after 3 buffered elements
    ops.do_action(print),  # log buffered elements
    )
res.run()
```
