### ISSUE TITLE
python3.6 and python3.7 support

### ISSUE THREAD

**Issue by achukka** [ReactiveX/RxPY#323]
Hi reactive developers,

I was wondering if the [v1.5.9](https://github.com/ReactiveX/RxPY/releases/tag/v1.5.9) of rxpy supports python3.6 and/or python3.7.

Note: Sorry I couldn't find any other place to ask this question.

Thanks,
Aditya.

**Comment by jcafhe** [comment]
Hi,

I can't remember for v1.5.9, but v1.6.1 (last stable version available on PyPi) supports python 3.7.

Also, you can test v3 (work in progress), either by `pip install --pre rx` or preferably by cloning github repository and checkout the master branch. Note that v3 brings important changes, as described in [migration.md](https://github.com/ReactiveX/RxPY/blob/master/doc/migration.rst) and [documentation](https://github.com/ReactiveX/RxPY/tree/master/doc).

**Comment by achukka** [comment]
@jcafhe Thanks I'll try v1.6.1 for now :)
