### ISSUE TITLE
Infinite Busy Wait

### ISSUE THREAD

**Issue by Alexhuszagh** [ReactiveX/RxPY#325]
# Reproducing

```python
import asyncio
import rx

async def x(y):
    return await y
    
y = rx.Observable.from_([])
asyncio.get_event_loop().run_until_complete(y)
```

# Tested Versions

Tested on RxPy 1.6, but also confirmed the issue is present on master.

# Potential Fixes

[The following implementation](https://github.com/ReactiveX/RxPY/blob/b333440871ad5e74dbdf5365fe99643f22f92c25/rx/core/operators/tofuture.py#L33) shows the issue: if no value has been produced, awaiting the observable will block forever, since no result or exception is set.

In my (biased) opinion, a few options are possible, since I feel that silently blocking forever based on an opaque type is an unsatisfactory solution:

1. Silently set the value to `None`. This would have the added advantage that the original statement would work, but would also be difficult to distinguish between an function that does not return a value, and an empty iterable, which are two completely different types. It also has 1 more benefit, which is similar to future-like objects (see below).
2. Raise `StopAsyncIteration`. This would be explicit, but would mean the above statement would fail, but would clearly signal intent.
3. Raise a custom error. Also explicit, and would also clearly signal intent. It could potentially derive from `StopAsyncIteration`.

# Footnotes

**Future-Like Objects**

[PEP 492](https://www.python.org/dev/peps/pep-0492/#asyncio) defines future-like objects which have `__await__ = __iter__` to simplify implementations. These cannot return a value, and I believe are only used for the side-effects (that is, to ensure the logic in `__iter__` is executed without having to modify existing code).

```python
import asyncio

class A:
    def __iter__(self):
        return self
    def __next__(self):
        raise StopIteration
    __await__ = __iter__

asyncio.get_event_loop().run_until_complete(A())
```

**Comment by MainRo** [comment]
I'd be in favor of setting the result to None in _to_future when the iterable is empty.

**Comment by MainRo** [comment]
Finally the implementation completes the future with the exception rx.internal.exceptions.SequenceContainsNoElementsError if the observable is empty.

**Comment by Alexhuszagh** [comment]
Wonderful, thank you.
