### ISSUE TITLE
Cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by kunalpal** [ReactiveX/RxPY#326]
I have a function making recursive calls using the same scheduler. However, after the first go I encounter the error that "cannot schedule new futures afterinterpreter shutdown".

```python
    def fetch_all(self, queue=None):
        print("Fetch things")
        if queue is None:
            queue = self.uids
        Observable.from_(queue) \
            .flat_map(lambda uid: Observable.just(uid, self.scheduler)) \
            .map(lambda uid: self.fetch(uid)) \ 
            .filter(lambda uid: uid is not None) \
            .to_list() \
            .subscribe(on_next=lambda uids: self.fetch_all(queue=uids), on_error=print)
```
I am using the built-in rxpy `ThreadPoolScheduler` for this. `fetch` makes a simple network request and returns the next uid. I don't have any clue about how to fix the problem and will appreciate any help.

**Comment by jcafhe** [comment]
Hi,

Are you sure you are maintaining your object alive?

It is a common mistake when working with Rx to declare observables that push items from threads which are not the main thread. Thus, if you don't block the main thread in some way (sleep, loop, `run` method, ...), the starting script exits before any observables have a chance to emit items.

**Comment by kunalpal** [comment]
Thanks @jcafhe. If I keep the main thread alive, that solves the problem.
Closing this issue.
