### ISSUE TITLE
RxPY Collaborator Workflow

### ISSUE THREAD

**Issue by dbrattli** [ReactiveX/RxPY#328]
Adding a workflow to RxPY for collaborators to make things more community driven. Every change to the master branch must be in form of a PR and approved by at least 2 collaborators. When 2 or more have approved the PR, you are free to merge (with or without my approval). I'm currently NJNL (new job, new language) and do not want to slow down the speed of RxPY development. What do you think? Any other things we should do?

PS: I've also added @erikkemperman as a collaborator and hope he will accept the invitation.

**Comment by erikkemperman** [comment]
I accepted the invitation, thanks! I have to say, though, I’m still pretty new around here, so I’ll probably be slightly timid for the time being. But, if my free time allows, I’ll be happy to try and support the effort.

Congrats on the new job! What’s the new language?

**Comment by MainRo** [comment]
Let's try this. I must admit that I do not feel confident to vote for many PR that occured the last months. But that's the point of being several people and I hope this will help.

**Comment by dbrattli** [comment]
Thanks, we need someone who knows the inner details of the schedulers. The idea is that we have enough collaborators so we can share the work between us, so if some are stuck with other work then hopefully someone else have time to look through or create PRs.

Exciting stuff and currently learning Scala, but as one of the few that knows .NET there will be some C#. Hope to turn that into F# instead since I've been using F# for the last year. Also a lot of Python, Java, and JavaScript. I great mix which I really like. Look at https://cognite.com/careers/ if Oslo is an option :wink:

**Comment by jcafhe** [comment]
Like you, I don't feel comfortable with a lot of topics. However, it is a good opportunity to know more about the inner mechanisms of RxPY. 

By the way, good luck with your new job :tada:

**Comment by dbrattli** [comment]
I think this has been working really well so far so thanks for all the great work and effort. Really happy to have you all onboard!
