### ISSUE TITLE
Doc build fails on ReadTheDocs

### ISSUE THREAD

**Issue by dbrattli** [ReactiveX/RxPY#339]
Not sure why RTD uses the latex builder, i.e `make latex` will trigger the error.

```
Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/writers/latex.py", line 2569, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: marble
```

**Comment by erikkemperman** [comment]
That's probably because they would like to generate PDFs for download:
https://docs.readthedocs.io/en/stable/builds.html#understanding-what-s-going-on

Currently, probably due to this error, it is empty:
https://buildmedia.readthedocs.org/media/pdf/rxpy/stable/rxpy.pdf

I think the sphinxcontrib-dooble needs to add latex support, not sure how difficult that is.

**Comment by MainRo** [comment]
arg... I skipped the pdf rendering in the sphinx add-on. I thought it was not needed.

**Comment by erikkemperman** [comment]
For what it’s worth I made a PR to add latex, that should be enough I think (Sphinx has a `latexpdf` target in the makefile and I’ve tested that works with the PR).
https://github.com/MainRo/sphinxcontrib-dooble/pull/1

**Comment by MainRo** [comment]
I just published a new release of sphinxcontrib-dooble, can anybody re-trigger the doc generation ?

**Comment by erikkemperman** [comment]
Looks like it’s finding a cached version of the dooble sphinx plugin at 0.1.0, maybe we need to be explicit in asking for 1.0.0 in docs/requirements.txt?

**Comment by erikkemperman** [comment]
Hmm the doc build failed again, same error as before. I think it might help to specify minimum version — unfortunately I won’t be near a computer today...

**Comment by MainRo** [comment]
The doc build now works, and the PDF and epub can be downloaded !
