### ISSUE TITLE
How can i rewrite the subscriber in RXJS with rxpy

### ISSUE THREAD

**Issue by masonCaminer** [ReactiveX/RxPY#346]
I don't know how to change the Subscriber of RXJS to the form of Python, which is not effective.
Typescript USES the GRPC stream form and plugs in the RXJS Subscriber. Python doesn't know how to write it.

RXJS code
`import * as grpc from 'grpc';
import { Observable, Subscriber } from 'rxjs';

export function subscribeToWorkspace(
  input: WorkspaceSubscriptionInput,
): Observable<EventPayload> {
  return new Observable<EventPayload>((observer: Subscriber<EventPayload>) => {
    log(`opening stream for subscription ${input.toString()}`);

    const stream: grpc.ClientReadableStream<EventPayload> =
      client.subscribeToWorkspace(input, metadata);

    stream.on('data', (eventPayload: EventPayload) => {
      if (observer.closed) {
        return;
      }
      observer.next(eventPayload);
    });

    stream.on('error', (err) => observer.error(err));
    stream.on('end', () => observer.complete());

    return () => {
      log(`closing stream for subscription ${input.toString()}`);
      stream.cancel();
    };
  });
}
Python code
`
from rx import of
def subscribe_to_workspace(cls, subsinput: WorkspaceSubscriptionInput) -> Observable:
        return of(cls.client.SubscribeToWorkspace(subsinput))
`
Rxpy does not work. What should Python do

**Comment by MainRo** [comment]
I am not familiar with gRPC.
btw the of operator will create an observable emitting only the value returned by  cls.client.SubscribeToWorkspace(subsinput) (it is a gRPC stream ?). I suppose that you need to implement a logic similar to the rxjs one (registering callbacks on the gRPC stream and calling on_next/on_completed/on_error on the observer)

**Comment by masonCaminer** [comment]
Thank you, MainRo
