### ISSUE TITLE
list assignment index out of range error in zip_array class extension method

### ISSUE THREAD

**Issue by trilokacharya** [ReactiveX/RxPY#35]
The class extension method zip_array's action() method has this code:

    for _ in queues:
        queues[n] = []

n is set to len(queues) earlier in the method, so this throws index out of range error.

**Comment by dbrattli** [comment]
Thanks for pointing this out. That code looks ugly.

**Comment by trilokacharya** [comment]
Thanks for jumping on it so quickly.  Any idea when this would get merged into master?

**Comment by dbrattli** [comment]
I don't have code that triggers the bug, so it's hard for me to know if really fixes the bug. If you could verify the fix, or post some minimal code that triggers the bug, then I can make a unit-test. When we know the fix is correct, then I can merge to master.

**Comment by 38elements** [comment]
Hi, @dbrattli 
Hi, @trilokacharya 
I tried this by using Python 2.7 and RxPY 1.1.
```
from __future__ import print_function
import rx

s = rx.Observable.range(0, 5)
rx.Observable.zip_array(
    s,
    s.skip(1),
    s.skip(2)
).subscribe(print)
```
   
result
```
  File "/usr/local/lib/python2.7/dist-packages/rx/linq/observable/ziparray.py", line 82, in action
    queues[n] = []
IndexError: list assignment index out of range
```

**Comment by dbrattli** [comment]
The code in `Observable.zip` and `Observable.zip_array`looks very similar. What is really the difference between `zip_array`and `zip(s1, s2, lambda: x, y: [x, y])` @mattpodwysocki ? I checked the JavaScript sources, and they still have both operators `Observable.zipArray`and `observableProto.zip` that are very similar. Would be nice if we could refactor this code, and implement `zip_array` (or really `zip_list` in python) just using `zip`.

**Comment by trilokacharya** [comment]
@dbrattli, my understanding from reading the docs at http://reactivex.io/documentation/operators/zip.html is that zip_array is supposed to take a variable number of observables and zip them all. 

This is not pretty, but I think it shows the intended behavior:
```
def flat_add(a,b):
        """ if a = valueA, b = valueB : returns [valueA, valueB]. 
            if a = [V1,V2..Vn], b = valueB : returns [V1,V2..Vn,valueB ]
        """
	if isinstance(a,list):
    	       a.append(b)
	       return a
	else:
    	       return [a,b]

s1 = rx.Observable.range(0, 5)
s2 = s1.skip(1)
s3 = s1.skip(2)

reduce(lambda a,b:a.zip(b,flat_add),[s1,s2,s3])

"""
result = 
[0, 1, 2]
[1, 2, 3]
[2, 3, 4]
""""
```

**Comment by dbrattli** [comment]
Yes, but you can do that already with `zip`:

```python
>>> import rx
>>> def res(*args):
...    return list(args)
...
>>> s1 = rx.Observable.range(0, 5)
>>> s2 = s1.skip(1)
>>> s3 = s1.skip(2)
>>> rx.Observable.zip(s1, s2, s3, res).subscribe(print)
[0, 1, 2]
[1, 2, 3]
[2, 3, 4]
<rx.autodetachobserver.AutoDetachObserver object at 0x1025c1320>
```

Isn't this the same?

**Comment by trilokacharya** [comment]
You're right. I should've read the description better instead of just looking at the diagram and thinking zip only works on 2 observables at a time.

**Comment by dbrattli** [comment]
I've now added the simplified Observable.zip_array to the develop branch.
