### ISSUE TITLE
Suggestion: syntactic sugar for pipe calls

### ISSUE THREAD

**Issue by erikkemperman** [ReactiveX/RxPY#352]
I had this idea a while ago, and I can't decide if this is a pretty nice and pythonic idea, or else if it might be too clever by half...

So I should probably just ask the community: what do you think if we add something like this to `Observable`?

```python
    def __or__(self, other):
        """Pythonic version of pipe.

        Example:
            >>> zs = xs | op          # Equivalent to zs = xs.pipe(op)
            >>> zs = xs | (op1, op2)  # Equivalent to zs = xs.pipe(op1, op2)

        Returns:
            self.pipe(*other) if other is iterable, otherwise self.pipe(other)
        """
        if isinstance(other, Iterable):
            return self.pipe(*other)
        return self.pipe(other)
```

**Comment by MainRo** [comment]
I consider such notation as a hack. This is how it is done in RxCpp. I come from system/driver development and I can't adhere to a notation that abuses the usage of the "bitwise or" operator. The | character is a pipe only in shells, in python the meaning is bitwise or.
So I prefer using an explicit pipe function, unless another dedicated operator appears one day (something like https://github.com/tc39/proposal-pipeline-operator)

**Comment by dbrattli** [comment]
I also think we should leave it for now and hope that there will be a proper pipe operator such as with F#. Lets fix the typing problems with pipe instead https://github.com/ReactiveX/RxPY/issues/355

**Comment by erikkemperman** [comment]
Fair enough, I guess it’s a bit too hackish :-) Closing the isssue.
