### ISSUE TITLE
qtscheduler not work. Maybe I find the reason and give myself code

### ISSUE THREAD

**Issue by woshimanong1990** [ReactiveX/RxPY#359]
I find the Rxpy can't run MainThread when some opreation has run in thread .One reason is that  previous operaton may run in thread . so the on_next method is called in that thread.So I change the code  and it works
`
   
    # -*- coding: utf-8 -*-
    from __future__ import absolute_import
    from __future__ import unicode_literals
    from __future__ import print_function
    import logging
    from datetime import datetime, timedelta
    from collections import namedtuple
    import uuid

    from rx.core import typing
    from rx.disposable import SingleAssignmentDisposable, CompositeDisposable, Disposable
    from PyQt5.QtCore import pyqtSignal, QObject, QTimer

    TimeParams = namedtuple('TimeParams', 'id msecs action periodic periodic_state sad scheduler state')
    logger = logging.getLogger()

    class CustomQtScheduler(QObject):
        action_signal = pyqtSignal(object)
        timer_dispose_signal = pyqtSignal(str)

        def __init__(self, parent=None):
            super(CustomQtScheduler, self).__init__(parent=parent)
            self.action_signal.connect(self.operate_action)
            self.timer_dispose_signal.connect(self.remove_timer)
            self._timers = dict()

        def remove_timer(self, timer_id):
            if timer_id in self._timers:
                self._timers[timer_id].stop()
                self._timers.pop(timer_id, None)

        def operate_action(self, timer_params):
            try:
                def interval():
                    if timer_params.periodic:
                        timer_params.periodic_state[0] = timer_params.action(timer_params.periodic_state[0])
                    else:
                        timer_params.sad.disposable = timer_params.action(timer_params.scheduler, timer_params.state)
                timer = QTimer()
                timer.setSingleShot(not timer_params.periodic)
                timer.timeout.connect(interval)
                timer.setInterval(timer_params.msecs)
                timer.start()
                time_id = timer_params.id
                self._timers[time_id] = timer
            except:
                logger.error("operate_action error", exc_info=True)

        def _qtimer_schedule(self, mtime, action, state, periodic=False):
            try:
                scheduler = self
                msecs = int(self.to_seconds(mtime) * 1000.0)

                sad = SingleAssignmentDisposable()

                periodic_state = [state]
                timer_id = uuid.uuid1().hex
                self.action_signal.emit(TimeParams(timer_id, msecs, action, periodic, periodic_state, sad, scheduler, state))

                def dispose():
                    self.timer_dispose_signal.emit(timer_id)
                return CompositeDisposable(sad, Disposable(dispose))
            except:
                logger.error("_qtimer_schedule", exc_info=True)

        def schedule(self, action: typing.ScheduledAction, state: typing.TState = None) -> typing.Disposable:
            """Schedules an action to be executed."""
            return self._qtimer_schedule(0, action, state)

        def schedule_relative(self, duetime: typing.RelativeTime, action: typing.ScheduledAction,
                            state: typing.TState = None) -> typing.Disposable:
            """Schedules an action to be executed after duetime.

            Args:
                duetime: Relative time after which to execute the action.
                action: Action to be executed.

            Returns:
                The disposable object used to cancel the scheduled action
                (best effort).
            """
            return self._qtimer_schedule(duetime, action, state)

        def schedule_absolute(self, duetime: typing.AbsoluteTime, action: typing.ScheduledAction,
                            state: typing.TState = None) -> typing.Disposable:
            """Schedules an action to be executed at duetime.

            Args:
                duetime: Absolute time after which to execute the action.
                action: Action to be executed.

            Returns:
                The disposable object used to cancel the scheduled action
                (best effort).
            """

            duetime = self.to_datetime(duetime)
            return self._qtimer_schedule(duetime, action, state)

        def schedule_periodic(self, period: typing.RelativeTime, action: typing.ScheduledPeriodicAction,
                            state: typing.TState = None):
            """Schedules a periodic piece of work to be executed in the Qt
            mainloop.

            Args:
                period: Period in milliseconds for running the work
                    periodically.
                action: Action to be executed.
                state: [Optional] Initial state passed to the action upon
                    the first iteration.

            Returns:
                The disposable object used to cancel the scheduled
                recurring action (best effort).
            """

            return self._qtimer_schedule(period, action, state, periodic=True)

        @classmethod
        def to_seconds(cls, timespan: typing.AbsoluteOrRelativeTime) -> float:
            """Converts time value to seconds"""

            if isinstance(timespan, datetime):
                timespan = timespan - datetime.utcfromtimestamp(0)
                timespan = timespan.total_seconds()
            elif isinstance(timespan, timedelta):
                timespan = timespan.total_seconds()

            return timespan

`
I find the thread switch is not useful.

**Comment by woshimanong1990** [comment]
find some bug

**Comment by erikkemperman** [comment]
I’m sorry, it’s probably a language problem but I don’t really understand this issue. If you have a proposal to change things, can you make a PR?
