### ISSUE TITLE
Bug in example for async V3

### ISSUE THREAD

**Issue by japrogramer** [ReactiveX/RxPY#364]
```
▶ python examples/asyncio/toasyncgenerator.py                                                      ∞
Traceback (most recent call last):
  File "examples/asyncio/toasyncgenerator.py", line 2, in <module>
    asyncio = rx.config['asyncio']
AttributeError: module 'rx' has no attribute 'config'
(Science)
Code/Forks/RxPY  master ✔                                                                          4d  ⍉
▶ python examples/asyncio/toasynciterator.py                                                      ∞
Traceback (most recent call last):
  File "examples/asyncio/toasynciterator.py", line 3, in <module>
    from rx.concurrency import AsyncIOScheduler
ImportError: cannot import name 'AsyncIOScheduler' from 'rx.concurrency' (/home/archangel/VENV/Science/lib/python3.7/site-packages/rx/concurrency/__init__.py)
(Science)
Code/Forks/RxPY  master ✔                                                                          4d  ⍉
▶ python examples/asyncio/await.py                                                                ∞
Traceback (most recent call last):
  File "examples/asyncio/await.py", line 5, in <module>
    stream = Observable.just("Hello, world!")
AttributeError: type object 'Observable' has no attribute 'just'
```

**Comment by MainRo** [comment]
examples have not been ported yet to rxpy 3

**Comment by ppGodel** [comment]
for the example of Concurrency i migrated to v3

`import multiprocessing
import random
import time
from threading import current_thread

from rx import Observable, of, range, interval
from rx import operators as op
from rx.concurrency import ThreadPoolScheduler


def intense_calculation(value):
    # sleep for a random short duration between 0.5 to 2.0 seconds to simulate a long-running calculation
    time.sleep(random.randint(5, 20) * .1)
    return value


# calculate number of CPU's, then create a ThreadPoolScheduler with that number of threads
optimal_thread_count = multiprocessing.cpu_count()
pool_scheduler = ThreadPoolScheduler(optimal_thread_count)

# Create Process 1
of("Alpha", "Beta", "Gamma", "Delta", "Epsilon").pipe(
    op.map(lambda s: intense_calculation(s)),
    op.subscribe_on(pool_scheduler)) \
    .subscribe(on_next=lambda s: print("PROCESS 1: {0} {1}".format(current_thread().name, s)),
               on_error=lambda e: print(e), on_completed=lambda: print("PROCESS 1 done!"))

# Create Process 2
range(1, 10).pipe(
    op.map(lambda s: intense_calculation(s)),
    op.subscribe_on(pool_scheduler)). \
    subscribe(on_next=lambda i: print("PROCESS 2: {0} {1}".format(current_thread().name, i)),
              on_error=lambda e: print(e), on_completed=lambda: print("PROCESS 2 done!"))

# Create Process 3, which is infinite
interval(1000).pipe(
    op.map(lambda i: i * 100),
    op.observe_on(pool_scheduler),
    op.map(lambda s: intense_calculation(s))). \
    subscribe(on_next=lambda i: print("PROCESS 3: {0} {1}".format(current_thread().name, i)),
              on_error=lambda e: print(e))

input("Press any key to exit\n")
`
