### ISSUE TITLE
RxPY v3 Release It!

### ISSUE THREAD

**Issue by dbrattli** [ReactiveX/RxPY#375]
The release of v3 is set to June 1, and I would really like to get it released. What are the remaining issues or blockers? 

I don't think everything should be perfect for the release. After the release we should continue to improve RxPY and target a release v3.1 etc as soon as we get feedback on the v3 release.

Lets get it out!

**Comment by erikkemperman** [comment]
I am (still / again) working through the schedulers and their tests, I’m finding some issues which in my opinion should be resolved before 3.0...

Hoping to submit some things soon, but would love your input on #370?

**Comment by MainRo** [comment]
There are some things I wanted to work on on the documentation and the examples, but nothing that would prevent a release. I will try to work on them before the release if I have some time the next weeks.

**Comment by dbrattli** [comment]
Released 3.0.0b1, https://pypi.org/project/Rx/3.0.0b1/

**Comment by dbrattli** [comment]
Beta 2 (3.0.0b2) is at https://pypi.org/project/Rx/3.0.0b2/

**Comment by jcafhe** [comment]
Based on @MainRo proposal to split `window` in 3 distinct operators to simplify type hints and avoid internal dispatching machinery, I suggest that we change few operators: 

[`buffer`](https://github.com/ReactiveX/RxPY/blob/d3ff1b72963fd08341807986d49480351015165e/rx/core/operators/buffer.py#L7) is basically `window` chained with `to_iterable`. So we can split it too with the same naming convention:
- `buffer(openings: Observable)`
- `buffer_when(closing_mapper: Callable[[], Observable])`
- `buffer_toggle(openings: Observable, closing_mapper: Callable[[Any], Observable])`

I believe [`sample`](https://github.com/ReactiveX/RxPY/blob/d3ff1b72963fd08341807986d49480351015165e/rx/core/operators/sample.py#L36) can be simplified too with only 1 argument that accepts an Observable or a time interval. However, a dispatching mechanism will remain but it should be quite simple:
 - `sample(sampler: Union[Observable, RelativeTime)])`

Same with [`catch`,](https://github.com/ReactiveX/RxPY/blob/d3ff1b72963fd08341807986d49480351015165e/rx/core/operators/catch.py#L38) i.e. 1 argument that accepts an Observable or a callable (handler): 
- `catch(handler: Union[Observable, Callable[Exception, Observable], Observable])]`

What do you think? 
I've looked at static operators and it seems fine (except missing type hints, but it won't break API if v3 is released before).

**Comment by dbrattli** [comment]
I think this looks like a good idea. It will make the functions simpler and more clear in how you should use them instead of a single function will all kinds of variants.

**Comment by dbrattli** [comment]
But we need to get these changes in asap to reach the v3 release (scheduled for this weekend). Would be great if you had time to look at it so we get buffer operators fixed before sunday @jcafhe ? The window operator PR is btw approved and ready to be merged.

**Comment by jcafhe** [comment]
@dbrattli yes, sure, I'll do it today.

**Comment by dbrattli** [comment]
https://pypi.org/manage/project/Rx/release/3.0.0b4/

**Comment by erikkemperman** [comment]
I understand the desire to release v3 quickly... But speaking just for myself there’s a few things I would really like to submit for consideration prior to release.

I will have a bit of time the next couple of days, so I will try to get as much as I can ready — ideally as concrete PRs, perhaps an issue for discussion as well. I will focus first on things that might (slightly) affect the API surface.

There are also some examples that seem outdated, perhaps someone could look at those?

But just a thought, would it make sense to do an rc release before going to v3 final? Are people really counting on it being released this weekend?

By the way I keep getting warnings about the version string, apparently the packaging tools would prefer it to be “b4” instead of "beta4”?

**Comment by dbrattli** [comment]
We can make an rc-release, but the problem with both beta and rc is that many (most) people will not use them. Thus it's better (imo) to just release 3.0.0 and quickly bump to 3.0.1, 3.0.2, ... once we receive feedback. It's now 467 days since v1.6.1 was released so it's time to ship it, before the community disappears.

We should also go for a much higher cadence with RxPY. So a lot of the work with e.g schedulers could be targeted for v4 since the main new feature of v3 is `pipe()` and having operators as functions.

**Comment by erikkemperman** [comment]
Ok, fair enough, thanks for elaborating!

**Comment by MainRo** [comment]
@dbrattli it seems that there is no v3.0.0 tag on the git repo.
