### ISSUE TITLE
Invalid publish() annotation?

### ISSUE THREAD

**Issue by SF-300** [ReactiveX/RxPY#377]
Hi,

`publish` method is annotated as returning `ConnectableObservable` however - as far as I understand - it actually returns `Callable[[Observable], ConnectableObservable]`. This inconsistency makes Pycharm typechecker go nuts and I have to use `typing.cast` to silence it. Is it my misunderstanding or should I make PR to fix the annotation?

**Comment by dbrattli** [comment]
Thanks for the issue. Please make a PR.
