### ISSUE TITLE
type annotation style guide

### ISSUE THREAD

**Issue by jcafhe** [ReactiveX/RxPY#389]
@dbrattli @erikkemperman  @MainRo Sorry to bother you but I have a question regarding the `Optional` qualifier. 

I'm planning to complete missing type annotations for operators and I often see in the public API (rx.operators.init) function parameters with a default value = `None` typed as not being `Optional` while they are typed as `Optional` in implementation files. E.g. `replay` operator: 

```python
# public API
def replay(mapper: Mapper = None, 
           buffer_size: int = None, 
           window: typing.RelativeTime = None,
           scheduler: typing.Scheduler = None) -> Callable[[Observable], Union[Observable, ConnectableObservable]]:

# Implementation file
def _replay(mapper: Optional[Mapper] = None,
            buffer_size: Optional[int] = None,
            window: Optional[typing.RelativeTime] = None,
            scheduler: Optional[Scheduler] = None
            ) -> Callable[[Observable], Union[Observable, ConnectableObservable]]:
```

 I understand that `Optional` is used to mark an argument which could be `None`, not an 'optional' parameter (default value).

So I was wondering if this is simply something that should be corrected or if this is some kind of pattern I'm not aware of?

**Comment by erikkemperman** [comment]
Not 100% sure, but I think the `Optional` should be in the API as well. I think the type checkers consider it implicit if they see a `None` default, but I believe the guidelines are for authors to include them explicitly — and as far as I know there is no distinction in that regard between API and implementation?

**Comment by dbrattli** [comment]
Yes, the current code is not correct in many places. It should use `Optional[]` if the value can be `None`.  If the argument is marked as optional then the code must test whether the argument is None before using it. Not doing so would cause both static type errors as well as possible runtime errors. Thus it's much safer to mark the argument as optional.

- https://realpython.com/python-type-checking/#the-optional-type
- https://docs.python.org/3/library/typing.html
- https://stackoverflow.com/questions/51710037/how-should-i-use-the-optional-type-hint

**Comment by jcafhe** [comment]
Thanks for your answers and clarifications, it makes things far clearer for me.
