### ISSUE TITLE
Unable to concat Observable[Observable]

### ISSUE THREAD

**Issue by hulucc** [ReactiveX/RxPY#390]
It seems `concat` only support Iterable[Observable]

**Comment by jcafhe** [comment]
Hi,

Yes you are right. Instead, in RxPY v1.6, you should use `concat_all` operator or in RxPY v3.0, `merge` operator with max_concurrent argument set to 1:
```python
import rx
from rx import operators as ops

observables = rx.of(
    rx.of(0, 1),
    rx.of('a', 'b', 'c'),
    rx.of(3, 4, 5),
    )

observables.pipe(ops.merge(max_concurrent=1)).subscribe(print)
```

returns:
```
0
1
a
b
c
3
4
5
>>> 
```

**Comment by hulucc** [comment]
Oh, I see.
