### ISSUE TITLE
to_list operator

### ISSUE THREAD

**Issue by MichaelSchneeberger** [ReactiveX/RxPY#395]
Why is there no `to_list` operator? (There was one in RxPY v1.6)

The current implementation of `to_iterable` is buffering all incoming elements into a list, and then converting it into an iterator. Why not directly returning the list itself?

**Comment by dbrattli** [comment]
The idea was to make it symmetric with `from_iterable`, but the current impl returns an iterator and not an iterable so we should just as well return the list. Previously there was an alias called `to_list` I think. We could add it again.
