### ISSUE TITLE
Are streams created from iterables supposed to be exhaustible/mutable?

### ISSUE THREAD

**Issue by hangtwenty** [ReactiveX/RxPY#40]
I'm really puzzled by something in RxPY. It seems to be different from RxJS in a crucial way.

Please take a look at [my contrived RxJS example on JSFiddle](http://jsfiddle.net/9EjSQ/76/), then look at the equivalent RxPY code below.

In the examples, I create a single stream, then create two new streams by transforming it. I subscribe two observers to the streams. In RxJS, I get the result I expect. In RxPY, I get a confusing result.

```python
import rx

def on_next_1(s):
    print "subscriber 1: ", s

def on_next_2(s):
    print "subscriber 2: ", s

ns = rx.Observable.from_(['a', 'b', 'c'])

xs = ns.map(lambda s: s)
ys = ns.map(lambda s: s.upper())

xs.subscribe(on_next_1)
xs.merge(ys).subscribe(on_next_2)
```

This RxPY code produces this output:

```
subscriber 1:  a
subscriber 1:  b
subscriber 1:  c
```

This is the output I would expect (just like the RxJS output):

```
subscriber 1: a
subscriber 1: b
subscriber 1: c
subscriber 2: a
subscriber 2: A
subscriber 2: b
subscriber 2: B
subscriber 2: c
subscriber 2: C
```

In the RxPY code, it seems the first observer works, but the second observer gets nothing. It's like the `ns` is a mutable object that is changing in place. But shouldn't each call to `Observable(...).map` return a new `Observable`? Is it really the desired/designed behavior, for `Observable.from_(<a list>)` to fire just once and be exhausted, even when you're deriving more than one new `Observable`s from it?

I cannot tell if this is a bug, or if I'm missing a fundamental point! It _seems_ like the current behavior violates expectations about the Observer pattern. Isn't the contract, that each subscriber gets each message? What am I missing?

**Comment by hangtwenty** [comment]
I may have answered my own question.

```
import rx


def on_next_1(s):
    print "subscriber 1: ", s


def on_next_2(s):
    print "subscriber 2: ", s


ns = rx.Observable.from_(['a', 'b', 'c']).publish()

xs = ns.map(lambda s: s)
ys = ns.map(lambda s: s.upper())

xs.subscribe(on_next_1)
xs.merge(ys).subscribe(on_next_2)

ns.connect()
```

Doh. That produces my exepcted output. The [rubber duck](http://en.wikipedia.org/wiki/Rubber_duck_debugging) is pretty good huh? [Here's the RxJS code updated to look the same as the working RxPY code](http://jsfiddle.net/9thnr8b2/). This begs the question: does RxPY have "normal" defaults for [cold vs. hot observables](http://jsfiddle.net/9thnr8b2/)? (I'm new to Rx*, so please forgive me if I'm misusing vocabulary.) Why is RxPY different from RxJS in this case? Does it deserve documentation?

I'd be glad to add this documentation if it's warranted, as soon as I have clarity about it!

Please feel free to close this ticket... Just want to check if there's anything I can do, before we do.

**Comment by dbrattli** [comment]
There was a serious bug in `Observable.from_iterator` where all subscriptions shared the same iterator, that's why `xs.subscribe(on_next_1)` had the side-effect of exhausting the iterator and the next subscription didn't receive any events. 

Many thanks for reporting this issue!!

Other than that, it's always hard to know the ordering of subscribing to multiple cold observables since the all events from one observable happens at the exact same time. They are only separated by ordering. Thus one subscription may even complete before the other one gets subscribed. It's all up to the scheduler, and `merge` uses the immediate scheduler as default.

To get a more realistic view, you can use a testing tool I have made called `Observable.from_string()` that you can use after importing `rx.texting.stringify`. Use the develop branch for now since there was a bug in that function that I fixed earlier today. There you can insert time between the events using the `-` char. You can add errors etc.

```python
@extensionclassmethod(Observable)
def from_string(cls, string, scheduler=None):
    """Converts a marble diagram string to an observable sequence, using an
    optional scheduler to enumerate the events.

    Special characters:
    - = Timespan of 100 ms
    x = on_error()
    | = on_completed()

    All other characters are treated as an on_next() event at the given
    moment they are found on the string.

    Examples:
    1 - res = rx.Observable.from_string("1-2-3-|")
    2 - res = rx.Observable.from_string("1-2-3-x", rx.Scheduler.timeout)
```

**Comment by hangtwenty** [comment]
Wow, awesome. I am so relieved to know I wasn't completely lost on this. Haha. I'm new but my [reading](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754) [materials](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/creating.md#cold-vs-hot-observables) made me feel like something was amiss.

Thanks for the quick and elucidating response, I really appreciate it.

`Observable.from_string()` is AMAZING, I wanted something like this so badly that I was tempted to write it myself. Thank you for sharing!

On a related note, are there plans to expand the RxPY documentation? It would be great to learn about `Observable.from_string()` as a beginner.

**Comment by hangtwenty** [comment]
@dbrattli On a related note, are there plans to expand the RxPY documentation? It would be great to learn about `Observable.from_string()` as a beginner.
