### ISSUE TITLE
Question about 3.0 upgrade path

### ISSUE THREAD

**Issue by cowlicks** [ReactiveX/RxPY#435]
Hi I'm excited about using 3.0 in my own projects whenever it is released. However, I'm concerned there won't be a practical upgrade path for most projects.

My understanding is that 3.0 contains significant breaking changes (which are all needed improvements). But if I want to include it in a project, it would mean that my project cannot have dependencies which depend on rx 1.x. It would also mean no one could include my project as a dependency as long as they had anything that depended on 1.x. I feel like these limitations would dramatically slow adoption of 3.0.

Have y'all considered releasing 3.0 as a separate package? I'd  use it immediately if so.

**Comment by MainRo** [comment]
The way to chain operators in RxPY 3 is very different than the way it is done on RxPY 1. So it effectively means that it will not be possible for a project to be compatible with both v1 and v3 in a single release (AFAIK).
I will also have this issue on several of my projects. My personal plan is to simply leverage semantic versioning: Let's say I have project Foo version 1.1.0 using RxPY v1. I will create a maintenance branch for new releases of Foo 1.x. In parallel I will do the porting to RxPY v3 on master and release versions as Foo v2.x. So I can start porting all my projects step by step without breaking existing code (They just have to ensure they depend on RxPY v1 based packages in their dependencies).
So there is no need to rename RxPY as another package, the major version changed and will allow all projects to choose using either v1 or v3.
I think we are all aware that these changes can slow the transition. But I hope that the benefits will be worth the effort for most developers.
