### ISSUE TITLE
Difference between  subscribe_on and observe_on?

### ISSUE THREAD

**Issue by 4n4nd** [ReactiveX/RxPY#436]
[Here](https://rxpy.readthedocs.io/en/latest/reference_operators.html?highlight=observe_on#rx.operators.subscribe_on) it says to see the remarks section, but I couldn't find it. Is there any other documentation available for it?

Thanks

**Comment by MainRo** [comment]
We must update the link, this is now in the *[CPU Concurrency](https://rxpy.readthedocs.io/en/latest/get_started.html#concurrency)* section.

**Comment by 4n4nd** [comment]
great! thanks
