### ISSUE TITLE
RxPY 1.6 deprecation warning

### ISSUE THREAD

**Issue by MainRo** [ReactiveX/RxPY#438]
On RxPY 1.6, we have following warning with python 3.7:
```
rx/linq/observable/selectmany.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(selector_result, collections.Iterable):
```

I would be nice to put RxPY v1 in maintenance mode (once v3 is released) and still do some maintenance releases with fixes that would prevent it to work.

**Comment by tirkarthi** [comment]
This seems to be fixed now with collections.abc being used in all places.
