### ISSUE TITLE
RxPY 3.0.1: catch_exception operator missing

### ISSUE THREAD

**Issue by leinardi** [ReactiveX/RxPY#449]
I'm porting some code from RxPY 1.6.1 to 3.0.1 but I just notice that the operator `catch_exception` seems to be missing.

It is documented on the official doc:
![image](https://user-images.githubusercontent.com/273338/61590463-12d92c00-abba-11e9-9acf-033ae86952b5.png)

but if you search for it inside the repo code you can't find any occurrence, beside the doc itself:
![image](https://user-images.githubusercontent.com/273338/61590470-313f2780-abba-11e9-86dd-7a9fbb4be5fc.png)

I noticed that there is an operator called `catch`: https://github.com/ReactiveX/RxPY/blob/43f54f4d4f1e6369cb3c2e0d9ed0359115a49847/rx/operators/__init__.py#L298

should this be used instead of  `catch_exception`?

**Comment by jcafhe** [comment]
That's right, `catch_exception` has been renamed to `catch` from commit ba0b61b51507bfd196bac447121737b7ec42db0b.

Also the signature has been updated (PR #404). So now, it requires only one parameter which can be a "continuation" `Observable` or a `Callable[[Exception, Observable], Observable]`.
