### ISSUE TITLE
(idea) Is it crazy to integrate RxPy and Celery, or RxPy and RabbitMQ?

### ISSUE THREAD

**Issue by hangtwenty** [ReactiveX/RxPY#45]
Just an idea, that I'm wondering if I should explore or nip in the bud. Looking for some Rx wisdom I suppose, since I'm a newb.

I'm looking at these:
- http://pika.readthedocs.org/en/0.9.14/examples/twisted_example.html (Since there's an asyncio scheduler there can probably be a Twisted scheduler ... [right](https://glyph.twistedmatrix.com/2014/05/the-report-of-our-death.html)?)
- http://pika.readthedocs.org/en/0.9.14/examples/tornado_consumer.html

I'm also thinking about [Celery](http://celery.readthedocs.org/en/latest/userguide/canvas.html) and how to either integrate it with RxPy, or to imitate a small part of RxPy with Celery's operators. Integration would be nicer. Or if RxPy + ((Twisted or Tornado) + pika + RabbitMQ) could replace the need for Celery for some projects... that would also be interesting.

Is this something worth thinking about and trying to work on? Or am I mixing incompatible patterns? Opinions?

**Comment by dbrattli** [comment]
Are you trying to build something similar to [Storm](http://storm.apache.org) like a real-time processing flow/network, or more like the [Akka](http://akka.io/) actors for highly concurrent distributed applications?

**Comment by hangtwenty** [comment]
Great question.

I found my way to ReactiveX via Akka and [reactive-streams](http://www.reactive-streams.org/). (Specifically, [this presentation](http://spray.io/msug/#/).) So Akka is relevant, but I'm not necessarily after that actor model. My attention was caught by Akka's DSL for reactive streams, a DSL that looks a lot like RxJava.

I'm after the "highly concurrent" and "distributed" aspects, and the rest is unclear. My primary imagined use-case is very IO-bound (within workers). Perhaps RxPY the wrong tool for this kind of job.

Regarding Storm, the [streamparse](https://github.com/Parsely/streamparse) library is compelling. And it's README says this (*emphasis* mine):

> It can be viewed as a more robust *alternative to Python worker-and-queue systems, as might be built atop frameworks like Celery and [RabbitMQ].* It offers a way to do "real-time map/reduce style computation" against live streams of data. It can also be a powerful way to scale long-running, highly parallel Python processes in production.

It already exists ... maybe that's the right tool for the job. The code won't be as elegant as RxPY code, but I'm not sure there's anything elegant about RxPY-integrated-with-Celery-or-RabbitMQ.

Thanks for entertaining my discussion, hopefully the thread is useful to someone else with similar ponderings. Finding Storm & streamparse is going to be so helpful to me, thank you!

Any other thoughts, for posterity?

**Comment by hangtwenty** [comment]
People have integrated Storm with RxJava ([relevant discussion thread](https://groups.google.com/forum/#!topic/rxjava/yTM9o596uL0), [relevant discussion thread](https://groups.google.com/forum/#!topic/rxjava/Z19QnMnuMuM)). I might try RxPY + Storm, using streamparse...
