### ISSUE TITLE
Learning, Examples, Tutorials

### ISSUE THREAD

**Issue by mitchelllisle** [ReactiveX/RxPY#454]
Hi! I am just getting into ReactiveX but am really enjoying it so far. With 3.0 coming out a lot of the old code snippets are out of data and although it's not too difficult to transpose, a lot of the old examples don't cover things like creating Observable from scratch etc.

Are there any plans to work on some training material? If so, I would be happy to send across a list of things that would really help me as I'm learning that might help in determining what training material would be of use to others.

**Comment by mitchelllisle** [comment]
for instance, I was a big fan of this series https://learning.oreilly.com/videos/reactive-python-for/9781491979006/9781491979006-video294981

Something like this but with new RxPy 3.0 syntax and other use cases would be awesome.

**Comment by MainRo** [comment]
I suppose that it is a matter of time before old content is updated, or new content appear. Since the release of v3 is recent, there is not a lot of available material yet. in the meantime, the documentation should help to rewrite available tutorials and code to v3 syntax.

**Comment by MainRo** [comment]
Closing this issue since it is quite out of reach of the maintainers for rxpy. On my side I updated the code of my book, I am not sure what the other authors plan to do.
