### ISSUE TITLE
Add generic typings

### ISSUE THREAD

**Issue by dev-solid-desktop** [ReactiveX/RxPY#461]
with python3.5+, we now have [static-typing](https://docs.python.org/3/library/typing.html) with [generics](https://docs.python.org/3/library/typing.html#generics)

But the current code inside rxpy does not account for generics:

```python
class BehaviorSubject(Subject):
    """Represents a value that changes over time. Observers can
    subscribe to the subject to receive the last (or initial) value and
    all subsequent notifications.
    """

    def __init__(self, value) -> None:
        ...
```

One quick fix for this is adding `typevars`:

```python
from typing import (
    Generic,
    TypeVar,
    Callable,
)

T = TypeVar('T')


class Subject(Generic[T]):
    def subscribe(self, func: Callable[[T], None]):
        ...


U = TypeVar('U')


class BehaviorSubject(Subject[U], Generic[U]):
    def __init__(self, value: U):
        ...
```

Note that current IDE support is not "very good" like typescript.
But that'll improve, as everyone (google/fb/ms/dropbox/etc) is trying to create a decent type-checker

**Comment by sobolevn** [comment]
Operators also ignores the generic part. Here's an example: https://github.com/ReactiveX/RxPY/blob/master/rx/operators/__init__.py#L40

All `Observable` instances there would have `Observable[Any]` type. Which is not very typesafe!
We are really interested in this: https://github.com/dry-python/returns/issues/420

**Comment by devdoomari3** [comment]
I actually ended up creating overload-wrappers for operators... it feels like pre-version-5 rxjs :(

seems python type-checking lack a lot of inference features I take for granted on "Typescript Land"

(and the one-liner-lambda that can only be typed by defining with "callable" is ...uhg 🤮 )

```
import rx
from typing import TypeVar, Tuple, Union, cast, Optional

from typing_extensions import overload


T1 = TypeVar('T1')
T2 = TypeVar('T2')
T3 = TypeVar('T3')
T4 = TypeVar('T4')
T5 = TypeVar('T5')

@overload
def combine_latest(
        s1: rx.typing.Observable[T1],
) -> rx.typing.Observable[Tuple[T1]]: ...

@overload
def combine_latest(
        s1: rx.typing.Observable[T1],
        s2: rx.typing.Observable[T2],
) -> rx.typing.Observable[Tuple[T1,T2]]: ...

@overload
def combine_latest(
        s1: rx.typing.Observable[T1],
        s2: rx.typing.Observable[T2],
        s3: rx.typing.Observable[T3],
) -> rx.typing.Observable[Tuple[T1,T2,T3]]: ...

def combine_latest(
        s1: rx.typing.Observable[T1],
        s2: Optional[rx.typing.Observable[T2]],
        s3: Optional[rx.typing.Observable[T3]],
) -> rx.typing.Observable:
    return rx.combine_latest(cast(rx.Observable, [s1, s2, s3]))
```

**Comment by sobolevn** [comment]
We have done a working Higher Kinded Types library that is compatible with `mypy`.
https://returns.readthedocs.io/en/latest/pages/hkt.html

@dbrattli are you interested in incorporating it into RxPY?

**Comment by dbrattli** [comment]
This is fixed in the latest --pre release and will be fixed in the next major release
