### ISSUE TITLE
Completable, Single and Maybe

### ISSUE THREAD

**Issue by leinardi** [ReactiveX/RxPY#465]
Is there something equivalent to the concept of Completable, Single and Maybe in RxPy3?

I'm referring to this: http://reactivex.io/RxJava/javadoc/io/reactivex/Completable.html

**Comment by MainRo** [comment]
There are only Observables in RxPY 3

**Comment by leinardi** [comment]
Can I emit None on RxPy3? What is the best way to replicate a Completable?

**Comment by MainRo** [comment]
I would say the most similar way to express a Completable is to use the ignore_elements operator: It will complete/error when the source observable completes or raises an error.
I you need to create a Completable from scratch, you can create an Observable that does not emit any item.
