### ISSUE TITLE
Naming Conventions in RxPy

### ISSUE THREAD

**Issue by AjawadMahmoud** [ReactiveX/RxPY#466]
Coming from `rxjs`, I'm finding few naming conventions little wired. Here I'm listing two that most noted by me:
1. `rx.subject.Subject` uses `on_next` as method to send message to the `Subject`. I expect method name to be `Subject.name`.
2. Although `Observable.subscribe` method is using `on_completed` as arg for `complete` event, `Observable` uses method name `dispose`. I expect method name to be `Observable.complete`.

**Comment by dbrattli** [comment]
RxPY uses the original naming from RxNET. RxJS have changed the naming.

**Comment by AjawadMahmoud** [comment]
Fair enough.
