### ISSUE TITLE
Could not await timeout observable

### ISSUE THREAD

**Issue by kerol2r20** [ReactiveX/RxPY#471]
Hi all,

```py
import rx
import asyncio
from rx import operators as op

async def main():
    obs = rx.never().pipe(
        op.timeout(1.0)
    )
    await obs

asyncio.run(main())
```

This snippet would block at `await obs`.
I expect it would throw out a timeout exception, but it no do that.
How could I deal with it?

Thanks~

**Comment by MainRo** [comment]
Do you use rxpy 3.0.1 (from pypi) ?
If so you can test on master. It should be fixed with #462

**Comment by kerol2r20** [comment]
Thank you!
I test successfully on master branch!

**Comment by kerol2r20** [comment]
Excuse me
Would this change apply on next release?

**Comment by MainRo** [comment]
yes

**Comment by kerol2r20** [comment]
Thanks a lot~
