### ISSUE TITLE
Could not await a subject that would pushed a value later

### ISSUE THREAD

**Issue by kerol2r20** [ReactiveX/RxPY#472]
Hi all,

```py
import rx
from rx import operators as rxop
from rx.subject import ReplaySubject, Subject
import asyncio

async def main():
    interval = rx.interval(2.0)
    subject = Subject()
    interval.subscribe(subject)

    await subject.pipe(rxop.take(1)) # This would block forever

asyncio.run(main())
```

I found a subject could not be awaited when it was empty at the beginning.
But if subject contain value at the beginning, it would work well.

```py
import rx
from rx import operators as rxop
from rx.subject import ReplaySubject, Subject
import asyncio

async def main():
    interval = rx.interval(2.0)
    sub = ReplaySubject()
    interval.subscribe(sub)
    await asyncio.sleep(2.0) # Wait one value pushed into subject
    await sub.pipe(rxop.take(1)) # This would work well

asyncio.run(main())
```

How to deal with it?
Thanks

**Comment by kerol2r20** [comment]
Would anyone have suggestions?

**Comment by kerol2r20** [comment]
Dear @MainRo 

I have read your blog article about RxPY working with Asyncio.
I modified previous snippet as the following.

```py
import rx
from rx import operators as ops
from rx.subject import Subject
from rx.scheduler.eventloop import AsyncIOScheduler
import asyncio


async def main():
    src = rx.interval(1.0)
    subject = Subject()
    src.subscribe(subject)
    done = asyncio.Future()

    def on_complete():
        done.set_result(123)

    subject.pipe(
        ops.take(2)
    ).subscribe(
        on_next=lambda i: print(f"Next: {i}"),
        on_completed=on_complete,
        scheduler=AsyncIOScheduler(loop=loop)
    )

    await done
    print("Complete")

loop = asyncio.get_event_loop()
asyncio.run(main())
```

But it still block at `await done`.
Would you know how about it?

Thanks~

**Comment by jcafhe** [comment]
Hi,

Not sure I fully understand your problem here, but in your first example, I'm pretty sure it blocks forever because you didn't specify the AsyncioScheduler in the subcribe method of the source observable.
 
```python
import rx
from rx import operators as rxop
from rx.scheduler.eventloop import AsyncIOScheduler
from rx.subject import ReplaySubject, Subject
import asyncio

async def main():
    scheduler = AsyncIOScheduler(asyncio.get_event_loop())

    interval = rx.interval(2.0)
    subject = Subject()
    interval.subscribe(subject, scheduler=scheduler)

    await subject.pipe(rxop.take(1)) # This block for 2.0 s


asyncio.run(main())
print('finished!')
```

**Comment by MainRo** [comment]
@kerol2r20, there two reasons why your code sample does not work.
First, as said by @jcafhe you need to provide an AsyncIOScheduler when subscribing to the Subject (BTW the subject it is not needed in this example, you can directly subscribe to src, but maybe you have more logic in your real code).

Then asyncio.run always creates a new event loop (c.f. https://docs.python.org/3/library/asyncio-task.html#asyncio.run). So the asyncio scheduler is using an event loop that will never be started. You can replace asyncio.run with loop.run_until_complete and it will work:

```
import rx
from rx import operators as ops
from rx.subject import Subject
from rx.scheduler.eventloop import AsyncIOScheduler
import asyncio


async def main():
    scheduler=AsyncIOScheduler(loop=loop)
    src = rx.interval(1.0)
    subject = Subject()
    src.subscribe(subject, scheduler=scheduler)
    done = asyncio.Future()

    def on_complete():
        print("completed")
        done.set_result(123)

    subject.pipe(
        ops.take(2)
    ).subscribe(
        on_next=lambda i: print(f"Next: {i}"),
        on_completed=on_complete,
        scheduler=scheduler
    )

    print(loop)
    await done
    print("Complete")

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by kerol2r20** [comment]
Dear @MainRo, @jcafhe 
Thank you for your response.
In my application, the source is a IO input stream which come from other threads.
So I have to buffer them into ReplaySubject, and then handle them after a while.
I want to use native Observable and operators to emulate the scenario.

According to your suggestion, I tried to modify my code.
But it still block when I want to await it.
The following snippet is more like my real application

```py
import asyncio
from rx import operators as ops
from rx.scheduler.eventloop import AsyncIOScheduler
from rx.subject import Subject, ReplaySubject
import threading
import time
import random

src = Subject()

# Emulate IO input stream
def random_push_source():
    count = 0
    while True:
        time.sleep(random.randint(1, 4))
        src.on_next(count)
        count += 1


threading.Thread(target=random_push_source).start()

loop = asyncio.get_event_loop()


async def main():
    rp = ReplaySubject()
    src.subscribe(rp, scheduler=AsyncIOScheduler(loop=loop))
    print("Start wait")
    await rp.pipe(
        ops.take(1)
    ) # Block forever
    print("Complete")


src.subscribe(lambda i: print(f"thread: {threading.currentThread().ident}. p = {i}"))
loop.run_until_complete(main())
```

Thanks

**Comment by MainRo** [comment]
ok, the items emitted on src come from another thread. So you need to re-schedule them on the asyncio event loop with AsyncIOThreadSafeScheduler. something like this should work:

```
src.pipe(
   ops.observe_on(scheduler=AsyncIOThreadSafeScheduler(loop=loop))
).subscribe(rp, scheduler=AsyncIOScheduler(loop=loop))
```

**Comment by kerol2r20** [comment]
All done! Thank you very much!
What's the magic of AsyncIOThreadSafeScheduler and AsyncIOScheduler?

**Comment by MainRo** [comment]
Nice !
The AsyncIOScheduler follows the principle of the similar asyncio functions: It can be used to schedule tasks only on the current event loop (i.e. on the thread running the current event loop). There are situations (like the one of this issue) where items are emitted from another thread. In this case there are dedicated functions in asyncio that allow to schedule a task from any thread to a specific event loop.
We chose to split these behaviors in two dedicated schedulers, that's why both schedulers are needed in your case.

**Comment by kerol2r20** [comment]
Resolved! Thanks
