### ISSUE TITLE
timeout and retry cause "Do not schedule blocking work!"

### ISSUE THREAD

**Issue by freelancer1845** [ReactiveX/RxPY#476]
I can't figure out how to use **timeout** and **retry** in the same operator chain. I think the timeout is scheduled in "TimeoutScheduler" but the retry moves it back to "Trampolinscheduler" resulting in strange behavior.

# Example

```python
import rx
import rx.operators
import datetime
import time

rx.interval(5.0).pipe(
    rx.operators.timeout(4.0),
    rx.operators.retry()
).subscribe(on_next=lambda x: print("next"), on_error=lambda x: print("Error: " + str(x)))


while True:
    time.sleep(1.0)
```
This example produces unending "Do not schedule blocking work!" log messages originating form TrampolinScheduler.

If I add 
```python
rx.operators.do_action(on_error=lambda x: print("Error: " + str(x))),
```
to the operator chain i get:

> Do not schedule blocking work!
> Error: 'CurrentThreadSchedulerSingleton' object has no attribute 'schedule_periodic'

(Also flooding the log)

I tried using 
```python
scheduler = rx.scheduler.ThreadPoolScheduler(max_workers=10)
````
which works if I use it as scheduler in the subscribe call.

But I'm wondering If this is the correct solution... because I don't really do blocking calls, do I?

I my case I have an Observable that works like a heartbeat and if there is no heartbeat I want to emit a signal.

## Java
* I'm more used to RxJava where this works.

```java
Observable.interval(5000, TimeUnit.MILLISECONDS)
                  .timeout(1000, TimeUnit.MILLISECONDS)
                  .doOnError(er -> System.out.println("Timeout..."))
                  .retry()
                  .subscribe();
```

**Comment by jcafhe** [comment]
Hi,
thanks for your comment. You are right, it doesn't work as expected and I suspect a conflict in `catch_with_iterable`.

Under the hood, `retry` is based on `catch_with_iterable`. So  when the subscription scheduler is not given, `catch_with_iterable` will subscribe to the upstream observable with its own default scheduler, e.g. CurrentThreadScheduler. Maybe we need to forward the downstream scheduler to the subcribed upstream observable even if it's None (source will choose whatever scheduler is appropriate), and keep CurrentThreadScheduler to handle `catch_with_iterable` scheduling machinery.
