### ISSUE TITLE
Bug in combine_latest

### ISSUE THREAD

**Issue by filonik** [ReactiveX/RxPY#48]
It seems that combine_latest is buggy. I believe the `result_selector = args.pop()` line needs to be moved before the preceding if statement:

    if args and isinstance(args[0], list):
        args = args[0]
    else:
        args = list(args)

    result_selector = args.pop()

**Comment by dbrattli** [comment]
Thanks. It needs to be moved before since the result selector is the last argument. But I needed to fix things a bit more since args is a tuple and you cannot `pop` from tuples.
