### ISSUE TITLE
to_iterator seems to spin forever

### ISSUE THREAD

**Issue by c200chromebook** [ReactiveX/RxPY#484]
You'll excuse me if this is a dumb question - I'm looking to, in lieu of a subscribe fn, send back an iterator. I think this would be how to do it, but this indeed seems to spin forever. What am I doing wrong? Can I convert a observable to a generator or iterable?

    z=rx.from_list(range(25)).to_iterator()

**Comment by c200chromebook** [comment]
Ah. Seems to be grabbing the wrong to_iterator.

**Comment by MainRo** [comment]
if you want to convert an observable to a list variable, you need to combine to_iterable with run:

```
import rx
import rx.operators as ops

z=rx.from_list(range(25)).pipe(ops.to_iterable()).run()

print(type(z))
print(list(z))
```

to_iterable converts the observable to an observable that emits only one item (an iterable that emits all items of the source observable). Run blocks until the observable completes and return the last value emitted, i.e. the iterable.
