### ISSUE TITLE
count() doesn't seem to work with group_by()

### ISSUE THREAD

**Issue by fra-luc** [ReactiveX/RxPY#488]
Hi all,
while trying this library I came across what seems to be a bug. I'm trying to group a stream of integers ranging from 0 to 9 by being odd or even.

```python
from rx import from_, range as rxrange
from rx.operators import group_by, count


def even_or_odd(x):
    if x % 2 == 0:
        return 'even'
    return 'odd'


def group_consumer(group_observable):
    def print_number(n):
        print(f"Observable {group_observable.key}: count {n}")

    group_observable.pipe(count()).subscribe(print_number)


print("---> With from_")
test1 = from_(range(10)).pipe(group_by(even_or_odd)).subscribe(group_consumer)
print("\n---> With rx.range")
test2 = rxrange(0, 10, 1).pipe(group_by(even_or_odd)).subscribe(group_consumer)

```

The output is:

```bash
---> With from_
Observable even: count 0
Observable odd: count 0

---> With rx.range
Observable even: count 3
Observable odd: count 3

Process finished with exit code 0
```

Two things are odd in the output:

1. The result is different depending upon the usage of `from_` or `rx.range` (they should do the same, right?)
2. In both cases the result is wrong (should be 5 and 5, right?)

I hope I am not making some silly mistake,
thank you for your help.

**Comment by MainRo** [comment]
The difference between the two cases is due to a difference when items are scheduled: The range operator schedules each item emission via the current thread scheduler. This not the case with the from_ operator. 

The first example works as expected if the items are emitted **after** the subscription:

```
import time
import rx
import rx.operators as ops
from rx.subject import Subject

def even_or_odd(x):
    if x % 2 == 0:
        return 'even'
    return 'odd'


def group_consumer(group_observable):
    def print_number(n):
        print(f"Observable {group_observable.key}: count {n}")

    group_observable.pipe(ops.count()).subscribe(print_number)


source = Subject()
print("---> With from_")
test1 = source.pipe(ops.group_by(even_or_odd)).subscribe(group_consumer)

for i in range(10):
    source.on_next(i)
source.on_completed()
```

I will check why on the second example only some of the items are received instead of none|all. 

Not related, but just as a comment: The double subscription in the example can be replaced with a flat_map which would improve readability:

```
def print_number(n):
    print(f"Observable {n[0]}: count {n[1]}")

source = Subject()
counts = source.pipe(
    ops.group_by(even_or_odd),
    ops.flat_map(lambda i: i.pipe(
        ops.count(),
        ops.map(lambda ii: (i.key, ii)),
    ))
)

counts.subscribe(print_number,
    on_error=lambda e: print(e))

for i in range(10):
    source.on_next(i)
source.on_completed()
```

**Comment by fra-luc** [comment]
Thank you for your answer and for your suggestions!

**Comment by jcafhe** [comment]
@MainRo if it helps you, I've digged a bit this issue some time ago, and despite the fact I can't explain why, I think this behaviour comes from a weird interaction with `concat_with_iterable` called thru :
`count` -> `reduce`-> `start_with` -> `rx.concat` -> `concat_with_iterable`

I've worked a bit with the following sample based on @fra-luc  to try to isolate the problem (with no success). This sample should prepend values 100 and 200 (coming from two cold observables) to the 'even' and 'odd' grouped observables with . Obviously, this is not working as it should be. It seems that the prepend observables are 'eating' values from grouped observables.

```python
import rx
from rx import operators as ops
from rx.subject import ReplaySubject

def even_or_odd(x):
    if x % 2 == 0:
        return 'even'
    return 'odd'

prepend_values = rx.just(100)
prepend_values2 = rx.just(200)

def mapper(group):
    gname = group.key
    if gname == 'odd':
        sformat = ' ' * 20 + 'odd: {}'
    else:
        sformat = ' ' * 32 + 'even: {}'

    return rx.concat(prepend_values, prepend_values2, group).pipe(
        ops.map(lambda x: sformat.format(x))
        )


x = rx.range(0, 10).pipe(
    ops.do_action(lambda x: print(f'range:next: {x}'), print, lambda: print('range:completed')),
    ops.group_by(even_or_odd),
    ops.flat_map(mapper),
    )

x.subscribe(
    print,
    )

```

output:
```
range:next: 0
range:next: 1
                                even: 100
range:next: 2
                    odd: 100
range:next: 3
                                even: 200
range:next: 4
                    odd: 200
range:next: 5
range:next: 6
                                even: 6
range:next: 7
                    odd: 7
range:next: 8
                                even: 8
range:next: 9
                    odd: 9
range:completed
>>>
```

Also note that `concat_with_iterable` may have a bug regarding the scheduler used to subscribe to the sources, i.e. it subscribes to the sources with its own CurrentThreadScheduler when the subscribe scheduler is None.

**Comment by MainRo** [comment]
Some news, I have (probably) the same issue on a pipeline that involves windowing and sum:

```
data = range(25)


def sum(acc, i):
    return acc + i

rx.from_(data).pipe(
    ops.window_with_count(count=3, skip=1), # emits a last empty observable
    ops.flat_map(lambda i: i.pipe(
        ops.do_action(
            on_next=lambda i: print("i: {}".format(i)),
            on_completed=lambda: print("Done"),
        ),
        ops.sum(),
    )),
).subscribe(
    on_next=print,
    on_error=lambda e: print("error: {}".format(e)),
    on_completed=lambda: print("Done"),
)
```

I am pretty sure that the issue comes from the usage of concat: Concat subscribes to observables one after the other. The fact that reduce uses concat to feed the seed means that we can loose the first items of the group/window observables before we subscribe to them. 
So I think all operators based on reduce with seed have the same issue. 

So possibly this could be fixed by changing in reduce.py:

```
return pipe(scanner, initial, ops.last())
```

with:
```
return pipe(scanner, ops.last_or_default(seed))
```
