### ISSUE TITLE
Scheduler provided in subscribe is not used for all observable factories

### ISSUE THREAD

**Issue by frederikaalund** [ReactiveX/RxPY#489]
We now have `Observable.subcribe(..., scheduler=scheduler)`, which is really nice. Let's take the API all the way.

[The documentation says that](https://rxpy.readthedocs.io/en/latest/get_started.html#default-scheduler):

> Operators that accept a scheduler select the scheduler to use in the following way:
>  * If a scheduler is provided for the operator, then use it.
>  * If a default scheduler is provided in subscribe, then use it.
>  * Otherwise use the default scheduler of the operator.

I know that this applies to operators but I think that it would make sense if it also applied to observable factories. This way, we can finally get rid of all the `scheduler=scheduler` boilerplate. See #183 for additional info.

The `timer` observable factory, for instance, still defaults to the `TimeoutScheduler` .

I guess this is a feature request.

**Comment by MainRo** [comment]
This should already work: The timer factory defaults to TimeoutScheduler when no scheduler was provided to the factory and the subscription. So if you provide a scheduler in subscribe, it should be back-propagated up to the timer factory.

**Comment by frederikaalund** [comment]
> This should already work: The timer factory defaults to TimeoutScheduler when no scheduler was provided to the factory and the subscription. So if you provide a scheduler in subscribe, it should be back-propagated up to the timer factory.

You're completely right. The is indeed the expected behaviour. I see a different actual behaviour (rxpy v3.0.1). I guess this transforms this issue from a feature request to a bug report.

Consider the following unit test:
```
async def test_subscribe_with_scheduler(self):
    loop = asyncio.get_event_loop()
    scheduler = AsyncIOScheduler(loop)

    def assert_loop():
        loop = asyncio.get_event_loop()
        self.assertIsNotNone(loop)

    obs = rx.of(0).pipe(
        ops.sample(1),
        ops.do_action(lambda _: assert_loop()),
        ops.share(),  # <-- The culprit!
    )

    on_completed_event = asyncio.Event()
    def on_completed():
        on_completed_event.set()

    obs.subscribe(None, None, on_completed, scheduler=scheduler)

    await on_completed_event.wait()
```
It raises an exception `RuntimeError: There is no current event loop in thread 'Thread-1'.`. From the traceback, I can see that the TimoutScheduler is being used despite the fact that I explicitly provide a scheduler to the subscribe function.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/scheduler/timeoutscheduler.py", line 83, in interval
    sad.disposable = self.invoke_action(action, state)
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/scheduler/scheduler.py", line 103, in invoke_action
    ret = action(self, state)
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/scheduler/periodicscheduler.py", line 47, in periodic
[...]
```

If I remove the `ops.share()` line, then it works as expected. I think that the `share` operator fails to forward the scheduler.

**Comment by jcafhe** [comment]
Hi @frederikaalund, 
I think PR #492  should solve your issue. However, I didn't manage to work with your sample. If that's possible, could you try the changes from [/jcafhe/RxPY/tree/fix-scheduler-ConnectableObservable](/jcafhe/RxPY/tree/fix-scheduler-ConnectableObservable)  against your code?

**Comment by frederikaalund** [comment]
> If that's possible, could you try the changes from /jcafhe/RxPY/tree/fix-scheduler-ConnectableObservable against your code?

That was it! Nice find. I hope to see #492 merged soon.

**Comment by frederikaalund** [comment]
> However, I didn't manage to work with your sample.

For future reference, you can use [unittest.IsolatedAsyncioTestCase](https://docs.python.org/3/library/unittest.html#unittest.IsolatedAsyncioTestCase) to run the code sample.

**Comment by jcafhe** [comment]
Thank's for the tip.
