### ISSUE TITLE
AttributeError: type object 'Observable' has no attribute 'from_iter'

### ISSUE THREAD

**Issue by binbjz** [ReactiveX/RxPY#491]
**Create the data flow based on the iterator.**

**Version info:**
OS: Mac OS catalina 10.15.3
python version: 3.8.1
Rx Version: 3.0.1
```python
from rx import Observable
obs = Observable.from_iterable(range(4))
obs.subscribe(print)
```
**Expected results:**
output：
0
1
2
3

**Actual results:**
AttributeError: type object 'Observable' has no attribute 'from_iter'

**Comment by binbjz** [comment]
```python
obs = rx.from_iterable(range(4))
obs.subscribe(print)
```
0
1
2
3

**Comment by MainRo** [comment]
seems that you answered yourself. This changed in rxpy v3 compared to rxpy v1
