### ISSUE TITLE
buffer is always empty when callback takes longer

### ISSUE THREAD

**Issue by marcj** [ReactiveX/RxPY#496]
Following code

```python
import threading
import time

from rx import interval
from rx.operators import buffer
from rx.scheduler import ThreadPoolScheduler
from rx.subject import Subject

scheduler = ThreadPoolScheduler(1)

print('start', threading.current_thread().name)


def cb1(data):
    print('buffer', threading.current_thread().name, data)
    time.sleep(2)


subject = Subject()
subject.pipe(buffer(interval(1, scheduler=scheduler))).subscribe(cb1)

i = 0
try:
    while True:
        i += 1
        subject.on_next(i)
        time.sleep(1)
except KeyboardInterrupt:
    print('Stop')
    subject.on_completed()
    print('Bye')

scheduler.executor.shutdown()
```

### Expected output

```
start MainThread
buffer ThreadPoolExecutor-0_0 [1]
buffer ThreadPoolExecutor-0_0 [2, 3]
buffer ThreadPoolExecutor-0_0 [4, 5, 6]
```

Because the callback is taking longer (2sec) than the feeder (which waits 1sec) and everything runs in one thread the buffer should get bigger and bigger.

### But actual output

```
start MainThread
buffer ThreadPoolExecutor-0_0 [1]
buffer ThreadPoolExecutor-0_0 []
buffer ThreadPoolExecutor-0_0 []
```

I use `buffer` to queue data to be processed in batches to improve performance.
If the handling of that data takes a bit longer it should just queue up. But currently it's just dropped.

Is this by design? My wild guess is that the buffer is reseted right after the callback has been called, instead of before and passing a copy of the old. Is there a way to work around that?

**Comment by jcafhe** [comment]
Hi,
This is a complex question but IMO, your expectation is a bit wrong. From the buffer docs: 
https://rxpy.readthedocs.io/en/latest/reference_operators.html?highlight=buffer#rx.operators.buffer

![](https://rxpy.readthedocs.io/en/latest/_images/marble-81dbcd0cd7a21fb6c1f4939387f5ff16b1556101.png)

If I understand correctly, you would like `buffer` to merge multiple buffers into a single one buffer when the subscriber (consumer) is not able to finish its work in the amount of time given by boundaries observable. This contradicts the contract shown in the figure above. I would say your case is not supposed to happen or, at least, the behaviour would be undefined. 

Keep in mind that Rx is a push model. To some extend, you can not natively slows down the emission of data depending on the status of your consumer, but you can work with something like a feedback control loop, or you could use an opertor that implements some kind of back-pressure.

Implementing your own operator requires some knowledge of Rx mechanisms but it's not so hard. E.g., as a workaround, here is a quick draft of a custom operator that should do the work (?) :

```python
from typing import Callable, List
from threading import RLock

from rx.core.typing import Observer, Scheduler
from rx.core.observable import Observable
from rx.disposable import CompositeDisposable


def buffer_sync(boundaries: Observable) -> Callable[[Observable], Observable]:
    def buffer_sync(source: Observable) -> Observable:
        def subscribe(observer: Observer, scheduler_: Scheduler = None):

            lock = RLock()
            buffer: List = []
            disposable: CompositeDisposable = CompositeDisposable()

            def boundaries_on_next(_):
                nonlocal buffer
                with lock:
                    b = buffer
                    buffer = []
                observer.on_next(b)

            def source_on_next(x):
                with lock:
                    buffer.append(x)

            def on_error(err):
                observer.on_error(err)

            def on_completed():
                observer.on_completed()

            disposable.add(source.subscribe(
                source_on_next,
                on_error,
                on_completed,
                scheduler=scheduler_,
                )
            )

            disposable.add(boundaries.subscribe(
                boundaries_on_next,
                on_error,
                on_completed,
                scheduler=scheduler_,
                )
            )

            return disposable
        return Observable(subscribe)
    return buffer_sync


```

**Comment by marcj** [comment]
I'm totally fine with not merging so that consumer callbacks are called one-by-one and if necessary queued. The expected output is then like that:

```
start MainThread
buffer ThreadPoolExecutor-0_0 [1]
buffer ThreadPoolExecutor-0_0 [2]
buffer ThreadPoolExecutor-0_0 [3]
buffer ThreadPoolExecutor-0_0 [4]
```

That's better than getting an incorrect empty buffer and probably more aligned with the way buffer should work.
