### ISSUE TITLE
Can I compose pipes dynamically?

### ISSUE THREAD

**Issue by radiantone** [ReactiveX/RxPY#497]
I see how pipes are composed statically in the examples, but let's say I want to create a pipe at runtime and add some arbitrary number of operators to it - within a conditional (if X then add this operator, else add this one). Can I create the pipe and add to it as needed before running it? How would that be done exactly? Thank you.

**Comment by jcafhe** [comment]
Hi, 

yes you can by using higher order operators, like `flat_map`, `switch_latest`, `merge`, etc. or by creating your own operators. 
E.g. you can create an observable of observables with `map` operator, by returning an observable that depends on the incoming values. Then you apply operators like `switch_latest`, `merge_all`. 
Alternatively, you can work with operators that combine the two previous steps like `flat_map`. 

```python
import rx
from rx import operators as ops

condition = rx.from_marbles('--a---b------a--b-|')


def mapper(x):
    if x == 'a':
        return rx.from_marbles('a1-a2-a3-|')
    elif x == 'b':
        return rx.from_marbles('b1-b2-b3-|')
    else:
        return rx.throw(ValueError("x must be 'a' or 'b'"))

condition.pipe(
    ops.map(mapper),  # this will create an observable of observables
    ops.switch_latest(),  # swith to the last created observable
    ).subscribe(print)
```
