### ISSUE TITLE
from_future and asyncio.CancelledError

### ISSUE THREAD

**Issue by frederikaalund** [ReactiveX/RxPY#498]
The [`from_future`](https://github.com/ReactiveX/RxPY/blob/master/rx/core/observable/fromfuture.py) operator no longer forwards `asyncio.CancelledError`s. This is due to a [change](https://bugs.python.org/issue32528) in Python 3.8 that makes `asyncio.CancelledError` inherit from `BaseException` (it inherited from `Exception` in previous releases).

The [current implementation](https://github.com/ReactiveX/RxPY/blob/master/rx/core/observable/fromfuture.py#L29) of `from_future` only forwards `Exception`s:
```
        def done(future):
            try:
                value = future.result()
            except Exception as ex:  # pylint: disable=broad-except
                observer.on_error(ex)
            else:
                observer.on_next(value)
                observer.on_completed()
```

I suggest that we either:
 * Broaden the exception handler even more, so that `BaseException`s are forwarded.
 * Make a specialized version of `from_future` (say `from_coro`) that forwards the relevant cancellation exceptions. I think that the built-in `asyncio.CancelledError` should be supported by default.
 * Add argument to `from_future` that specifies the exception types, that we want to forward. E.g., `ops.from_future(fut, exceptions=(Exception, asyncio.CancelledError))`.

---

I got hit by this issue in practice. It gave me a short and non-descriptive stack trace:
```
<27>1 2020-02-10T11:43:55.556901+01:00 zeus1934001 baxter 5680 - - [geist.geist] Stopped due to error:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/baxter/__main__.py", line 40, in main
    geist.run(_amain())
  File "/usr/lib/python3.8/site-packages/geist/geist.py", line 40, in run
    self.loop.run_forever()
  File "uvloop/loop.pyx", line 1312, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 492, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 409, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "usr/lib/python3.8/site-packages/rx/core/observable/fromfuture.py", line 28, in done
asyncio.exceptions.CancelledError
```
There are no indications of which task got cancelled. This makes it very difficult to debug.

**Comment by MainRo** [comment]
I think that catching BaseException makes sense here. however this may break existing code that handles such exceptions in the loop handler (I do not know how many existing code does this).
An alternative would be to always explicitely catch asyncio.CancelledError, without additional parameter (a mix of your proposed solutions 2 and 3). this would not change the existing behavior and would work on all versions of python.

**Comment by frederikaalund** [comment]
> I think that catching BaseException makes sense here. however this may break existing code that handles such exceptions in the loop handler (I do not know how many existing code does this).
An alternative would be to always explicitely catch asyncio.CancelledError, without additional parameter (a mix of your proposed solutions 2 and 3). this would not change the existing behavior and would work on all versions of python.

Both could work for me. Thanks for taking a look at this.
