### ISSUE TITLE
Using CombineLatest with Subjects

### ISSUE THREAD

**Issue by jdreaver** [ReactiveX/RxPY#50]
Is `combine_latest` supposed to work with subjects? Whenever I try to subscribe to the combined stream, the interpreter freezees because rx requests a lock.

```python
s1 = rx.subjects.BehaviorSubject(1)
s2 = rx.subjects.BehaviorSubject(2)
s = rx.Observable.combine_latest(s1, s2, lambda a, b: (a, b))
s.subscribe(print)  # Freezes here
```

The output I expect is simply `(1, 2)`. I have tried using plain `Subject` as well, but it freezes in the same spot. Here is the stack trace after I press Ctrl-C to interrupt:

```
^CTraceback (most recent call last):
  File "combine.py", line 29, in <module>
    main()
  File "combine.py", line 14, in main
    s.subscribe(print)
  File "/usr/lib/python3.4/site-packages/rx/observable.py", line 51, in subscribe
    return self._subscribe(observer)
  File "/usr/lib/python3.4/site-packages/rx/anonymousobservable.py", line 50, in _subscribe
    current_thread_scheduler.schedule(set_disposable)
  File "/usr/lib/python3.4/site-packages/rx/concurrency/currentthreadscheduler.py", line 54, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/usr/lib/python3.4/site-packages/rx/concurrency/currentthreadscheduler.py", line 68, in schedule_relative
    self.queue.run()
  File "/usr/lib/python3.4/site-packages/rx/concurrency/currentthreadscheduler.py", line 37, in run
    item.invoke()
  File "/usr/lib/python3.4/site-packages/rx/concurrency/scheduleditem.py", line 18, in invoke
    self.disposable.disposable = self.invoke_core()
  File "/usr/lib/python3.4/site-packages/rx/concurrency/scheduleditem.py", line 33, in invoke_core
    return self.action(self.scheduler, self.state)
  File "/usr/lib/python3.4/site-packages/rx/anonymousobservable.py", line 34, in set_disposable
    auto_detach_observer.disposable = fix_subscriber(subscribe(auto_detach_observer))
  File "/usr/lib/python3.4/site-packages/rx/linq/observable/combinelatest.py", line 101, in subscribe
    func(idx)
  File "/usr/lib/python3.4/site-packages/rx/linq/observable/combinelatest.py", line 98, in func
    subscriptions[i].disposable = args[i].subscribe(on_next, observer.on_error, on_completed)
  File "/usr/lib/python3.4/site-packages/rx/observable.py", line 51, in subscribe
    return self._subscribe(observer)
  File "/usr/lib/python3.4/site-packages/rx/subjects/behaviorsubject.py", line 47, in __subscribe
    observer.on_next(self.value)
  File "/usr/lib/python3.4/site-packages/rx/linq/observable/combinelatest.py", line 90, in on_next
    with parent.lock:
KeyboardInterrupt
```

The following program based on observables works:

```python
o1 = rx.Observable.interval(2000)
o2 = rx.Observable.interval(3000)
s = rx.Observable.combine_latest(o1, o2, lambda a, b: (a, b))
s.subscribe(print)
```

I figured that the subject version should be able to work similarly, but I could be wrong as I have only a little experience with Rx. 

Thanks in advance for any help, and sorry if I am simply using this wrong!

**Comment by dbrattli** [comment]
Thanks for reporting. The problem seems to be with `BehaviorSubject`, and `combine_latest` ends up up using the same lock as `BehaviorSubject` at subscribe time. The lock usage has been ported from .NET where locks looks to be reentrant, thus we should probably use `RLock` instead of `Lock` with Python. Else, we should make sure `BehaviorSubject` does not `on_next()` at `subscribe` time while holding the lock. Maybe schedule the `on_next` or something, so it's done on the next turn. I'm looking into this.

**Comment by jdreaver** [comment]
Thanks for looking into this! I'm just glad it wasn't my error :smile:

**Comment by jdreaver** [comment]
It looks like that commit you've made fixed the issue! Thanks!

**Comment by dbrattli** [comment]
Great. I'll probably make another release on master during the weekend, since the issue was pretty serious. But looks like the issue was mostly related to the use of BehaviorSubject which is not used that often. But it's perfekt to be used with ViewModels as you have found out.

**Comment by jdreaver** [comment]
Great!

> But it's perfekt to be used with ViewModels as you have found out.

I'm glad you agree with that. Most of the ReactiveX tutorials I have found imply that subjects are just for toying around with Rx, and any serious reactive pipeline should use an Observable. I think that they are great for wrapping values in models (like I did already), and for wrapping imperative signals (like in Qt). Since Python doesn't have a unified language construct like C#'s `Event`, I expect the first step to many pieces of functionality is to wrap particular GUI framework events into an RxPY `Observable`. I suppose it isn't the most "purely functional" solution, but if you are wrapping an imperative base in a non-functional language, I don't see much else you can do. 

Part of the reason I am making that simple Todo app is to explore the design space around integrating RxPY with a Python GUI framework before I use RxPY in production at work. So far it is very promising!

**Comment by dbrattli** [comment]
Here are some other projects using Rx that you might want to take a look at:

* https://github.com/cwharris/rxjs-splash (using `BehaviorSubject`)
* https://github.com/staltz/todomvc-cycle, https://github.com/staltz/cycle
* http://reactiveui.net/

**Comment by jdreaver** [comment]
Awesome, thanks!

**Comment by ardoramor** [comment]
Thanks for all the hard work! Love what it allows me to do. I see that v1.2.2 has been released but can it also be pushed to pip? Right now, it has 1.2.1 version available.
