### ISSUE TITLE
Using a subject per business entity

### ISSUE THREAD

**Issue by pablocastilla** [ReactiveX/RxPY#503]
Hi!

This is more a conceptual question, not sure if this is the best place to do it.

I will receive a lot of events from devices which are in different houses. I want to process them keeping the state of each house separately.

House 1 --> Subject 1
House 2 --> Subject 2

My overall idea is to have a subject per house, so I can keep certain state on them.

Is this the right direction?

**Comment by MainRo** [comment]
not easy to answer without more information. However if you have an observable per house, then you can maintain a state per hours with the scan operator.
