### ISSUE TITLE
How to get observable mongo data

### ISSUE THREAD

**Issue by tareksamoud** [ReactiveX/RxPY#508]
Hello i'm try to get observable mongo data using Rx 3.1.0, im trying to implement "Observable.from_" an error appear that "from_" is not recongized as observable method

> from pymongo import MongoClient
> from rx import Observable
> 
> def collect_data(dbname, collection):
>     clt = MongoClient('localhost', 27017)
>     db = clt[dbname]
>     col = db[collection]
> 
>     colData= col.find().limit(10)
>     return Observable.from_(colData)
> 
> collect_data('test', 'money').subscribe(print(data))

an error appear that "from_" is not recongized as observable method

I'm trying to use `rx.of` 

> from pymongo import MongoClient
> import rx
> 
> def collect_data(dbname, collection):
>     clt = MongoClient('localhost', 27017)
>     db = clt[dbname]
>     col = db[collection]
> 
>     colData= col.find().limit(10)
>     return rx.of(colData)
> 
> collect_data('test', 'money').subscribe(lambda data: print('{0}'.format(data)))

I get `<pymongo.cursor.Cursor object at 0x000001BF824FE8C8>`

**Comment by MainRo** [comment]
rx.from_ should work:

```
from pymongo import MongoClient
import rx

def collect_data(dbname, collection):
clt = MongoClient('localhost', 27017)
db = clt[dbname]
col = db[collection]

colData= col.find().limit(10)
return rx.from_(colData)
```

The Observable class does not have a from_ method. The rx.just factory operator that you tried creates an observable emitting just the object you provide to it, so the mongo cursor in your case. That's why you get it in the print.

**Comment by tareksamoud** [comment]
thank you for your help
