### ISSUE TITLE
Pipeline called as many times as Observers

### ISSUE THREAD

**Issue by mecton** [ReactiveX/RxPY#512]
I have a first pipeline (main) to which some Observers subscribe and some pipelines branch out.
I was quite surprised to see that the code in my main pipeline runs as many times as the amount of Observers.

``` python
source = Subject()

main = source.pipe(
    # do something
    operators.do_action(lambda x: print('Main pipeline: ' + x))
)

main.subscribe(lambda x: print(' Main Subscriber 1: ' + x))
main.subscribe(lambda x: print(' Main Subscriber 2: ' + x))

branch = main.pipe(
    # do something else
)

branch.subscribe(lambda x: print(' Branch Subscriber 1: ' + x))
branch.subscribe(lambda x: print(' Branch Subscriber 2: ' + x))

source.on_next('Hey')
```

Above code prints:
```
Main pipeline: Hey
 Main Subscriber 1: Hey
Main pipeline: Hey
 Main Subscriber 2: Hey
Main pipeline: Hey
 Branch Subscriber 1: Hey
Main pipeline: Hey
 Branch Subscriber 2: Hey
```

I was expecting the main pipeline to run only once per `on_next`, and populate Observers and branches sequentially, like:
```
Main pipeline: Hey
 Main Subscriber 1: Hey
 Main Subscriber 2: Hey
 Branch Subscriber 1: Hey
 Branch Subscriber 2: Hey
```

Is there a way to make it work as such?

**Comment by MainRo** [comment]
Your code works as expected. Each time you subscribe to an Observable, then the while operator chain is subscribed and processed. So in your example, since there are 4 subscription, your main is processed 4 times. If you want this to happen only once, then you must make this operator *hot*, i.e. multicast it. Several operators allow to do this. They are all based on publish and connect. This should work as you expect:

```
source = Subject()

main = source.pipe(
    # do something
    operators.do_action(lambda x: print('Main pipeline: ' + x)),
    operators.publish()
)

main.subscribe(lambda x: print(' Main Subscriber 1: ' + x))
main.subscribe(lambda x: print(' Main Subscriber 2: ' + x))

branch = main.pipe(
    # do something else
)

branch.subscribe(lambda x: print(' Branch Subscriber 1: ' + x))
branch.subscribe(lambda x: print(' Branch Subscriber 2: ' + x))

main.connect()
source.on_next('Hey')
```

**Comment by mecton** [comment]
Hi MainRo, thank you very much for your answer, it's exactly what I was looking for.
Is there a reason why it is not the default behavior? That is a bit counter intuitive to me, maybe because I represent the pipeline like a tree, where each node is an operation, and the result is given to the children sequentially.

**Comment by MainRo** [comment]
The default behavior of ReactiveX observable is called "cold" observables. This means that each subscription runs a new instance of the observable. This was a design choice of ReactiveX, and all implementations follow this behavior. There are other libraries that are hot by default (I think that javascript xstream works this way).
