### ISSUE TITLE
Use accumulator object for next iteration if acc in reduce returns None

### ISSUE THREAD

**Issue by freelancer1845** [ReactiveX/RxPY#513]
I'm trying to use a simple [] as accumulator object but since [].append(...) returns None I can't really use the function.

Maybe it would be nice to use the accumulator object again if t he lambda returns None.

```python
import rx
import rx.operators

result = rx.from_iterable(range(10)).pipe(
    rx.operators.reduce(lambda acc, a: acc.append(a), seed=[])
).run()

print(result.data)
```

**Comment by MainRo** [comment]
The reduce operators mandates that the accumulator returns the new state. This is how all reduce implementations work. However in your case, you can simply concatenate the list with a new one:

```python
import rx
import rx.operators

result = rx.from_iterable(range(10)).pipe(
    rx.operators.reduce(lambda acc, a: acc + [a], seed=[])
).run()

print(result.data)
```

**Comment by freelancer1845** [comment]
Allright, thanks a lot.
One other thing, can go in to an new Issues:
Is there sth. like a global error handler/default error handler planned or does it already exists? Just to make it simpler to debug code.

**Comment by MainRo** [comment]
With the run operator, if any error occurs, then an exception is raised. If instead of run you use subscribe, then you can register an error callback. There are also several operators that allow to deal with errors, such as catch and retry.
