### ISSUE TITLE
Type hint support question

### ISSUE THREAD

**Issue by Carsten-Leue** [ReactiveX/RxPY#514]
I am running 
```
Python 3.8.2
```

```pip show rx
Name: Rx
Version: 3.1.0
Summary: Reactive Extensions (Rx) for Python
Home-page: http://reactivex.io
Author: Dag Brattli
Author-email: dag@brattli.net
License: MIT License
Location: XXX
Requires:
Required-by:
```

I would like to use the rx library using python type hints. My very simple attempt:

```py
from unittest.case import TestCase
from rx.subject import BehaviorSubject
from rx import Observable


class TestCounter(TestCase):

    def test_typing(self):

        sub = BehaviorSubject[int](1)

        sub.on_next(10)

        ob: Observable[int] = sub
```

This does not run and fails with:
```
TypeError: <class 'rx.subject.behaviorsubject.BehaviorSubject'> is not a generic class
```

When I remove the generics (`[int]`) from the type hints then the code runs but my type checker does not detect that `BehaviorSubject` is actually a subject of integers.  Also it would not detect that `ob` is an observable of integers.

The other difficulty I have is when trying to declare a type that represents an operator function. To my best knowledge this should be:

```py
from typing import Callable, TypeVar

from rx import Observable

T1 = TypeVar('T1')
T2 = TypeVar('T2')
Operator = Callable[[Observable[T1]], Observable[T2]]
```

I would expect this to declare a function that accepts an observable of type `T1` and returns an observable of type `T2`.
But running this gives:

```
TypeError: <class 'rx.core.observable.observable.Observable'> is not a generic class
```

I also tried to import `Observable` from `rx.core.typing` since that version is generic. But this does not help either, because that version of `Observable` does not define the `pipe` method. Also a deep import does not seem to be appropriate.

Could you please point me to examples that show how to use RxPY with type hints and proper generics support.

**Comment by jcafhe** [comment]
Hi,
after some testing, I believe generics are not suported in Observable, Subject, etc, despite the fact that a generic class is declared in rx/core/typing.  

I think the idea here was to have 2 different Observable declarations, one for typing and one for running, like `list`/`tuple` and `List`/ `Tuple` in python typing module. This is failing or is not convenient because as you said, there are too much differences between `rx.Observable` and `rx.core.typing.Observable` (signatures, missing methods, etc).

A possible solution would be to make the "running" `Observable` a generic class. That would allow the subscribe callbacks to be parametrized  (especially `on_next`). Also a change in pipe overloads would propagate types through the chain of operator. i.e. for the overload with 2 operators :
```python
class Observable(typing.Observable):
    ...

    @overload
    def pipe(self,  
             op1: Callable[['Observable'], A],
             op2: Callable[[A], B]) -> B:
```
would be changed into: 
```python
class Observable(typing.Observable[T]):
    ...

    @overload
    def pipe(self,
             op1: Callable[['Observable[T]'], 'Observable[A]'],
             op2: Callable[['Observable[A]'], 'Observable[B]']) -> 'Observable[B]':
```
 
Also it would be necessary to add generics to every subclasses of Observable, to Subject and its subclasses, Observer, ... and more importantly to **all operators**.

Please feel free to share your thoughts on this.

**Comment by sobolevn** [comment]
From my experience this does not work:

```python
def pipe(self,
             op1: Callable[['Observable[T]'], 'Observable[A]'],
             op2: Callable[['Observable[A]'], 'Observable[B]']) -> 'Observable[B]':
```

We had to write an infrence plugin to support this annotation in `returns`. Because `lambda` and generic functions won't work without this hack: https://github.com/dry-python/returns/blob/master/returns/contrib/mypy/_features/pipe.py

**Comment by izmailoff** [comment]
Looks like this has been fixed already in Rx==3.2.0.

I'm able to do this in Python 3.7 without any issues from runtime or Pycharm:
```
from rx import operators as Observable

source: Observable[int] = rx.interval(1)
```

**Comment by Carsten-Leue** [comment]
@izmailoff in vscode this is showing errors (python 3.8):

![image](https://user-images.githubusercontent.com/55989662/131501033-aef57fc9-596d-486c-a75f-56ddbec0a524.png)

![image](https://user-images.githubusercontent.com/55989662/131501317-1cf93464-1403-45e3-8adc-54ad5cddc0b7.png)

![image](https://user-images.githubusercontent.com/55989662/131501368-1f8801ac-6a4d-44ec-b9f2-616b9245a71c.png)


This code actually works for me:

```python
import rx
from rx.core.typing import Observable

source: Observable[int] = rx.interval(1)
```

but it's not helpful because:
- the return value of `rx.interval` does not return a templated return value. This means you have to hardcode the template type manually, leading to potential issues
- there is no `pipe` method on the obserable returned by `rx.core.typing`. So I cannot do any meaningful operation on it.

**Comment by izmailoff** [comment]
> @izmailoff in vscode this is showing errors (python 3.8):
> 
> ![image](https://user-images.githubusercontent.com/55989662/131501033-aef57fc9-596d-486c-a75f-56ddbec0a524.png)
> 
> ![image](https://user-images.githubusercontent.com/55989662/131501317-1cf93464-1403-45e3-8adc-54ad5cddc0b7.png)
> 
> ![image](https://user-images.githubusercontent.com/55989662/131501368-1f8801ac-6a4d-44ec-b9f2-616b9245a71c.png)
> 
> This code actually works for me:
> 
> ```python
> import rx
> from rx.core.typing import Observable
> 
> source: Observable[int] = rx.interval(1)
> ```
> 
> but it's not helpful because:
> 
>     * the return value of `rx.interval` does not return a templated return value. This means you have to hardcode the template type manually, leading to potential issues
> 
>     * there is no `pipe` method on the obserable returned by `rx.core.typing`. So I cannot do any meaningful operation on it.

Indeed there is a problem that there are 2 Observable declarations one with `pipe` and one without. I've noticed that later after I posted. So we can still type hint but we have to chose whether we want to annotate `Observable[MyType]` or have `pipe` recognized. More improvements needed.

**Comment by dbrattli** [comment]
This is fixed in the latest --pre release and will be fixed in the latest major release
