### ISSUE TITLE
Support mypy

### ISSUE THREAD

**Issue by Carsten-Leue** [ReactiveX/RxPY#515]
Why I run [mypy](http://mypy-lang.org/) on my project that uses `rx` I get the following kind of errors:

```
Skipping analyzing 'rx': found module but no type hints or library stubs
Skipping analyzing 'rx.subject': found module but no type hints or library stubs
Skipping analyzing 'rx.operators': found module but no type hints or library stubs
```

and the recommendation https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports to ask the maintainer to support type hints, what this issue is about.

**Comment by MichaelSchneeberger** [comment]
I notices that as well.

This mypy error messages can also be avoided by adding *py.typed* (see [PEP 561](https://www.python.org/dev/peps/pep-0561/)) to the package instead of providing the stups files. This has actually be done for rxpy (see [here](https://github.com/ReactiveX/RxPY/blob/master/rx/py.typed)), but somehow it hasn't been transferred to the RxPY package yet.

**Comment by frederikaalund** [comment]
> This mypy error messages can also be avoided by adding py.typed (see PEP 561) to the package instead of providing the stups files. This has actually be done for rxpy (see here), but somehow it hasn't been transferred to the RxPY package yet.

Furthermore, it seems like it was the intention to include `py.typed` in the package. From [setup.py](https://github.com/ReactiveX/RxPY/blob/master/setup.py#L61):
```python
    package_data={'rx': ['py.typed']},
```

Maybe the `package_data` argument isn't working as expected? There generally seems to be [some confusion about the `package_data` argument](https://stackoverflow.com/a/14159430/554283). I know that I've had difficulties getting `package_data` to "behave" in the past.

**Comment by CarstenLeue** [comment]
I did some testing and it looks like the file `py.typed` is not included in the package because it's empty. Try to add some content to it, e.g. 

```
# Marker file for PEP 561.  The mypy package uses inline types.
```
I would also suggest to add one `py.typed` file per sub-module, not just top level. Make sure to explicitly list these files in `setup.py`.

**Comment by CarstenLeue** [comment]
Also I think according to https://mypy.readthedocs.io/en/stable/installed_packages.html it should read `zip_safe=False`:

https://github.com/ReactiveX/RxPY/blob/master/setup.py#L42

**Comment by jcafhe** [comment]
Hi,
after some checks and for whatever reason, it appears that `py.typed` is not included in tarball used as source distribution, but it is included in wheel dist. It seems that including this file in `MANIFEST.in` should do the trick.  Thanks :+1:
