### ISSUE TITLE
Update Getting Started Tutorial: No more observer class to import

### ISSUE THREAD

**Issue by rheophile10** [ReactiveX/RxPY#517]
see attached image from 
https://github.com/ReactiveX/RxPY/blob/develop/notebooks/Getting%20Started.ipynb

![image](https://user-images.githubusercontent.com/60486447/82958991-f9d89e80-9f73-11ea-976f-9573c937f30f.png)

There is no more Observer class to import

**Comment by MainRo** [comment]
The notebooks example have not been updated. We wanted to rework them with v3 release but this is still not done.
This is related to #265

**Comment by dbrattli** [comment]
This works with the latest --pre release and will be fixed in the next major release:

```py
>>> from reactivex import Observable, Observer
>>> 
```
