### ISSUE TITLE
Misleading example in 'defer' docstring

### ISSUE THREAD

**Issue by freelancer1845** [ReactiveX/RxPY#518]
The example in the 'defer' docstring

```python
rx.defer(lambda: rx.of(1,2,3)).subscribe()
```

gives the impression that the 'factory' method takes no parameter.

This works fine if you use subscribe to 'execute' the observable sequence.

But

```python
rx.defer(lambda: rx.of(1)).run()
```

throws an exception since run() wants to pass the scheduler to the lambda.

For me it feels a little inconsistent (although useful) that you can get away with a lambda that doesn't take a scheduler as argument, so I'm not sure if updating the docstring is enough.

Also the exception thrown may be a little confusing. Inspecting the callback and throwing an exception describing the problem might be more helpful for new users.

**Comment by MainRo** [comment]
actually the example from the documentation also throws an exception. The factory function is always called with the scheduler parameter. So we should update the documentation.
