### ISSUE TITLE
Buffer losing/ignoring items

### ISSUE THREAD

**Issue by darrickyee** [ReactiveX/RxPY#520]
I don't know if this is an issue or my own misunderstanding, but:

I have a Subject that can be called to emit items via `on_next()`.  The Subject's observers may themselves call `on_next()` on the Subject.  If an observer does so, the usual behavior is for the Subject to emit the item immediately, so that the observer gets called recursively.

Instead, I want the observers to handle items in the order that the Subject receives them, so that any nested `on_next()` calls are "appended" to the END of the Subject's item list, instead of causing the Subject to immediately emit them.

I thought a buffer would be appropriate for this, but it doesn't work the way I expected.  Here is an example:

````
import rx.operators as op
from rx.subject import Subject

sender = Subject()
closer = Subject()

# Buffer should close whenever `closer` emits an item
events = sender.pipe(op.buffer(closer))

# Call this to close buffer & print notification
def close():
    print('Buffer closed')
    closer.on_next(True)


def process(buffer):
    print(buffer)
    for num in buffer:
        print(num)
        if num < 5:
            # Should add item to the next buffer?
            sender.on_next(num+5)
    close()


events.subscribe(process)
# Log everything the Subject receives
sender.subscribe(lambda i: print(f'Sender received {i}'))

for i in range(3):
    sender.on_next(i)
close()
````

I was expecting this to happen:
1. `for` loop sends three items to the Subject, `sender`, and then `close()` is called
2. `sender` emits the list of items due to the call to `close()`
3. `process` prints the received list [0, 1, 2], then for each item, it prints the item (integer) and tells `sender` to emit another item
4. After looping through the items, `process` sends `close()`
5. `sender` sends another item list [5, 6, 7] to `process`

It seems steps 1-4 happen correctly, but after `process` calls `close()`, the buffer is empty.  Here's the output:

````
Sender received 0
Sender received 1
Sender received 2
Buffer closed
[0, 1, 2]
0
Sender received 5
1
Sender received 6
2
Sender received 7
Buffer closed
````

You can see that `sender` is in fact receiving the items emitted by `process`, but there's no buffer emitted after the second `close()`.  After the second "Buffed closed" I would expect the output to show a buffer of [5, 6, 7] and then to print 5, 6, 7 on successive lines.

Is there something I'm doing wrong here?  I have a feeling the problem might be due to garbage collection of the `num+5` values emitted from inside `process`.  If instead of calling `sender.on_next()`, I add the items to a global list, then define `close()` to call `sender.on_next()` with the list contents (and clear the list), it works as expected - possibly because the emitted items are "kept alive" after executing exits `process`?

But I would expect `buffer` to have that behavior without having to "manually" keep references alive.  Or is that not how it should be expected to work?

**Comment by darrickyee** [comment]
Still interested in this, if anyone's available to answer...

**Comment by MainRo** [comment]
On this code, the operators form a cycle graph. The process function is called when the buffer operator emits its first item. So process is called in the context of the on_next callback of the buffer operator. In this case the internal flat_map of the buffer operator cannot subscribe before the other items are emitted. 
On solution could be to schedule the emissions of process later (after process exits).

But there is another part in your expectation that may not work this way in a real example. In step 3 you describe [0, 1, 2] as a list, but they are emitted independently from each other. If you consider a source observable that emits lists, then the problem may be simpler.
Here is a sample code where [0, 1, 2] is emited as a single item:

``` python
source = rx.just([0, 1, 2])
feedback = Subject()

output = rx.merge(source, feedback).pipe(
    ops.publish(),
)

disposable1 = output.pipe(
    ops.flat_map(lambda i: rx.from_(i))
).subscribe(
    on_next=lambda i: print("on_next: {}".format(i)),
    on_completed=lambda: print("on_completed"),
    on_error=lambda e: print("on_error: {}".format(e))
)

disposable2 = output.pipe(
    ops.flat_map(lambda i: rx.from_(i).pipe(
        ops.filter(lambda i: i < 5),
        ops.map(lambda i: i + 5),
        ops.to_list(),
    ))
).subscribe(feedback)

output.connect()

disposable1.dispose()
disposable2.dispose()
print("Done!")
```

It all depends how the source items should be grouped.

**Comment by darrickyee** [comment]
Thanks - yes, my current solution is to store the "events" in a global list, then emit and clear the list as needed.  I guess this is not a bug.
