### ISSUE TITLE
zip operator should complete if a single upstream source completes

### ISSUE THREAD

**Issue by MichaelSchneeberger** [ReactiveX/RxPY#525]
The following observable `y` ...

``` python
import rx
from rx import operators as rxop

y = rx.range(2).pipe(
    rxop.zip(rx.defer(lambda _: y)),
    rxop.merge(rx.just(0)),
    rxop.share(),
)

y.subscribe(print, on_completed=lambda: print('completed'))
```

... never completes.

My suggestion: The zip operator should complete if any upstream source completed and the corresponding queue is empty.

That is how it is implemented in [RxJava](https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableZip.java).

**Comment by MainRo** [comment]
I agree that zip should complete in such cases, because no item will be emitted after one source completes. Some applications may use the current behavior to wait for all streams to complete, but probably most people expect it to complete immediately.

**Comment by hoc081098** [comment]
Hi @MichaelSchneeberger, I created a PR #537
