### ISSUE TITLE
Mypy reports "Module 'rx' has no attribute 'Observable'" since 3.1.1

### ISSUE THREAD

**Issue by mysticfall** [ReactiveX/RxPY#531]
I don't know what has changed, but after I updated to RxPy 3.1.1, mypy began to report such errors as "Module 'rx' has no attribute 'Observable'", possibly due to python/mypy/issues/7423.

It happens for all other major types such as `BehaviorSubject`, and changing `[mypy] implicit_reexport` in `setup.cfg` to `True` fixes the symptom.

**Comment by jcafhe** [comment]
I guess this is related to #524, for fixing #515. Before 3.1.1, rx was maybe silently unsupported in your project?

**Comment by mysticfall** [comment]
@jcafhe I think what you suggested could be entirely possible since my project is just two weeks old, so it didn't have too much code before 3.1.1.

**Comment by dbrattli** [comment]
This should be fixed in the latest --pre release and will be fixed in the next major release
