### ISSUE TITLE
Nested flat_map example not working

### ISSUE THREAD

**Issue by malibu1966** [ReactiveX/RxPY#532]
Hi there, I am really trying to understand multiprocessing versus sequential processing so I am trying to follow [this youtube example.](https://www.youtube.com/watch?v=p7upvc5xcOs)  The gist of the example is when he does a query with a delay using a single flatmap, it runs in 8 seconds but when he uses a window() to compress the emissions then use a nested flatmap it runs all windows at once.  I have mostly been able to make the demo work except my two nested flat_maps are not compressing the run time of the script and it still runs in 8 seconds.  Is this a bug or am I doing something wrong?  Also I am open to the idea that this may be a GIL issue, in which case my honeymoon with python is over unless there is a workaround.

I would really like to understand this, since my primary motivation for using reactive techniques are to provide an elegant way to accelerate many long running web calls.  According to the output there are 4 CPUs on the machine I am executing on, therefore there are 4 threads created.  Each window should run on a separate thread and thus take closer to 2 seconds than to 8.  Output is clearly coming out sequentially still.  Here is my demo code (that should run in around 2 seconds but takes 8):

```
import concurrent.futures
import time
from threading import Thread
import rx
from rx import operators as ops, Observable
import multiprocessing
from rx.scheduler import ThreadPoolScheduler

bg_scheduler = ThreadPoolScheduler(multiprocessing.cpu_count())
print("CPUS:",multiprocessing.cpu_count())

empIds = ["1","2","3","4","5","6","7","8"]

def get_employee_details(id):
    employees = {
        "1":"A",
        "2":"B",
        "3":"C",
        "4":"D",
        "5":"E",
        "6":"F",
        "7":"G",
        "8":"H",
    }
    time.sleep(1)
    return employees[id]

rx.from_(empIds,bg_scheduler).pipe(
    ops.observe_on(bg_scheduler),
    ops.subscribe_on(bg_scheduler),
    ops.window_with_count(2),
    ops.do_action(lambda x: print(x)),
    ops.flat_map(lambda identifiers: identifiers.pipe( ops.flat_map(lambda id: get_employee_details(id)) )),
).subscribe(
   on_next = lambda i: print("Check Got - {}".format(i)),
   on_error = lambda e: print("Error : {0}".format(e)),
   on_completed = lambda: print("Job Done!"),
)

time.sleep(60)

```
Here is my pip freeze.  This is actually a demo that I'm running under the env for a wxpython application:

altgraph==0.17
certifi==2020.6.20
chardet==3.0.4
et-xmlfile==1.0.1
future==0.18.2
idna==2.10
jdcal==1.4.1
keyring==21.2.1
numpy==1.19.0
openpyxl==3.0.4
pefile==2019.4.18
Pillow==7.2.0
pyinstaller @ https://github.com/pyinstaller/pyinstaller/archive/develop.zip
pyinstaller-hooks-contrib==2020.5
pywin32==228
pywin32-ctypes==0.2.0
requests==2.24.0
Rx==3.1.0
six==1.15.0
urllib3==1.25.9
wxPython==4.1.0

**Comment by MainRo** [comment]
The key information in the thread schedulers (ThreadPool and NewThread) is that the Observables are bound to a thread at subscription time. So if your want to schedule each item in a thread of the threadpool, then you must create an observable for each of them. Here is an example that should do what you want:

```python
import concurrent.futures
import time
from threading import Thread
import rx
from rx import operators as ops, Observable
import multiprocessing
from rx.scheduler import ThreadPoolScheduler


print("foo")
bg_scheduler = ThreadPoolScheduler(multiprocessing.cpu_count())
print("CPUS:",multiprocessing.cpu_count())

empIds = ["1","2","3","4","5","6","7","8"]

def get_employee_details(id):
    employees = {
        "1":"A",
        "2":"B",
        "3":"C",
        "4":"D",
        "5":"E",
        "6":"F",
        "7":"G",
        "8":"H",
    }
    time.sleep(1)
    return employees[id]

rx.from_(empIds,bg_scheduler).pipe(
    ops.do_action(lambda x: print(x)),
    ops.flat_map(lambda identifiers: rx.just(identifiers, scheduler=bg_scheduler).pipe(
        ops.flat_map(get_employee_details),
    )),
).subscribe(
   on_next = lambda i: print("Check Got - {}".format(i)),
   on_error = lambda e: print("Error : {0}".format(e)),
   on_completed = lambda: print("Job Done!"),
)

time.sleep(60)
```

I removed the windowing part for clarity (I am not sure if you used them because you need them or because it was in the tutorial).

**Comment by malibu1966** [comment]
Thank you for your time to answer.  I had windows in the original question because the objective is to take a series of emissions and batch them into windows with each window being processed on a separate Thread.  I am not sure if this answers the question; the just() will cause all items to be processed at once, no?

**Comment by MainRo** [comment]
If you want to schedule each window in its own thread, then you can just use observe_on each window observable. Here is you initial example:

```python
import concurrent.futures
import time
from threading import Thread
import rx
from rx import operators as ops, Observable
import multiprocessing
from rx.scheduler import ThreadPoolScheduler


bg_scheduler = ThreadPoolScheduler(multiprocessing.cpu_count())
print("CPUS:",multiprocessing.cpu_count())

empIds = ["1","2","3","4","5","6","7","8"]

def get_employee_details(id):
    print(id)
    employees = {
        "1":"A",
        "2":"B",
        "3":"C",
        "4":"D",
        "5":"E",
        "6":"F",
        "7":"G",
        "8":"H",
    }
    time.sleep(1)
    return employees[id]

rx.from_(empIds).pipe(
    ops.window_with_count(2),
    ops.flat_map(rx.pipe(
        ops.observe_on(bg_scheduler),
        ops.flat_map(lambda id: get_employee_details(id)),
        #ops.map(get_employee_details),
    )),
).subscribe(
   on_next = lambda i: print("Check Got - {}".format(i)),
   on_error = lambda e: print("Error : {0}".format(e)),
   on_completed = lambda: print("Job Done!"),
)

time.sleep(10)
```

Also, since the last flat_map is blocking (on time.sleep), you can use map directly.
