### ISSUE TITLE
Implementation of feedback loops

### ISSUE THREAD

**Issue by jruizaranguren** [ReactiveX/RxPY#538]
We would like to model a problem having classes A(Subject), B(Subject), C(Observer)

A.subscribe(B)
B.subscribe(C)
B.Subscribe(A) # Feedback loop

Wwe would like to subscribe A to some events of B so some internal status of A is changed. The problem is that `_on_next_core` of B is handling both events generated by B and events received by B from C. In fact, this happens to any subject A that we would like to use in the form `A.subscribe(B)` if we want to implement custom logic in `_on_next_core` but at the same time being able to add own generated messages.

Is there any more elegant solution to this problem than filtering messages by type in `_on_next_core`?

**Comment by MainRo** [comment]
Maybe more details you help in understanding your issue. From the graph that you describe, b will effectively receive events from C and A. You can filter message with the filter operator, e.g. before B subscribes to A:


    C-->B-->A-->filter-->|
       /\                |
       |_________________|

**Comment by jruizaranguren** [comment]
The issue is that each object inherits from `Subject`. According to the documentation in that base class, we can override the method `_on_next_core`, but that method will be used in the following both cases:

- when B receives a new event coming from `C` or `A`.
- when B calls `on_next` in order to publish a new event that will be targeted to `A`.

**Comment by MainRo** [comment]
I am not sure that I understand your problem correctly. From the initial message, the graph seems to be:

```
C-->B-->A-->|
   /\       |
   |________|
```

You want to handle events emitted from C differently from the ones emitted - internally - by B ? If yes, then you need a way to differentiate these events either by type, either with a field (for example you can add the id of the source).

**Comment by dbrattli** [comment]
Closing for now. Please feel free to continue the discussion in Discussions tab
