### ISSUE TITLE
PyPI package not updated

### ISSUE THREAD

**Issue by jdreaver** [ReactiveX/RxPY#54]
Version 1.2.2 has been out for almost 2 months, but PyPI still only has version 1.2.1. Could someone with the power to do so update the PyPI version of Rx? @ardoramor made note of this in #50 but I decided to make a separate issue in case his message was buried. Thanks in advance!

**Comment by dbrattli** [comment]
Sorry, we have long summer holidays in Norway. But I'm back and have just uploaded a new version 1.2.3 to PyPI.

**Comment by jdreaver** [comment]
Awesome, thanks a lot!
