### ISSUE TITLE
Getting a traceback for exception raised in operator

### ISSUE THREAD

**Issue by rsaymore** [ReactiveX/RxPY#545]
How can I structure my code for easy debugging? I have an operator that fails but I can't get rxpy to provide a stack trace, which requires me to do a lot of work to hunt down the location of the error. Here is a simple example:
```python
import rx
from rx import operators as op

def add1(x):
    if x==3:
        raise RuntimeError("Exception raised at unknown location")
    return x+1

def to_string(x):
    return str(x)

rx.from_iterable(range(10)).pipe(op.map(add1), op.map(to_string)).subscribe(
    on_completed=lambda: print("success"), on_error=lambda e: print(e)
)
```
Running this simply prints `Exception raised at unknown location` with no additional information. Of course, in this example it's obvious on what line the error occurs. But is there a simple way to get a traceback for any exception that occurs in any operator?

**Comment by MainRo** [comment]
The traceback module is very helpful to track exceptions:

```
import traceback
import rx
from rx import operators as op

def add1(x):
    if x==3:
        raise RuntimeError("Exception raised at unknown location")
    return x+1

def to_string(x):
    return str(x)

rx.from_iterable(range(10)).pipe(op.map(add1), op.map(to_string)).subscribe(
    on_completed=lambda: print("success"), 
    on_error=lambda e: traceback.print_tb(e.__traceback__)
)
```
This gives the location where the exception has been raised:
```
$ python rxpy/issue_545.py
  File ".../RxPY/rx/core/operators/map.py", line 37, in on_next
    result = _mapper(value)
  File "rxpy/issue_545.py", line 7, in add1
    raise RuntimeError("Exception raised at unknown location")
```

**Comment by MainRo** [comment]
btw I often use a "trace" operator for bug hunting on non-trivial applications:

https://github.com/MainRo/cyclotron-py/blob/master/cyclotron/debug/trace.py

**Comment by rsaymore** [comment]
I see, thanks!
