### ISSUE TITLE
learn events in rxpy

### ISSUE THREAD

**Issue by ricardo5987** [ReactiveX/RxPY#549]
i am trying to learn rxpy to work with events in jinja2. but the tutorials I found only show how to interact lists. For example how do I change the text of an element each time I click a button? or do I change the value of a variable by applying a series of operations? just like react js does

**Comment by MainRo** [comment]
Can you be more specific? AFAIK jinja2 is only a template engine so I suppose that you use it within a web framework like Django?

**Comment by stefaneidelloth** [comment]
Might be related:
https://github.com/ReactiveX/RxPY/issues/553

**Comment by dbrattli** [comment]
Closing this for now. Please use the discussions tab to discuss this further.
