### ISSUE TITLE
piece of backpressure code

### ISSUE THREAD

**Issue by p4l1ly** [ReactiveX/RxPY#552]
I have saved from eternal oblivion a simple reusable piece of backpressure code that is being deleted in a project. I'm giving it another chance. You might find it useful and maybe mix it into this repo or start a separate library project from it. Or you might condemn it for good; without causing me any psychical harm :)

https://github.com/p4l1ly/rxpy_backpress/blob/master/rxpy_backpress.py

a simple example of use is in `test_backpress.py`

I may create a merge request if you decide to put it somewhere.

**Comment by MainRo** [comment]
Thanks for the drop. I am not sure if we will integrate it: Backpressure has been removed from rxpy so that alternative libraries can fully focus on this large topic.
Probably this would fit in the doc
