### ISSUE TITLE
Support for observable collections?

### ISSUE THREAD

**Issue by stefaneidelloth** [ReactiveX/RxPY#553]
I am looking for an implementation of observable collections / sequences in Python (similar to observable collections in [.Net](https://www.codeproject.com/articles/1004644/observablecollection-simply-explained) or [JavaFx](https://docs.oracle.com/javafx/2/collections/jfxpub-collections.htm#CIHEJJFH)), also see

https://stackoverflow.com/questions/65940026/recommented-way-to-implement-observable-collections-in-python/65951966#65951966

I found an implementation of observable collections in Python that is based on RxPy:
https://github.com/shyam-s00/ObservableCollections

However, it seems to be outdated/not ready for RxPy 3.x:
https://github.com/shyam-s00/ObservableCollections/issues/1

I am new to RxPy. Do I miss some syntax/concept that could be used to get change events *after* declaring a subscription? 
Does it make sense at all to try to use RxPy sources as observable collections?

Is the above project the right way to go or

**=> Are there plans to natively support / standardize observable collections in RxPy?**

Example code

```
from reactive.ObservableList import ObservableList

ol = ObservableList([1, 2, 3, 4])
ol.when_collection_changes() \
    .map(lambda x: x.Items) \
    .subscribe(print, print)

ol.append(5)  # <= adds item *after* subscription
```

Maybe RxPy could even provide observable DataFrames. Also see

https://stackoverflow.com/questions/62671185/how-to-make-tables-spreadsheets-e-g-pandas-dataframe-observable-use-triggers

**Comment by dbrattli** [comment]
Thanks for the suggestion. This will not be added to RxPY (since it cannot contain everything), but could be added to another library as the one you mention. Please ask there, add PRs or fork that library.
