### ISSUE TITLE
Change name of subject methods on_next, on_error, on_completed() to next(), error(), complete()

### ISSUE THREAD

**Issue by jxraynaud** [ReactiveX/RxPY#556]
I found it completely confusing to have the method allowing to 'push' a new value into a Subject being call on_next().
on_next() method intuitively represents what's the object does when a next event occurs. Honestly if I didn't know rxjs very well I would never have guessed that on_next() shall be used to push new value, on_error() to emit an error and on_completed() to complete the Subject. And I only guessed it because the complete(), error() and next() methods didn't exists in the documentation.

For backward compatibility, it's quite simple to maintain both names for the same method for a while.

**Comment by dbrattli** [comment]
This is the legacy from [Reactive Extensions (Rx)](https://github.com/dotnet/reactive). RxPY is a port of Rx so we keep the naming. The proper names for Python is probably `send`, `throw`, and `close` to align with the enhanced generator interface ([PEP-342](https://www.python.org/dev/peps/pep-0342/)). I btw did this for [aioreactive](https://github.com/dbrattli/aioreactive).

**Comment by jxraynaud** [comment]
@dbrattli thanks for your answer. And I love send/throw/close.
I'm currently looking at aloreactive. Very interesting. Thx for your work on both RxPy and aloreactive.
