### ISSUE TITLE
Move discussion channel from slack to github discussion

### ISSUE THREAD

**Issue by MainRo** [ReactiveX/RxPY#557]
This is a proposal: The current official discussion channel for RxPY is on slack. However posts are rare there, and answers are often quite long. On the other way, many people use the Github issues to ask for questions (much more than on slack!). 
It may be more natural to use GitHub discussions for this.

**Comment by MainRo** [comment]
Thanks @dbrattli !
I can update the readme accordingly to favor GitHub discussions over the slack channel.

**Comment by dbrattli** [comment]
@MainRo I already did some changes to the readme. Please feel free to add more info.
