### ISSUE TITLE
Immediate variant of generate_with_relative_time

### ISSUE THREAD

**Issue by Synthetica9** [ReactiveX/RxPY#559]
(I have asked this question on the Slack as well, but the solution might be useful to other people too.)

I ran into an issue where `generate_with_relative_time` ostensibly did what I wanted it to do, but instead of directly "yielding" the result of any given step, it is first delayed by the delay specified in time_mapper, which made it less useful for my use-case.

I have since made a work-around, but this feels clunky at best:

```python
def generate_with_relative_time_direct(initial_state, condition, iterate, time_mapper):
    State = namedtuple('State', 'state should_sleep')    

    return rx.generate_with_relative_time(
        State(initial_state, False),
        lambda x: condition(x.state),
        lambda x:
            State(x.state, True)
            if not x.should_sleep else
            State(iterate(x.state), False),
        lambda x:
            time_mapper(x.state) if x.should_sleep else 0
    ).pipe(
        ops.filter(lambda x: not x.should_sleep),
        ops.map(lambda x: x.state),
    )
```

Two questions:

1. Is this intended behaviour?
2. If yes, is the work-around presented here something we would want to include in the library itself?

**Comment by MainRo** [comment]
Just to be sure concerning your needs: Instead of a delay then emit behavior, you need a emit then delay behavior?
In this case, something like this should work:

```
rx.pipe(
    ops.start_with(initial_state),
    ops.generate_with_relative_time_direct(iterate(initial_state), condition, iterate, time_mapper),
)
```

This emits the first item directly and then continues with the delay+emit behavior.

**Comment by Synthetica9** [comment]
I don't really care about the initial delay, what I care about is that the output of iterate is being delayed longer than it needs to. 

For context: I use this to call an API that returns some relatively time-sensitive info. I want this info immediately, instead of first waiting for the delay imposed by time_mapper. Then, I want it to wait for a time imposed by time_mapper, and then I want to call the API again. (The return value of the API call determines how long I should wait for with the next call, so I can't just use `rx.interval`.

**Comment by MainRo** [comment]
ok so you need the item to be emitted immediately after iterate is called rather than after the delay has expired?

    iterate->emit->wait

instead of

    iterate->wait->emit

As you said this is not possible with the current implementation. We could add a parameter to specify which of both behaviors to use. However, it seems that the other implementations (rxjava et rxjs a least) removed this operator. So I wonder if we should add complexity to it or not (and plan to remove it in the future major release).
In your situation, I think that I would fork the operator's implementation in my project and modify it. It would be more readable than the workaround.
@dbrattli any opinion on this?

**Comment by dbrattli** [comment]
I don't think we can support every kind of behavior with RxPY. It's easy to extend or change the behavior for particular use-cases and everything do not need to end up in the library itself. Especially if it adds complexity to the code. Closing this issue as wont-fix.
