### ISSUE TITLE
Possible bug when using pausable on BehaviorSubject

### ISSUE THREAD

**Issue by jdreaver** [ReactiveX/RxPY#56]
I am using BehaviorSubjects all over the place my current GUI application, because they are an awesome way to store values and get updates. I have some situations where I use `.pausable()` when combining multiple streams of values. I do this because I update many of the streams at once, and I don't want to compute results in derived streams until all of the parent streams are updated. That is, I set the pausable to False, make updates to multiple streams, and then set the pausable to True.

I am encountering what I think is an error when I pause and immediately unpause without changing the value. Here is a sample script:

``` python
import rx


def normal_subject():
    pauser = rx.subjects.BehaviorSubject(True)
    subject = rx.subjects.Subject()
    subject.pausable(pauser).subscribe(print)
    subject.on_next("print value")

    print("Subject pause/unpause")
    pauser.on_next(False)
    pauser.on_next(True)


def behavior_subject():
    pauser = rx.subjects.BehaviorSubject(True)
    subject = rx.subjects.BehaviorSubject("print value")
    subject.pausable(pauser).subscribe(print)

    print("BehaviorSubject pause/unpause")
    pauser.on_next(False)
    pauser.on_next(True)


if __name__ == "__main__":
    print("Subject:")
    normal_subject()
    print("\nBehaviorSubject:")
    behavior_subject()
```

Here is the output:

```
$ python rx_pause.py 
Subject:
print value
Subject pause/unpause

BehaviorSubject:
print value
BehaviorSubject pause/unpause
print value
```

In the normal subject situation, the value is only printed once, right when `on_next` is called. When we pause and then unpause, the value is not printed again. In the BehaviorSubject version, the value is printed twice, the second time being when the pausable is paused then unpaused. **It is my understanding that both situations should produce the same output,** at least based off of the [RxMarbles](http://rxmarbles.com/#pausable) website.

My hunch is `pausable` is implemented using some sort of subscribe/unsubscribe mechanism. When used with BehaviorSubjects, the re-subscription causes the latest value to be emitted over again, **even though no values were emitted while paused**. I would think that `pausable` should be implemented by ignoring `on_next`, so values are simply ignored while paused, and we don't resubscribe when we unpause our stream. 

Again, _I'm not quite sure that this is a bug_, but it definitely feels unintended. I think that if two streams emit the same values into the same operator, we should get the same result.

**Comment by dbrattli** [comment]
Any chance of a repro of this in RxJS? The backpressure stuff has been directly ported from RxJS to Python, and they might have fixed bugs that haven't been ported to Python yet. I will have more time to look into this next weekend.

**Comment by jdreaver** [comment]
I looked through the RxJS implementation ([here is the file](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/pausable.js)) and everything looks the same. They also haven't updated that file since December of last year.

I think the root of the problem is using `connect` after unpausing. Here is an example of using connect on a published BehaviorSubject:

```python
import rx

subject = rx.subjects.BehaviorSubject(1)
published = subject.publish()
published.subscribe(lambda x: print("published:", x))

print("before connect")
published.connect()
print("after connect")
```

And the output:

```
before connect
published: 1
after connect
```

For most streams, using `connect` in the pausable implementation seems fine: you just reconnect when we are unpaused. However, we can see from this example that when the source is a BehaviorSubject, then connecting will re-emit the value. That seems like correct behavior for a BehaviorSubject, but I guess my issue is `pausable` probably should not use connect in this way because of this corner case.

Again, I'm unsure if this is actually a bug, it just seems weird to me that unpausing a stream can result in emitting the latest value over again. I think of "unpause" as simply "stop blocking."

**Comment by dbrattli** [comment]
Looks like the side-effect you are seing is because `pausable` uses a `ConnectableObservable` under the covers, and will connect/dispose when pausing/unpause. Thus it will re-subscribe to the BehaviorSubject. A BehaviorSubject is basically a Replay1Subject and this is why it will replay its value on unpause. So the problem is that your `BehaviorSubject` is partly cold. You could make it hot by publishing the `BehaviorSubject`, thus isolating the (re-)subscribe of the `ConnectableObservable`.

```python
def behavior_subject():
    pauser = rx.subjects.BehaviorSubject(True)
    subject = rx.subjects.BehaviorSubject("print value")
    psubject = subject.publish()
    psubject.pausable(pauser).subscribe(print)
    psubject.connect()

    print("BehaviorSubject pause/unpause")
    pauser.on_next(False)
    pauser.on_next(True)
```
More info at http://davesexton.com/blog/post/Hot-and-Cold-Observables.aspx

Btw. another operator you should check out is `with_latest_from` which do not produce a combined result until the source sequence produces an element.

**Comment by jdreaver** [comment]
Thanks for the info! I think `pausable` was designed with hot observables in mind, and I don't want to fight the original design decision.

Here is an example of a `pausable` implementation that works for my use-case:

```python
import rx


@rx.internal.extensionmethod(rx.Observable)
def my_pausable(self, pauser):

    is_paused = [False]

    def pauser_on_next(_is_paused):
        is_paused[0] = _is_paused

    pauser.subscribe(pauser_on_next)

    parent = self

    def subscribe(observer):

        def on_next(value):
            if not is_paused[0]:
                observer.on_next(value)

        return parent.subscribe(on_next, observer.on_error,
                                observer.on_completed)

    return rx.AnonymousObservable(subscribe)


s = rx.subjects.BehaviorSubject(1)
pauser = rx.subjects.Subject()
paused = s.my_pausable(pauser)
output = []
paused.subscribe(output.append)
assert output == [1]

# About to pause. We will ignore the values emitted here.
pauser.on_next(True)
s.on_next(2)
s.on_next(3)
pauser.on_next(False)
assert output == [1]

# Normal output should work now
s.on_next(2)
assert output == [1, 2]
```

It works by simply not calling `on_next` if we are currently paused. I don't expect this will be used as an alternative to the current `pausable` implementation (which I don't even fully understand, I suppose), but I thought I would share it here in case anyone else stumbles upon a similar issue :smile: 

Funny enough, it turns out I *want* to re-emit the latest value after pausing sometimes. I made a variant of this implementation that handles this use case as well. Basically, I just check if any values were received while paused. If so, then I emit the latest one when I unpause.

Thanks for your help again!
