### ISSUE TITLE
observe_on and subscribe somewhat inconvenient

### ISSUE THREAD

**Issue by kormang** [ReactiveX/RxPY#565]
Hi everybody!

According to [these docs](http://reactivex.io/documentation/operators/observeon.html) on ObserveOn operator, everything that fallows should execute on provided scheduler. With implementation we have in RxPY, that is not the case. For example in this case:

```python
observables.pipe(observe_on(scheduler), delay(3.0)).subscribe(callback)
```

`callback` will be called in separate thread. As a matter of fact, each call to delay(), or any other operator that has to do something with time, will silently spawn new thread (they will be reused for emission to that delay operator, but call to delay function itself will cause new thread to be spawned). That is problem when you want everything to run on single thread, with some loop. You would have to provide scheduler to each operator, or silently create potential race condition or performance issues (and in case of `delay` and asyncio loop that didn't work until #564 ). Another option is to always pass `scheduler` parameter to `subscribe`. Which is not ideal either, as subscribers could be all over the code.

Another problem I see, is `scheduler` parameter of `subscribe` function. I've taken look at C++, Java, .Net, and JS implementations of Rx, and none of them have that parameter.

1. It is not clear what it does. Comment _scheduler: [Optional] The default scheduler to use for this subscription._ , doesn't really tell much. Is it suppose to do what `observe_on` does, or `subscribe_on`, or both, or something else?
2. I suppose everything it does can be accomplished using `observe_on` and `subscribe_on`, which is much more flexible.
3. In some way it conflicts with operators that accept scheduler, like `delay` or `observe_on`.

I that these two problem are related (`observe_on` not behaving as it should, and `subscribe` having scheduler argument).
Forgive me if I'm wrong, but I think this needs attention. I'm willing to cooperate to make this work.

I haven't checked how it is implemented in other languages, but this is first plan that comes to my mind:
1. Attach `scheduler` as a property (or something like that) to observable sequence (source), passed from `observe_on`. Anyway make  `scheduler` accessible to operators down the pipe. I suppose that operator that come after  `observe_on` could get the scheduler from source passed to them.
2. Leave everything **backward compatible**, but simple to reason about. If user passes  `scheduler` to `subscribe`, then internally do `source = source.pipe(observe_on)`. Additionally deprecate  `scheduler` argument.
3. Inside operators like `delay`, somehow **check** if scheduler that source runs on, is blocking, and if it is then we can have to options, block (which is probably what most users would not expect, and it would be backward incompatible), or create TimeoutScheduler as we do now. I'm not sure how to make this completely backward compatible, because first thing that comes to my mind is to add `is_blocking` abstract property to schedulers' super class.
4. Live happily ever after with possibility to create any scheduling scenario you like with `observe_on` and `subscribe_on`, and not worry about silently switching to another thread.

I am ready to collaborate on this one. Starting from discussion and splitting it to smaller tasks, to implementing required changes.

What do you think?

**Comment by dbrattli** [comment]
I think you have misunderstood how `observe_on` works.

> According to these docs on ObserveOn operator, everything that fallows should execute on provided scheduler

This is not correct. There is nothing in the docs that tells this. The docs says that `observe_on` will: "specify the Scheduler on which an observer will observe this Observable". That is different. In your example the `delay` operator will observe the upstream notifications being emitted on the given scheduler, but it needs to decide for itself what  scheduler to use (i.e it needs to schedule). The `observe_on` operator will notify using the given scheduler but it cannot instruct the downstream operators to use the same scheduler. Operators like `map` do not need a scheduler so it's notifications will be given on the same scheduled context as the upstream scheduler. Operators like `delay` need to know what scheduler to use and have no clue what the upstream scheduler is. Thus you need to tell `delay` what scheduler it should use. For RxPY you can supply the default scheduler to use for each operator in the `subscribe()` call, and yes this is different from other implementations of Rx.

**Comment by kormang** [comment]
I see. Thanks for clarification. It is true that non on the operators on the marble diagram in the docs need to schedule.

OK, sorry, I have rushed into Rx, started using it for a project without deeply studying it, especially best practices and things like that.

This is first time I use Rx in any language, and I'm used to use event loops inside threads. I see it very difficult to make sure no extra threads are created. As I see it right now, I'll have to pass schedulers all over the place, and make sure that I pass them to subscribe, delay and other functions. Is there some advice, or best practices that I could use to make code maintainable?

Also, I'll happily close this issue, I just need clarification about comment _scheduler: [Optional] The default scheduler to use for this subscription._. As I see from the code, `subscribe` passes `scheduler` upstream towards observable source, and as long as operators pass it further, everything will be observed on that scheduler, and even subscription function will execute on that scheduler as if `subscribe_on`is used (as long as subscription function respects scheduler argument).

What is reasoning behind adding `scheduler` argument, unlike other implementations?

**Comment by kormang** [comment]
Maybe I ask too much :) But I wonder why C++ implementation also uses current thread as default scheduler for delay:
https://github.com/ReactiveX/RxCpp/blob/master/Rx/v2/src/rxcpp/operators/rx-delay.hpp#L200

Although it blocks, and usually that is not what we want, spawning new threads by default seems dangerous to me. Python is not Haskell, I already got burned :)  (I was actually  expecting it to use my loop, but I understand now why it didn't).

**Comment by dbrattli** [comment]
The reason is that for some GUI frameworks e.g GTK, QT, Tkinter, Pygame, you would usually need to set the scheduler of every operator (that deals with time). It makes the code look bad and it's easy to forget. Most Rx implementations do not have this problem. For an example of usage see: https://github.com/ReactiveX/RxPY/blob/master/examples/timeflies/timeflies_tkinter.py

**Comment by kormang** [comment]
Thank you for the great answer.

I have encountered that problem my self, although I don't do GUI, but use asyncio loop. That also means you have to pass scheduler every time you subscribe. Is there any way to do it the way I thought `observe_on` should work?
For example like this:
```python
obs = src.pipe(schedule_on(scheduler))
```
Now you can pass observables around, and scheduler will be fixed (if not overridden). When you have whole graph of observables, and many  subscriptions in different files, it becomes inconvenient to pass scheduler along with observables.

I have also encountered another problem with asyncio (#567 ), maybe you could review it. Thanks.

**Comment by dbrattli** [comment]
Yes, it should be possible. Make the new operator and have it set the scheduler when it subscribes upstream.

**Comment by kormang** [comment]
Thanks. I'll close this issue now.
