### ISSUE TITLE
Deadlock in AsyncIOThreadSafeScheduler

### ISSUE THREAD

**Issue by kormang** [ReactiveX/RxPY#566]
Fallowing code produces deadlock:

```python
import rx
import rx.operators as ops
from rx.subject.subject import Subject
from rx.scheduler.eventloop import AsyncIOThreadSafeScheduler
import asyncio
import logging

def print_threads_traces(_):
    import traceback
    print("\n*** STACKTRACE - START ***\n")
    code = []
    for threadId, stack in sys._current_frames().items():
        code.append("\n# ThreadID: %s" % threadId)
        for filename, lineno, name, line in traceback.extract_stack(stack):
            code.append('File: "%s", line %d, in %s' % (filename,
                                                        lineno, name))
            if line:
                code.append("  %s" % (line.strip()))

    for line in code:
        print(line)
    print("\n*** STACKTRACE - END ***\n")

logging.basicConfig(
    level=logging.DEBUG,
    format='[%(threadName)s|%(levelname).5s|%(name).32s:%(lineno)d] %(message)s'
)

logger = logging.getLogger('repro')

loop = asyncio.get_event_loop()
scheduler = AsyncIOThreadSafeScheduler(loop)

src = Subject()

def log_and_push_another_one(msg):
    logger.info(msg)
    src.on_next(msg + "0")
    logger.info('Done')

# Two delays are needed to break the cycle of action self-rescheduling in delay.py.
# That will cause setting cancelable.disposable = mad, which will cause previous
# disposable to be disposed, which will cause scheduler to wait for confirmation,
# which causes deadlock.
obs = src.pipe(ops.delay(1.0, scheduler=scheduler), ops.delay(1.0, scheduler=scheduler))
obs.subscribe(log_and_push_another_one)

# After few seconds print stack trace of each thread, in another thread.
rx.of(1).pipe(ops.delay(6.0)).subscribe(print_threads_traces)

loop.call_soon(src.on_next, "Message0")

loop.run_forever()

```

This is where thread waits:

```
File: "main.py", line 58, in <module>
  loop.run_forever()
File: "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
  self._run_once()
File: "/usr/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
  handle._run()
File: "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
  self._callback(*self._args)
File: "RxPY/rx/scheduler/eventloop/asynciothreadsafescheduler.py", line 87, in interval
  sad.disposable = self.invoke_action(action, state=state)
File: "RxPY/rx/scheduler/scheduler.py", line 103, in invoke_action
  ret = action(self, state)
File: "RxPY/rx/core/operators/delay.py", line 69, in action
  result.accept(observer)
File: "RxPY/rx/core/notification.py", line 37, in accept
  return self._accept_observer(on_next)
File: "RxPY/rx/core/notification.py", line 99, in _accept_observer
  return observer.on_next(self.value)
File: "RxPY/rx/core/observer/autodetachobserver.py", line 26, in on_next
  self._on_next(value)
File: "mamicu.py", line 43, in log_and_push_another_one
  src.on_next(msg + "0")
File: "RxPY/rx/subject/subject.py", line 55, in on_next
  super().on_next(value)
File: "RxPY/rx/core/observer/observer.py", line 26, in on_next
  self._on_next_core(value)
File: "RxPY/rx/subject/subject.py", line 62, in _on_next_core
  observer.on_next(value)
File: "RxPY/rx/core/observer/autodetachobserver.py", line 26, in on_next
  self._on_next(value)
File: "RxPY/rx/core/operators/materialize.py", line 23, in on_next
  observer.on_next(OnNext(value))
File: "RxPY/rx/core/observer/autodetachobserver.py", line 26, in on_next
  self._on_next(value)
File: "RxPY/rx/core/operators/map.py", line 41, in on_next
  obv.on_next(result)
File: "RxPY/rx/core/observer/autodetachobserver.py", line 26, in on_next
  self._on_next(value)
File: "RxPY/rx/core/observer/autodetachobserver.py", line 26, in on_next
  self._on_next(value)
File: "RxPY/rx/core/operators/delay.py", line 55, in on_next
  cancelable.disposable = mad
File: "RxPY/rx/disposable/serialdisposable.py", line 39, in set_disposable
  old.dispose()
File: "RxPY/rx/disposable/multipleassignmentdisposable.py", line 47, in dispose
  old.dispose()
File: "RxPY/rx/disposable/compositedisposable.py", line 68, in dispose
  disp.dispose()
File: "RxPY/rx/disposable/disposable.py", line 41, in dispose
  self.action()
File: "RxPY/rx/scheduler/eventloop/asynciothreadsafescheduler.py", line 110, in dispose
  future.result()
File: "/usr/lib/python3.6/concurrent/futures/_base.py", line 427, in result
  self._condition.wait(timeout)
File: "/usr/lib/python3.6/threading.py", line 295, in wait
  waiter.acquire()
```

It does not have to be two delays in a row, it can be observe_on after delay, or anything that prevents next delay action to be rescheduled immediately (see comment in code example).

It may seem to you that it is not real world use case to push item into observable from the same thread and asyncio loop as observer, but it is really important sometimes to be able to do everything in one thread, including pushing new items sometimes.

It may seem to you that we should use basic  AsyncIOScheduler, but if sometimes we still need to do something from other threads, it becomes impossible, I have tried.

To me it seems that scheduler shouldn't really wait for that future, because:
1. Canceling in asyncio is best effort anyway.
2. Other scheduler don't seem to behave like that.
3. If I remove future, all tests pass anyway.

**Comment by MainRo** [comment]
The original discussion on the creation of the AsyncIOThreadsafeScheduler is here:
https://github.com/ReactiveX/RxPY/pull/249

This scheduler should not be used from an asyncio eventloop because it uses a blocking future for disposal (hence the deadlock you see). The aim of this scheduler is to synchronize a non-asyncio thread with another one running an asyncio event loop.

> It may seem to you that we should use basic AsyncIOScheduler, but if sometimes we still need to do something from other threads, it becomes impossible, I have tried.

Can you provide an example where you cannot schedule items from one thread to an asyncio event-loop thread ? It is the aim of the ThreadSafeAsyncioScheduler.

> To me it seems that scheduler shouldn't really wait for that future, because:
    - Canceling in asyncio is best effort anyway.
    - Other scheduler don't seem to behave like that.
    - If I remove future, all tests pass anyway.

yes, in the example you provided, waiting for the future can deadlock, and will block the event loop in all cases. As said before this is because this scheduler should not be used from an event-loop thread, but another thread.
Concerning the tests, maybe it was non-trivial to write, I do not remember. But the current implementation guarantees that when dispose returns:
- either the scheduled tasks have been canceled
- either the scheduled tasks have completed

But they cannot be scheduled past that point.

My understanding is that you have several event loops, and you need the ability to dispose subscriptions that are distributed between them. In this case there is effectively no way to wait for the cancellation with the dispose API, so probably we should not wait there.

**Comment by kormang** [comment]
I'm not trying to cancel anything. The cancellation happens implicitly by setting `cancelable.disposable = mad` in delay operator.
That happens when you have multiple operators that schedule, chained in pipe. That is how I have ran into this problem.
One way to avoid it is to change  `cancelable.disposable = mad` to something else that would not cancel. However I thought that it should be resolved on the level of canceling, the root cause.

Also, I don't have multiple loops. But I do have multiple threads. So imagine, expanded example from above. I have one thread,  which runs loop, and almost everything happens on that thread. I try to keep all scheduling there. Similar to what people do with GUI frameworks. All GUI frameworks I know have event loop at it's core, and everything happens on that loop. From callback on that loop you can also schedule another event on the loop. @dbrattli also mentions that [here](https://github.com/ReactiveX/RxPY/issues/565#issuecomment-812984084). I wonder, how does this scheduling and canceling work in those schedulers?

I also have one more thread, spawned by a library, which gets data from web socket, does some processing, especially filtering, and emits filtered data to the thread which runs event loop. I'm actually working on displacing that thread to a separate process, then this problem won't affect me, but still I think it should be addressed.

Problem I have is that project is not small, but I have example reduced to about 50 lines of code that illustrates it better (I can provide it if necessary). Also due to abstraction layers in the project and its size, it is difficult to keep track of what scheduler to use for what.

Even if things should work as they work now, at least I would expect exception to be raised, rather than silently falling into deadlock.

And finally, I have made changes, yesterday, to my PR. Now I try to detect situation of deadlock, and in such case fallback to behaviour of AsyncIOScheduler (not ThreadSafe), otherwise, wait for Future.
