### ISSUE TITLE
Can we explicitly run schedulers on demonic threads?

### ISSUE THREAD

**Issue by sachuin23** [ReactiveX/RxPY#57]
If the main thread dies, we see that the scheduled threads are still alive causing system to be in a weired state, is there a way to make scheduler threads demonic?

**Comment by dbrattli** [comment]
Yes, that is a good idea. Which scheduler are you using? Note that all operators that uses a scheduler accepts a scheduler as a parameter, but will use a default scheduler if not specified. The `EventLoopScheduler` accepts a thread_factory where you may decide how you create your threads. Maybe we should do something similar for other thread creating schedulers as well. But new threads should probably be daemonized by default.

**Comment by sachuin23** [comment]
I am using NewThreadScheduler currently to schedule a task. This prevents program to exit if there is a problem with the program running on main thread.
