### ISSUE TITLE
Merge operator signature is confusing

### ISSUE THREAD

**Issue by laclouis5** [ReactiveX/RxPY#583]
The return type of the merge operator is very confusing, why is is a function that takes an observable?

I expected its behavior to be something like:

```python
import rx
import rx.operators as ops

p1 = rx.of("Hello", "world!")
p2 = rx.just(42)

pub = ops.merge(p1, p2)

pub.subscribe(on_next=lambda item: print(item))
```

I do not understand the current behavior and the examples of the documentation do not clarify anything (they do not event show a concrete example of a merge).

**Comment by MainRo** [comment]
There are two variants of the merge operator:

- A [factory](https://rxpy.readthedocs.io/en/latest/reference_observable_factory.html?highlight=merge#rx.merge) operator: rx.merge
- A [pipable](https://rxpy.readthedocs.io/en/latest/reference_operators.html?highlight=merge#rx.operators.merge) operator: ops.merge

The behavior you expect is the one implemented in the factory operator:

```python
import rx
import rx.operators as ops

p1 = rx.of("Hello", "world!")
p2 = rx.just(42)

pub = rx.merge(p1, p2)
pub.subscribe(on_next=lambda item: print(item))
```

The pipable operator is handy when you want to merge two observables in an existing pipeline:

```python
import rx
import rx.operators as ops


p1 = rx.of("Hello", "world!")
p2 = rx.just(42)

pub = p1.pipe(
    ops.map(lambda i: i.upper()),
    ops.merge(p2),
)

pub.subscribe(on_next=lambda item: print(item))
```

This implementation takes an observable as an argument and merges it with the source observable of the operator.
