### ISSUE TITLE
Clarity on the correct import for `Observable`

### ISSUE THREAD

**Issue by CarstenLeue** [ReactiveX/RxPY#586]
Documentation for `Observable` documents it as `rx.Observable` (https://rxpy.readthedocs.io/en/latest/reference_observable.html#rx.Observable) so I would assume to import it as

```python
from rx import Observable
```

however [pylance ](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) reports this as an error:
![image](https://user-images.githubusercontent.com/7644517/138685771-2936bdfd-d261-48f5-a0ba-6483bb05ae2a.png)

I assume this is because `rx` does not list it as its exports in `__all__` from its `__init__.py`.

What is the intended way to import `Observable`? Would it be possible to list the official exports in `__init__.py` files?

**Comment by MainRo** [comment]
This does not look like a valid error to me: Observable is imported in __init__.py, so the example should be valid.
Can this be a pylance issue?

@dbrattli @erikkemperman @jcafhe any idea?

**Comment by dbrattli** [comment]
Yes, for Pylance to be happy we need to "export" `Observable` (and others) from:

- `__init__.py`
- `core/__init__.py`
- `core/observable/__init__.py`

By export I mean that the symbols that should be exported should be added to `__all__` in the the end of the `__init__.py` file:

```py
__all__ = ["Observable", ..]
```

**Comment by MainRo** [comment]
So we also have to explicitly export all functions defined in init.py?

**Comment by dbrattli** [comment]
Yes, that's my understanding. This is btw from a project where I use Pylance: https://github.com/cognitedata/Expression/blob/main/expression/__init__.py

**Comment by MainRo** [comment]
ah, this will be a looong list to add. Is this specific to pylance? I cannot find a source of information that mandates to export public symbols in __all__.

**Comment by dbrattli** [comment]
This issue will be fixed in the next release
