### ISSUE TITLE
"DeQue" import error

### ISSUE THREAD

**Issue by FrancoMSarabia** [ReactiveX/RxPY#594]
There is an error that Deque cannot be imported in the trampoline.py file.

![image](https://user-images.githubusercontent.com/25891319/150049217-91a2fff4-31ea-42bf-bb8f-305ab60194ec.png)

**Comment by MainRo** [comment]
Can you post the actual error that you have - as text and not an image please - and the version of python that you use?

**Comment by dbrattli** [comment]
This means that the Python version used is too old and not supported this library.
