### ISSUE TITLE
error when calling on_completed on sampled observable

### ISSUE THREAD

**Issue by louisChiffre** [ReactiveX/RxPY#60]
When creating a stream using the "sample" method with an observable as sampler, I get the following error when on_completed is called "TypeError: sample_subscribe() takes exactly 1 argument (0 given)"

Here is a the sample code how to reproduce it:

    import rx

    def show(x):
        print x

    obs = rx.subjects.Subject()
    sampler = rx.subjects.Subject()

    obs.sample(sampler=sampler).subscribe(show)

    obs.on_next(1)
    sampler.on_next(0)

    sampler.on_completed()

And the output:

    1
    Traceback (most recent call last):
      File "sample_test.py", line 14, in <module>
        sampler.on_completed()
      File "/usr/local/lib/python2.7/dist-packages/rx/subjects/subject.py", line 57, in on_completed
        observer.on_completed()
      File "/usr/local/lib/python2.7/dist-packages/rx/abstractobserver.py", line 35, in on_completed
        self._completed()
    TypeError: sample_subscribe() takes exactly 1 argument (0 given)

Thanks for your help

**Comment by dbrattli** [comment]
Added a quick fix to the devel branch. Hope it fixes your problems.

**Comment by louisChiffre** [comment]
Great, thanks for the fix. It fixed the problem!
