### ISSUE TITLE
Python 2 vs. 3 incompatibility?

### ISSUE THREAD

**Issue by hugadams** [ReactiveX/RxPY#61]
Hi,

Thanks for putting this library together!  I'm really enjoying learning about reactive extensions.

One issue I've encountered is that some of the examples (for example ironpython) have Python 2.x print statements.  EG:

```
print "x y z"
```

So will not run in Python 3.x.  However, the notebook tutorial has statements like:

```
xs = d.subscribe(print)
```

Which only works in Python 3.x.  How would one subscribe the print function in Python 2.x?

**Comment by jdreaver** [comment]
You could always do `from __future__ import print_function`, which will make `print` a function in Python 2.

**Comment by dbrattli** [comment]
IronPython is only Python-2.7. But can try if `print_function` exists there.

**Comment by hugadams** [comment]
Ok, thanks.  Sorry, probably not big deal enough to have created issue.

@dbrattli Thanks for your help over twitter.  I as able to get my streams connected in Twisted.
