### ISSUE TITLE
hot child and cold parent in `with_latest_from` 

### ISSUE THREAD

**Issue by AstrickHarren** [ReactiveX/RxPY#631]
Hi dev, this code doesn't output anything despite a print action
```py
# also doesn't work if `state = rx.interval(..)`
state = rx.from_iterable([1, 2, 3]).pipe(
    ops.replay(buffer_size=1)
)

state.connect()

query = rx.from_iterable([1, 2, 3]).pipe(
    ops.with_latest_from(state),
    ops.do_action(print)
)

# works if subscribed with thread pool scheduler
query.subscribe()
```
It seems the reason is the implementation of `with_latest_from` subscribes parent first before children, and therefore handles parent event before the child. But prior to that, the parent completes, which I assume disposes the entire `query` and disposes the child. 

A workaround is to publish the parent first and then manually connect later after the subscription.

**Comment by dbrattli** [comment]
Thanks for the issue. This will be fixed in the next release.
