### ISSUE TITLE
ReactiveX wheel distribution name does not match .dist-info folder name 

### ISSUE THREAD

**Issue by chowder** [ReactiveX/RxPY#643]
Using the latest `reactivex` wheel (4.0.0) as an example, the wheel name is:

- `ReactiveX-4.0.0-py3-none-any.whl`

But the dist-info file is named:

- `reactivex-4.0.0.dist-info`

Contrast this with the older `Rx` wheels: 

- `Rx-3.2.0-py3-none-any.whl`
- `Rx-3.2.0.dist-info`

Now this is an extremely minute issue - but it does break the [dependency resolver for Bazel](https://github.com/bazelbuild/rules_python/blob/beed9a257cc493ebf5aa7b8e6bbe577fa637e8f6/packaging/whl.py#L68-L72), which expects the syntax `{distribution}-{version}.dist-info`. 

[PEP 491](https://peps.python.org/pep-0491/#file-contents) somewhat outlines the naming convention for wheel contents relative to its wheel file.

**Additional context**
 - RxPY version 4.0.0

**Comment by dbrattli** [comment]
Thanks for filing the issue @chowder. I think this could be solved my making the package all lowercase as well. I.e from PEP-8: "Python packages should also have short, all-lowercase names, although the use of underscores is discouraged". Then the wheel name should also become lowercase. If you think this would be the right solution, then I can try to build a new release!?

**Comment by chowder** [comment]
Thanks for looking into this, @dbrattli. (and congratulations/many thanks for shipping v4!) 

I do agree that this could be simply fixed by making the package name lowercase, but the fact that the generated folder name differs at all was a little strange to me (possibly a bug with Poetry...?) 

But if PEP-8 says package names should be lowercase to begin with then I have no objections. :)

Additionally also wanted to point out that up until 4.0.0a3 this was ok - until it was later changed here: https://github.com/ReactiveX/RxPY/commit/becb44c29e563c261d8e1a34dd94e68144fea481, as evidenced by the uploaded wheels on PyPi:

![Screenshot_20220510-231722_Brave](https://user-images.githubusercontent.com/16789070/167730821-f92d4b0f-fdd2-417d-8b8d-f85d9233626f.jpg)

**Comment by dbrattli** [comment]
Ok, thanks for investigating this. Then I think the right thing to do is to change it back.
