### ISSUE TITLE
Concurrency in RxPY

### ISSUE THREAD

**Issue by smeder** [ReactiveX/RxPY#65]
Hi,

Not sure where else to ask this, but I don't see how the library is able to support actual concurrent operation. The recursive scheduler in particular seems to actually serialize computation for the stream. From scheduledobserver.py:

```python
        try:
            work()
        except Exception:
            with self.lock:
                parent.queue = []
                parent.has_faulted = True
            raise

        recurse()
```

i.e. work() is called followed by recurse() which serializes processing of the stream (and does preserve order). My understanding is that one should be able to get concurrency via different scheduler choices (potentially giving up preserving order). Am I missing something?

**Comment by dbrattli** [comment]
Yes, the Rx contract ensures that events are processed in order for a given subscription. However, you may let Rx process items concurrently between multiple subscriptions:

```python
import time
import logging

from rx.concurrency import NewThreadScheduler
from rx.subjects import Subject

logging.basicConfig(format="%(threadName)s:%(message)s")
log = logging.getLogger("Rx")
log.setLevel(logging.DEBUG)

scheduler = NewThreadScheduler()
stream = Subject()
obs = stream.observe_on(scheduler)

s1 = obs.select(lambda x: x * 10).tap(lambda x: log.debug(x)).subscribe()
s2 = obs.select(lambda x: x / 10).tap(lambda x: log.debug(x)).subscribe()

stream.on_next(42)

time.sleep(2)
```

This example will have 2 subscriptions processing items on separate threads, producing the following output:

```
Thread-1:420
Thread-2:4.2
```
Does this answer your question?

**Comment by dbrattli** [comment]
In order to get concurrency for multiple operators for a single subscription:

```python
import time
import logging

from rx.concurrency import NewThreadScheduler
from rx.subjects import Subject

logging.basicConfig(format="%(threadName)s:%(message)s")
log = logging.getLogger("Rx")
log.setLevel(logging.DEBUG)

scheduler = NewThreadScheduler()
stream = Subject()
obs = stream.observe_on(scheduler)

s2 = obs.select(
        lambda x: x * 10
    ).tap(
        lambda x: log.debug(x)
    ).observe_on(scheduler).select(
        lambda x: x * 10
    ).tap(
        lambda x: log.debug(x)
    ).subscribe()

for x in range(10):
    stream.on_next(x)

time.sleep(2)
```
This produces different results every time you run it, but each `select()` still processes events in order:

```
Thread-1:0
Thread-1:10
Thread-1:20
Thread-1:30
Thread-1:40
Thread-2:0
Thread-1:50
Thread-2:100
Thread-1:60
Thread-2:200
Thread-1:70
Thread-2:300
Thread-1:80
Thread-2:400
Thread-1:90
Thread-2:500
Thread-2:600
Thread-2:700
Thread-2:800
Thread-2:900
```

**Comment by smeder** [comment]
Thanks for taking the time to answer. I didn't realize that that was part of the contract. For the application I had in mind there is no inherent need to preserve ordering, so I'll have to think about whether it still makes sense to put the computation in this framework. I could probably re-arrange things so I get the desired outcome, but it may look a bit weird/forced - we'll see.
