### ISSUE TITLE
it would be kind for pip system if you could publish directly a wheel

### ISSUE THREAD

**Issue by stonebig** [ReactiveX/RxPY#66]
method:
````
python setup.py sdist bdist_wheel  --universal
twine upload dist/*
````

reason:
- if you build  a system  with `pip -r requirements.txt` any tar.gz package in a requirement file is first transform as a wheel, and so if it needs a package for this, you have to create a requirements0.txt file and pip it first, adding complexity to a 'solved by wheel' problem otherwise,
- when a majority of packages on pip will be 'wheels', the packaging team may be able to raise the bar to next level ('whoops' , 'wings', ...)

**Comment by dbrattli** [comment]
Thanks, didn't know about this. I'll try to do this next time.
