### ISSUE TITLE
observe_on does not allow parallel processing

### ISSUE THREAD

**Issue by yarosla** [ReactiveX/RxPY#67]
The following code tries to use `.observe_on(Scheduler.timeout)` to run tasks in parallel:

    import time
    import threading
    import rx
    from rx.concurrency.scheduler import Scheduler
    
    tm1=time.time()
    lock=threading.Lock()
    
    def log(s):
      tm2=time.time()
      with lock:
        print '%ds: %s on %s' % (round(tm2-tm1), s, threading.currentThread().name)
    
    def work(x):
      log('processing '+str(x))
      time.sleep(1)
    
    def finish(x):
      log('finished '+str(x))
    
    log('started')
    
    rx.Observable.range(1, 3) \
      .observe_on(Scheduler.timeout) \
      .do_action(work) \
      .subscribe(finish)
    
    log('finished ALL')
    time.sleep(5) # wait to complete

Expected output:

    0s: started on MainThread
    0s: finished ALL on MainThread
    0s: processing 1 on Thread-1
    0s: processing 2 on Thread-2
    0s: processing 3 on Thread-3
    1s: finished 1 on Thread-1
    1s: finished 2 on Thread-2
    1s: finished 3 on Thread-3
    
Actual output:

    0s: started on MainThread
    0s: processing 1 on Thread-1
    0s: finished ALL on MainThread
    1s: finished 1 on Thread-1
    1s: processing 2 on Thread-2
    2s: finished 2 on Thread-2
    2s: processing 3 on Thread-3
    3s: finished 3 on Thread-3

The problem seems to be in the design of `ScheduledObserver` class. The `run` method does not schedule next queued item until current item is processed.

**Comment by yarosla** [comment]
After further investigation I've found that serial execution is not a bug but rather [intended behavior][1].

And here is the code that does work in parallel:

    Observable.range(1, 3) \
      .select_many(lambda i: Observable.start(lambda: work(i), scheduler=Scheduler.timeout)) \
      .observe_on(Scheduler.event_loop) \
      .subscribe(finish)

Although there is no guarantee that `finish` method is called in initial `range` order.

  [1]: http://stackoverflow.com/a/16660155/697313

**Comment by dbrattli** [comment]
Thanks for sharing this. I will probably use your example in the tutorial since there are many people asking about this.
