### ISSUE TITLE
[Question] Reading/writing from/to a Pandas DataFrame in rxpy

### ISSUE THREAD

**Issue by KickItLikeShika** [ReactiveX/RxPY#687]
It's my first time to use `rxpy`, and i have been struggling a bit to read data from a csv file and then save it again into a csv file, i always use pandas to deal with csv's (if someone has a better way to deal with csv's in rxpy please share it!). 

```py
data = from_(pd.read_csv("dataset.csv").itertuples(index=False))
output = data.pipe(
        op.filter(lambda row: is_good_sample(row))
    ).subscribe(
        on_completed=print("done")
    )
```
now i want to access the filtered items to store the output again in a csv file, how can i do that? and is there a better way to do this?

**Comment by KickItLikeShika** [comment]
just realized how this should work, thanks!

**Comment by MainRo** [comment]
I you're doing data transforms with rxpy you might be interested in [makinage](https://www.makinage.org/) and [rxcsi](https://github.com/maki-nage/rxsci). It contains operators that complement rxpy and some operators to convert an observable [from](https://www.makinage.org/doc/rxsci/latest/operators_other.html#rxsci.ops.from_pandas) and [to](https://www.makinage.org/doc/rxsci/latest/operators_other.html#rxsci.ops.to_pandas) pandas.
