### ISSUE TITLE
Zip operator does not work

### ISSUE THREAD

**Issue by QZero233** [ReactiveX/RxPY#695]
**Describe the bug**
I ran the code on the migration document (https://rxpy.readthedocs.io/en/latest/migration.html) which uses zip operator, but there is no output at all

**To Reproduce**
Run the code below, this code can be found at https://rxpy.readthedocs.io/en/latest/migration.html, paragraph with subtitle "Removal Of The Result Mapper" 

```python
import rx
from rx import operators as ops
import operator

a = rx.of(1, 2, 3, 4)
b = rx.of(2, 2, 4, 4)

a.pipe(
    ops.zip(b), # returns a tuple with the items of a and b
    ops.map(lambda z: operator.mul(z[0], z[1]))
).subscribe(print)
```

**Expected behavior**
Expect it will output
(1,2)
(2,2)
(3,4)
(4,4)

**Actual behavior**
There is no output at all

**Additional context**
 - OS Windows 10 x64
 - RxPY version 4.0.4
 - Python version 3.10.9

**Comment by QZero233** [comment]
I've found the reason, this happens because the observable "complete" before the emitting
If I run the code below
```python
def f(o,s):
    o.on_next(1)
    o.on_next(3)
    # o.on_completed()

def g(o,s):
    o.on_next(2)
    o.on_next(4)
    # o.on_completed()

a=create(f)
b=create(g)

c=rx.zip(a,b)

c.subscribe(
    on_next=print,
    on_error=print,
    on_completed=lambda : print("Completed")
)
```
There will be output, but if I add `o.on_completed()` at the end of `f` and `g`, then there will be just "Completed" output

**Comment by matiboy** [comment]
Hi @QZero233 

Thank you for opening this issue;
I just tried the above code (almost exactly) on Windows 10, RxPy 4.04 and Python 3.9 - so almost same as your set up - and the output shows as expected: 2, 4, 12, 16 (since you have the `mul` operator)

The only change I made was to import reactivex rather than rx since that's the correct import in v4.

**Comment by QZero233** [comment]
> 

Thank you, it works after replacing "rx" with "reactivex"
