### ISSUE TITLE
use relative imports for all imports

### ISSUE THREAD

**Issue by guillermooo** [ReactiveX/RxPY#72]
Currently absolute imports are used. This prevents the rxpy package to be easily included in other packages, when a package manager/installer isn't available (for example, a Python-extensible app that imposes non-standard requirements). By using relative imports, it'd be easy to just drop the rxpy package in a larger package and be able to import it.

IIRC, relative imports are available since py2.5 (?) so this shouldn't affect compat?

**Comment by dbrattli** [comment]
According to [PEP8](https://www.python.org/dev/peps/pep-0008/) absolute imports are recommended ... but explicit relative imports are an acceptable alternative to absolute imports. I don't have any strong feelings about this issue, so you're welcome to make a pull request.

**Comment by guillermooo** [comment]
There will be imports like `...xxx` and maybe even `....xxx`. Not sure if that's acceptable.
