### ISSUE TITLE
thread_pool scheduler

### ISSUE THREAD

**Issue by Sovetnikov** [ReactiveX/RxPY#73]
Is there any plans to implement thread_pool scheduler?

**Comment by dbrattli** [comment]
No plans right now. We should probably align with [ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html).

**Comment by dbrattli** [comment]
Initial support added to develop. Python 3 only because of the `concurrent.futures` module.

**Comment by Sovetnikov** [comment]
Great!
But i suppose you are right about ProcessPoolExecutor, because of python GIL.
