### ISSUE TITLE
Observable.repeat() causes maximum recursion depth exceeded

### ISSUE THREAD

**Issue by serathius** [ReactiveX/RxPY#76]
Rx version: 1.2.4
on both python2 and python3.

I'm new to rx and maybe I'm doing something wrong but using repeat with value > 60 causes RuntimeError: maximum recursion depth exceeded while calling a Python object.

Code example:
`Observable.just(0).repeat().subscribe(lambda _: None)`

**Comment by dbrattli** [comment]
Not sure if or what is wrong, but it seems to be related to `just()` defaulting to `immediate_scheduler` which makes `repeat()` recurse around itself. If you choose a trampoline based scheduler such as `current_thread_scheduler` you should not get this problem. I'll take a better look at it during the weekend.

```python
from rx.concurrency import Scheduler
Observable.just(0, Scheduler.current_thread).repeat().subscribe(lambda _: None)
```
