### ISSUE TITLE
Docs for Observable instance and class method

### ISSUE THREAD

**Issue by AlexMost** [ReactiveX/RxPY#84]
Would be very helpful to add the list with of all supported Observable methods to some .md file, like here - [rxjs_observable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md). I guess they are using something to autogenerate that.

**Comment by ninmesara** [comment]
I've started working on this (#101).
The HTML docs can be found [here](https://ninmesara.github.io/RxPY/). They're mostly automatically generated and should be regarded as a skeleton upon which to build write proper docs.

The operators are documented. For example: [all](https://ninmesara.github.io/RxPY/api/operators/all.html), [zip](https://ninmesara.github.io/RxPY/api/operators/zip.html).

**Comment by AlexMost** [comment]
awesome !!!

**Comment by erikkemperman** [comment]
The docs are now hosted on readthedocs: https://rxpy.readthedocs.io/en/latest/.

Specifically, the operators are here: https://rxpy.readthedocs.io/en/latest/reference_operators.html

Closing this issue now, feel free to re-open if anything is missing!
