### ISSUE TITLE
Keyword arg Scheduler not used in start_with

### ISSUE THREAD

**Issue by rjayatilleka** [ReactiveX/RxPY#85]
In `rx/linq/observable/startswith.py`, the scheduler is fetched from the keyword args. However, it's then immediately overridden by the following if-else. I'm not sure if allowing a scheduler in the keywords is desired, but either way, I think that the current implementation is mistaken.

I don't actually use the scheduler arg (I was looking at start_with for something else), so this isn't high priority for me. I just wanted to bring it up.

**Comment by dbrattli** [comment]
Thanks a lot, and nicely spotted!  Will fix
