### ISSUE TITLE
Process is Blocked when an Error occurs in an Observable.interval Chain

### ISSUE THREAD

**Issue by frederikaalund** [ReactiveX/RxPY#90]
The following program illustrates the problem:

	import rx
	import time

	sub = rx.Observable.interval(1000) \
		.map(lambda x: 0/(5-x)) \
		.subscribe(print, print, print)

	try:
		while True:
			time.sleep(0.1)
	except:
		sub.dispose()

The `map` call will cause a division by 0 exception to occur if x is 5. Since `Observable.interval` emits 0, 1, 2, 3, ... this will happen after 6 seconds.

If you exit via a keyboard interrupt (Ctrl+C) *before* the exception occurs, the program exits normally (since `dispose` is called, cancelling the `Observable` subscription).

However, if you exit *after* the exception occurs, the process never ends. Some thread (probably the one controlling `Observable.interval`) seems to be blocking the process.
Pressing Ctrl+C again causes the following error to show:

	Exception ignored in: <module 'threading' from '/opt/sd/lib/python3.5/threading.py'>
	Traceback (most recent call last):
	  File "/opt/sd/lib/python3.5/threading.py", line 1288, in _shutdown
	    t.join()
	  File "/opt/sd/lib/python3.5/threading.py", line 1054, in join
	    self._wait_for_tstate_lock()
	  File "/opt/sd/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
	    elif lock.acquire(block, timeout):
	KeyboardInterrupt

I would have thought that an error would cancel the controlling thread (of `Observale.interval`), but this does not seem to be the case. What gives?

I'm using Python 3.5.1 and RxPY 1.2.2.

**Comment by dbrattli** [comment]
Added a fix to develop. Looks like there were still some threads that were not daemonized.

**Comment by frederikaalund** [comment]
That's great news. Cheers for the quick bugfix! I'll test the devel branch tomorrow.

**Comment by frederikaalund** [comment]
I just tested the commit, and it completely solved the issue. Thanks again.
Is there any way to disable the debugging output? My logs are getting filled with:

	[stdout] ****************
	[stdout] ([<rx.core.anonymousobservable.AnonymousObservable object at 0x2fceef30>, <rx.core.anonymousobservable.AnonymousObservable object at 0x2fcee1b0>],)
	[stdout] [<rx.core.anonymousobservable.AnonymousObservable object at 0x2fceef30>, <rx.core.anonymousobservable.AnonymousObservable object at 0x2fcee1b0>]
	[stdout] ****************
	[stdout] ([<rx.core.anonymousobservable.AnonymousObservable object at 0x2fcf17d0>, <rx.core.anonymousobservable.AnonymousObservable object at 0x2fcf1d90>],)
	[stdout] [<rx.core.anonymousobservable.AnonymousObservable object at 0x2fcf17d0>, <rx.core.anonymousobservable.AnonymousObservable object at 0x2fcf1d90>]
	[stdout] ****************

Using `logging.getLogger('Rx').setLevel(logging.INFO)` does not work since the output seems to go directly to stdout.
