### ISSUE TITLE
Observable.interval raises "AttributeError: 'int' object has no attribute 'dispose'" with the AsyncIOScheduler

### ISSUE THREAD

**Issue by frederikaalund** [ReactiveX/RxPY#91]
The following program illustrates the problem:

	import asyncio
	import rx
	import time

	scheduler = rx.concurrency.AsyncIOScheduler()
	sub0 = rx.Observable.interval(1000, scheduler=scheduler) \
		.subscribe(print, print, print)

	try:
		loop = asyncio.get_event_loop()
		loop.run_forever()
	except:
		pass

	sub0.dispose()

I would expect the above to exit normally. However, I get the following error message instead:

	Traceback (most recent call last):
	  File "./rx_test.py", line 17, in <module>
		sub0.dispose()
	  File "/opt/sd/lib/python3.5/site-packages/rx/autodetachobserver.py", line 40, in dispose
		self.m.dispose()
	  File "/opt/sd/lib/python3.5/site-packages/rx/disposables/booleandisposable.py", line 50, in dispose
		old.dispose()
	  File "/opt/sd/lib/python3.5/site-packages/rx/disposables/compositedisposable.py", line 63, in dispose
		disposable.dispose()
	  File "/opt/sd/lib/python3.5/site-packages/rx/disposables/booleandisposable.py", line 50, in dispose
		old.dispose()
	AttributeError: 'int' object has no attribute 'dispose'

Python 3.5.1 and RxPY master branch (where I have applied the fix for issue #90).

**Comment by frederikaalund** [comment]
Just tested the develop branch. The issue is there too.

**Comment by frederikaalund** [comment]
I noticed that the `Observable.interval` normally outputs 0, 1, 2, 3, ... but with the AsyncIOScheduler, it outputs 0, 0, 0, 0, ...

**Comment by dbrattli** [comment]
I think I've found the bug. Creating a fix soon ...

**Comment by frederikaalund** [comment]
Ah, excellent. I had a pull request on the way (see [this commit](https://github.com/frederikaalund/RxPY/commit/97a6fa5786fe351968df66ac17fdd0afeb939ada)) but I much prefer a fix from the original author. Cheers!

**Comment by dbrattli** [comment]
Yes, you are right, and thanks a lot for reporting these issues. It also uncovered a different problem. We also have to check that scheduled actions returns disposables before using the return value as a disposable. Usually an action returns None, so it's not a problem. I'll make some more fixes later.

**Comment by frederikaalund** [comment]
You're welcome. Cheers for the timely replies and fixes! I will test the latter tomorrow.

**Comment by frederikaalund** [comment]
Just tested b2836e7 and it completely solves the issue. Cheers!
