### ISSUE TITLE
How can I subscribe to an Observable on a remote machine using RxPy?

### ISSUE THREAD

**Issue by mchen402** [ReactiveX/RxPY#93]
[This can be achieved using IObservable.Remotable using the .NET flavour of Rx](http://stackoverflow.com/questions/3202545/can-reactive-extensions-rx-be-used-across-process-or-machine-boundaries), but what about in Python with RxPy?

**Comment by dbrattli** [comment]
Not yet. The problem is that there are so many ways to do this, so RxPY does not support Remotable. But it should be quite straight forward to use a distributed message queue such as ZMQ or Azure service bus or similar. The problem arises when you want to submit queries remotely using Qbservables. I've done some experimenting in a private branch https://github.com/dbrattli/RxPY/blob/feature/provider/rx/observablequery.py

But actually I'm just waiting for IRP to be open source: http://www.infoq.com/presentations/cloud-rx

**Comment by mchen402** [comment]
Thanks Dag, I took a look at your private branch. However, I'm not so familiar with the `ast` or `bonsai` libraries and feel like I'm missing the point of `ObservableQuery` and `Qbservables`.
 - I see that `Qbservables` are just like `Observables` but all arguments of linq operators that take lambdas now take lambdas as a string. I.e. `observable.map(lambda x: x + 1)` vs `qbservable.map("lambda x: x + 1")` -- what is the point of doing this? Is this to overcome the fact that lambdas cannot be pickled?
 - From what I gather, the idea is to have `qbservable` versions of all linq operators that is sent to and executed on a remote server rather than locally. Is that right?
 - How are messages from a server transmitted to a client? For instance, let's say the server wants to tell a client that an observable has completed. How does it do this?

It'd be very helpful for those like me who know a bit of [`twisted` ](https://twistedmatrix.com/trac/) (but not `ast` or `bonsai`)  if you could knock up a minimal working example of how to use `Qbervables` with `twisted`. One example might be an Rx echo server: the client sends `'Hello World'` to the server and the server response with something like `observable.from_iterable('Hello World')` which the client can subscribe to.

> But actually I'm just waiting for IRP to be open source: http://www.infoq.com/presentations/cloud-rx

For those of us who are working on immediate deliverables and cannot wait, it would be good if you include `Qbservables` in the main Rx library so as to define some standard way of subscribing to remote observables. It would save people (like me) from attempting to roll their own half-baked/rushed solution only to find out it doesn't work for many complex/edge cases (my attempt fell apart when I needed to remotely subscribe to an Observable stream of Observables)

**Comment by dbrattli** [comment]
RxPY is not a product and is currently being developed in my spare time. Feel free to contribute if you need functionality that is not already included.
